;; generated by gen_imports.py from imports.spec - do not edit

%include "x64inc.inc"
%include "asm-calls.inc"

extern IDirectSound_QueryInterface_c
extern IDirectSound_AddRef_c
extern IDirectSound_Release_c
extern IDirectSound_CreateSoundBuffer_c
extern IDirectSound_GetCaps_c
extern IDirectSound_DuplicateSoundBuffer_c
extern IDirectSound_SetCooperativeLevel_c
extern IDirectSound_Compact_c
extern IDirectSound_GetSpeakerConfig_c
extern IDirectSound_SetSpeakerConfig_c
extern IDirectSound_Initialize_c
extern IDirectSoundBuffer_QueryInterface_c
extern IDirectSoundBuffer_AddRef_c
extern IDirectSoundBuffer_Release_c
extern IDirectSoundBuffer_GetCaps_c
extern IDirectSoundBuffer_GetCurrentPosition_c
extern IDirectSoundBuffer_GetFormat_c
extern IDirectSoundBuffer_GetVolume_c
extern IDirectSoundBuffer_GetPan_c
extern IDirectSoundBuffer_GetFrequency_c
extern IDirectSoundBuffer_GetStatus_c
extern IDirectSoundBuffer_Initialize_c
extern IDirectSoundBuffer_Lock_c
extern IDirectSoundBuffer_Play_c
extern IDirectSoundBuffer_SetCurrentPosition_c
extern IDirectSoundBuffer_SetFormat_c
extern IDirectSoundBuffer_SetVolume_c
extern IDirectSoundBuffer_SetPan_c
extern IDirectSoundBuffer_SetFrequency_c
extern IDirectSoundBuffer_Stop_c
extern IDirectSoundBuffer_Unlock_c
extern IDirectSoundBuffer_Restore_c
extern IDirectSound3DListener_QueryInterface_c
extern IDirectSound3DListener_AddRef_c
extern IDirectSound3DListener_Release_c
extern IDirectSound3DListener_GetAllParameters_c
extern IDirectSound3DListener_GetDistanceFactor_c
extern IDirectSound3DListener_GetDopplerFactor_c
extern IDirectSound3DListener_GetOrientation_c
extern IDirectSound3DListener_GetPosition_c
extern IDirectSound3DListener_GetRolloffFactor_c
extern IDirectSound3DListener_GetVelocity_c
extern IDirectSound3DListener_SetAllParameters_c
extern IDirectSound3DListener_SetDistanceFactor_c
extern IDirectSound3DListener_SetDopplerFactor_c
extern IDirectSound3DListener_SetOrientation_c
extern IDirectSound3DListener_SetPosition_c
extern IDirectSound3DListener_SetRolloffFactor_c
extern IDirectSound3DListener_SetVelocity_c
extern IDirectSound3DListener_CommitDeferredSettings_c
extern IDirectSound3DBuffer_QueryInterface_c
extern IDirectSound3DBuffer_AddRef_c
extern IDirectSound3DBuffer_Release_c
extern IDirectSound3DBuffer_GetAllParameters_c
extern IDirectSound3DBuffer_GetConeAngles_c
extern IDirectSound3DBuffer_GetConeOrientation_c
extern IDirectSound3DBuffer_GetConeOutsideVolume_c
extern IDirectSound3DBuffer_GetMaxDistance_c
extern IDirectSound3DBuffer_GetMinDistance_c
extern IDirectSound3DBuffer_GetMode_c
extern IDirectSound3DBuffer_GetPosition_c
extern IDirectSound3DBuffer_GetVelocity_c
extern IDirectSound3DBuffer_SetAllParameters_c
extern IDirectSound3DBuffer_SetConeAngles_c
extern IDirectSound3DBuffer_SetConeOrientation_c
extern IDirectSound3DBuffer_SetConeOutsideVolume_c
extern IDirectSound3DBuffer_SetMaxDistance_c
extern IDirectSound3DBuffer_SetMinDistance_c
extern IDirectSound3DBuffer_SetMode_c
extern IDirectSound3DBuffer_SetPosition_c
extern IDirectSound3DBuffer_SetVelocity_c
extern IDirectDraw_QueryInterface_c
extern IDirectDraw_AddRef_c
extern IDirectDraw_Release_c
extern IDirectDraw_Compact_c
extern IDirectDraw_CreateClipper_c
extern IDirectDraw_CreatePalette_c
extern IDirectDraw_CreateSurface_c
extern IDirectDraw_DuplicateSurface_c
extern IDirectDraw_EnumDisplayModes_c
extern IDirectDraw_EnumSurfaces_c
extern IDirectDraw_FlipToGDISurface_c
extern IDirectDraw_GetCaps_c
extern IDirectDraw_GetDisplayMode_c
extern IDirectDraw_GetFourCCCodes_c
extern IDirectDraw_GetGDISurface_c
extern IDirectDraw_GetMonitorFrequency_c
extern IDirectDraw_GetScanLine_c
extern IDirectDraw_GetVerticalBlankStatus_c
extern IDirectDraw_Initialize_c
extern IDirectDraw_RestoreDisplayMode_c
extern IDirectDraw_SetCooperativeLevel_c
extern IDirectDraw_SetDisplayMode_c
extern IDirectDraw_WaitForVerticalBlank_c
extern IDirectDraw2_QueryInterface_c
extern IDirectDraw2_AddRef_c
extern IDirectDraw2_Release_c
extern IDirectDraw2_Compact_c
extern IDirectDraw2_CreateClipper_c
extern IDirectDraw2_CreatePalette_c
extern IDirectDraw2_CreateSurface_c
extern IDirectDraw2_DuplicateSurface_c
extern IDirectDraw2_EnumDisplayModes_c
extern IDirectDraw2_EnumSurfaces_c
extern IDirectDraw2_FlipToGDISurface_c
extern IDirectDraw2_GetCaps_c
extern IDirectDraw2_GetDisplayMode_c
extern IDirectDraw2_GetFourCCCodes_c
extern IDirectDraw2_GetGDISurface_c
extern IDirectDraw2_GetMonitorFrequency_c
extern IDirectDraw2_GetScanLine_c
extern IDirectDraw2_GetVerticalBlankStatus_c
extern IDirectDraw2_Initialize_c
extern IDirectDraw2_RestoreDisplayMode_c
extern IDirectDraw2_SetCooperativeLevel_c
extern IDirectDraw2_SetDisplayMode_c
extern IDirectDraw2_WaitForVerticalBlank_c
extern IDirectDraw2_GetAvailableVidMem_c
extern IDirectDrawSurface_QueryInterface_c
extern IDirectDrawSurface_AddRef_c
extern IDirectDrawSurface_Release_c
extern IDirectDrawSurface_AddAttachedSurface_c
extern IDirectDrawSurface_AddOverlayDirtyRect_c
extern IDirectDrawSurface_Blt_c
extern IDirectDrawSurface_BltBatch_c
extern IDirectDrawSurface_BltFast_c
extern IDirectDrawSurface_DeleteAttachedSurface_c
extern IDirectDrawSurface_EnumAttachedSurfaces_c
extern IDirectDrawSurface_EnumOverlayZOrders_c
extern IDirectDrawSurface_Flip_c
extern IDirectDrawSurface_GetAttachedSurface_c
extern IDirectDrawSurface_GetBltStatus_c
extern IDirectDrawSurface_GetCaps_c
extern IDirectDrawSurface_GetClipper_c
extern IDirectDrawSurface_GetColorKey_c
extern IDirectDrawSurface_GetDC_c
extern IDirectDrawSurface_GetFlipStatus_c
extern IDirectDrawSurface_GetOverlayPosition_c
extern IDirectDrawSurface_GetPalette_c
extern IDirectDrawSurface_GetPixelFormat_c
extern IDirectDrawSurface_GetSurfaceDesc_c
extern IDirectDrawSurface_Initialize_c
extern IDirectDrawSurface_IsLost_c
extern IDirectDrawSurface_Lock_c
extern IDirectDrawSurface_ReleaseDC_c
extern IDirectDrawSurface_Restore_c
extern IDirectDrawSurface_SetClipper_c
extern IDirectDrawSurface_SetColorKey_c
extern IDirectDrawSurface_SetOverlayPosition_c
extern IDirectDrawSurface_SetPalette_c
extern IDirectDrawSurface_Unlock_c
extern IDirectDrawSurface_UpdateOverlay_c
extern IDirectDrawSurface_UpdateOverlayDisplay_c
extern IDirectDrawSurface_UpdateOverlayZOrder_c
extern IDirectDrawPalette_QueryInterface_c
extern IDirectDrawPalette_AddRef_c
extern IDirectDrawPalette_Release_c
extern IDirectDrawPalette_GetCaps_c
extern IDirectDrawPalette_GetEntries_c
extern IDirectDrawPalette_Initialize_c
extern IDirectDrawPalette_SetEntries_c
extern IDirectDrawClipper_QueryInterface_c
extern IDirectDrawClipper_AddRef_c
extern IDirectDrawClipper_Release_c
extern IDirectDrawClipper_GetClipList_c
extern IDirectDrawClipper_GetHWnd_c
extern IDirectDrawClipper_Initialize_c
extern IDirectDrawClipper_IsClipListChanged_c
extern IDirectDrawClipper_SetClipList_c
extern IDirectDrawClipper_SetHWnd_c
global IDirectSoundVtbl_asm2c
global IDirectSoundBufferVtbl_asm2c
global IDirectSound3DListenerVtbl_asm2c
global IDirectSound3DBufferVtbl_asm2c
global IDirectDrawVtbl_asm2c
global IDirectDraw2Vtbl_asm2c
global IDirectDrawSurfaceVtbl_asm2c
global IDirectDrawPaletteVtbl_asm2c
global IDirectDrawClipperVtbl_asm2c

%ifidn __OUTPUT_FORMAT__, elf64
section .note.GNU-stack noalloc noexec nowrite progbits
section .text progbits alloc exec nowrite align=16
%else
%error "only elf64 (SysV) is supported"
%endif

align 16
IDirectSound_QueryInterface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound_QueryInterface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound_AddRef_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSound_AddRef_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSound_Release_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSound_Release_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSound_CreateSoundBuffer_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectSound_CreateSoundBuffer_c
        Call_Asm_Epilogue_0 4

align 16
IDirectSound_GetCaps_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound_GetCaps_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound_DuplicateSoundBuffer_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound_DuplicateSoundBuffer_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound_SetCooperativeLevel_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound_SetCooperativeLevel_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound_Compact_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSound_Compact_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSound_GetSpeakerConfig_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound_GetSpeakerConfig_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound_SetSpeakerConfig_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound_SetSpeakerConfig_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound_Initialize_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound_Initialize_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSoundBuffer_QueryInterface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSoundBuffer_QueryInterface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSoundBuffer_AddRef_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSoundBuffer_AddRef_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSoundBuffer_Release_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSoundBuffer_Release_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSoundBuffer_GetCaps_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSoundBuffer_GetCaps_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSoundBuffer_GetCurrentPosition_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSoundBuffer_GetCurrentPosition_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSoundBuffer_GetFormat_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectSoundBuffer_GetFormat_c
        Call_Asm_Epilogue_0 4

align 16
IDirectSoundBuffer_GetVolume_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSoundBuffer_GetVolume_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSoundBuffer_GetPan_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSoundBuffer_GetPan_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSoundBuffer_GetFrequency_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSoundBuffer_GetFrequency_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSoundBuffer_GetStatus_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSoundBuffer_GetStatus_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSoundBuffer_Initialize_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSoundBuffer_Initialize_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSoundBuffer_Lock_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 16
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov eax, [r11d+40]
        mov [rsp+8], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call IDirectSoundBuffer_Lock_c
        add rsp, 16
        Call_Asm_Epilogue_0 8

align 16
IDirectSoundBuffer_Play_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectSoundBuffer_Play_c
        Call_Asm_Epilogue_0 4

align 16
IDirectSoundBuffer_SetCurrentPosition_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSoundBuffer_SetCurrentPosition_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSoundBuffer_SetFormat_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSoundBuffer_SetFormat_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSoundBuffer_SetVolume_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSoundBuffer_SetVolume_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSoundBuffer_SetPan_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSoundBuffer_SetPan_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSoundBuffer_SetFrequency_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSoundBuffer_SetFrequency_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSoundBuffer_Stop_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSoundBuffer_Stop_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSoundBuffer_Unlock_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectSoundBuffer_Unlock_c
        Call_Asm_Epilogue_0 5

align 16
IDirectSoundBuffer_Restore_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSoundBuffer_Restore_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSound3DListener_QueryInterface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DListener_QueryInterface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DListener_AddRef_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSound3DListener_AddRef_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSound3DListener_Release_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSound3DListener_Release_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSound3DListener_GetAllParameters_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DListener_GetAllParameters_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DListener_GetDistanceFactor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DListener_GetDistanceFactor_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DListener_GetDopplerFactor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DListener_GetDopplerFactor_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DListener_GetOrientation_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DListener_GetOrientation_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DListener_GetPosition_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DListener_GetPosition_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DListener_GetRolloffFactor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DListener_GetRolloffFactor_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DListener_GetVelocity_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DListener_GetVelocity_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DListener_SetAllParameters_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DListener_SetAllParameters_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DListener_SetDistanceFactor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DListener_SetDistanceFactor_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DListener_SetDopplerFactor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DListener_SetDopplerFactor_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DListener_SetOrientation_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 16
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov eax, [r11d+40]
        mov [rsp+8], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call IDirectSound3DListener_SetOrientation_c
        add rsp, 16
        Call_Asm_Epilogue_0 8

align 16
IDirectSound3DListener_SetPosition_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectSound3DListener_SetPosition_c
        Call_Asm_Epilogue_0 5

align 16
IDirectSound3DListener_SetRolloffFactor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DListener_SetRolloffFactor_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DListener_SetVelocity_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectSound3DListener_SetVelocity_c
        Call_Asm_Epilogue_0 5

align 16
IDirectSound3DListener_CommitDeferredSettings_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSound3DListener_CommitDeferredSettings_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSound3DBuffer_QueryInterface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DBuffer_QueryInterface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DBuffer_AddRef_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSound3DBuffer_AddRef_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSound3DBuffer_Release_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectSound3DBuffer_Release_c
        Call_Asm_Epilogue_0 1

align 16
IDirectSound3DBuffer_GetAllParameters_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DBuffer_GetAllParameters_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DBuffer_GetConeAngles_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DBuffer_GetConeAngles_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DBuffer_GetConeOrientation_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DBuffer_GetConeOrientation_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DBuffer_GetConeOutsideVolume_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DBuffer_GetConeOutsideVolume_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DBuffer_GetMaxDistance_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DBuffer_GetMaxDistance_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DBuffer_GetMinDistance_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DBuffer_GetMinDistance_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DBuffer_GetMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DBuffer_GetMode_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DBuffer_GetPosition_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DBuffer_GetPosition_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DBuffer_GetVelocity_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectSound3DBuffer_GetVelocity_c
        Call_Asm_Epilogue_0 2

align 16
IDirectSound3DBuffer_SetAllParameters_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DBuffer_SetAllParameters_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DBuffer_SetConeAngles_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectSound3DBuffer_SetConeAngles_c
        Call_Asm_Epilogue_0 4

align 16
IDirectSound3DBuffer_SetConeOrientation_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectSound3DBuffer_SetConeOrientation_c
        Call_Asm_Epilogue_0 5

align 16
IDirectSound3DBuffer_SetConeOutsideVolume_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DBuffer_SetConeOutsideVolume_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DBuffer_SetMaxDistance_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DBuffer_SetMaxDistance_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DBuffer_SetMinDistance_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DBuffer_SetMinDistance_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DBuffer_SetMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectSound3DBuffer_SetMode_c
        Call_Asm_Epilogue_0 3

align 16
IDirectSound3DBuffer_SetPosition_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectSound3DBuffer_SetPosition_c
        Call_Asm_Epilogue_0 5

align 16
IDirectSound3DBuffer_SetVelocity_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectSound3DBuffer_SetVelocity_c
        Call_Asm_Epilogue_0 5

align 16
IDirectDraw_QueryInterface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw_QueryInterface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw_AddRef_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDraw_AddRef_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDraw_Release_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDraw_Release_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDraw_Compact_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDraw_Compact_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDraw_CreateClipper_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectDraw_CreateClipper_c
        Call_Asm_Epilogue_0 4

align 16
IDirectDraw_CreatePalette_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectDraw_CreatePalette_c
        Call_Asm_Epilogue_0 5

align 16
IDirectDraw_CreateSurface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectDraw_CreateSurface_c
        Call_Asm_Epilogue_0 4

align 16
IDirectDraw_DuplicateSurface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw_DuplicateSurface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw_EnumDisplayModes_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectDraw_EnumDisplayModes_c
        Call_Asm_Epilogue_0 5

align 16
IDirectDraw_EnumSurfaces_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectDraw_EnumSurfaces_c
        Call_Asm_Epilogue_0 5

align 16
IDirectDraw_FlipToGDISurface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDraw_FlipToGDISurface_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDraw_GetCaps_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw_GetCaps_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw_GetDisplayMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw_GetDisplayMode_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw_GetFourCCCodes_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw_GetFourCCCodes_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw_GetGDISurface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw_GetGDISurface_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw_GetMonitorFrequency_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw_GetMonitorFrequency_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw_GetScanLine_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw_GetScanLine_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw_GetVerticalBlankStatus_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw_GetVerticalBlankStatus_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw_Initialize_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw_Initialize_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw_RestoreDisplayMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDraw_RestoreDisplayMode_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDraw_SetCooperativeLevel_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw_SetCooperativeLevel_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw_SetDisplayMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectDraw_SetDisplayMode_c
        Call_Asm_Epilogue_0 4

align 16
IDirectDraw_WaitForVerticalBlank_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw_WaitForVerticalBlank_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw2_QueryInterface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw2_QueryInterface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw2_AddRef_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDraw2_AddRef_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDraw2_Release_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDraw2_Release_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDraw2_Compact_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDraw2_Compact_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDraw2_CreateClipper_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectDraw2_CreateClipper_c
        Call_Asm_Epilogue_0 4

align 16
IDirectDraw2_CreatePalette_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectDraw2_CreatePalette_c
        Call_Asm_Epilogue_0 5

align 16
IDirectDraw2_CreateSurface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectDraw2_CreateSurface_c
        Call_Asm_Epilogue_0 4

align 16
IDirectDraw2_DuplicateSurface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw2_DuplicateSurface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw2_EnumDisplayModes_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectDraw2_EnumDisplayModes_c
        Call_Asm_Epilogue_0 5

align 16
IDirectDraw2_EnumSurfaces_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectDraw2_EnumSurfaces_c
        Call_Asm_Epilogue_0 5

align 16
IDirectDraw2_FlipToGDISurface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDraw2_FlipToGDISurface_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDraw2_GetCaps_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw2_GetCaps_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw2_GetDisplayMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw2_GetDisplayMode_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw2_GetFourCCCodes_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw2_GetFourCCCodes_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw2_GetGDISurface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw2_GetGDISurface_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw2_GetMonitorFrequency_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw2_GetMonitorFrequency_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw2_GetScanLine_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw2_GetScanLine_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw2_GetVerticalBlankStatus_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw2_GetVerticalBlankStatus_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw2_Initialize_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDraw2_Initialize_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDraw2_RestoreDisplayMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDraw2_RestoreDisplayMode_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDraw2_SetCooperativeLevel_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw2_SetCooperativeLevel_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw2_SetDisplayMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call IDirectDraw2_SetDisplayMode_c
        Call_Asm_Epilogue_0 6

align 16
IDirectDraw2_WaitForVerticalBlank_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDraw2_WaitForVerticalBlank_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDraw2_GetAvailableVidMem_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectDraw2_GetAvailableVidMem_c
        Call_Asm_Epilogue_0 4

align 16
IDirectDrawSurface_QueryInterface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawSurface_QueryInterface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawSurface_AddRef_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDrawSurface_AddRef_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDrawSurface_Release_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDrawSurface_Release_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDrawSurface_AddAttachedSurface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_AddAttachedSurface_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_AddOverlayDirtyRect_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_AddOverlayDirtyRect_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_Blt_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call IDirectDrawSurface_Blt_c
        Call_Asm_Epilogue_0 6

align 16
IDirectDrawSurface_BltBatch_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectDrawSurface_BltBatch_c
        Call_Asm_Epilogue_0 4

align 16
IDirectDrawSurface_BltFast_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call IDirectDrawSurface_BltFast_c
        Call_Asm_Epilogue_0 6

align 16
IDirectDrawSurface_DeleteAttachedSurface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawSurface_DeleteAttachedSurface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawSurface_EnumAttachedSurfaces_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawSurface_EnumAttachedSurfaces_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawSurface_EnumOverlayZOrders_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectDrawSurface_EnumOverlayZOrders_c
        Call_Asm_Epilogue_0 4

align 16
IDirectDrawSurface_Flip_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawSurface_Flip_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawSurface_GetAttachedSurface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawSurface_GetAttachedSurface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawSurface_GetBltStatus_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_GetBltStatus_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_GetCaps_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_GetCaps_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_GetClipper_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_GetClipper_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_GetColorKey_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawSurface_GetColorKey_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawSurface_GetDC_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_GetDC_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_GetFlipStatus_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_GetFlipStatus_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_GetOverlayPosition_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawSurface_GetOverlayPosition_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawSurface_GetPalette_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_GetPalette_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_GetPixelFormat_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_GetPixelFormat_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_GetSurfaceDesc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_GetSurfaceDesc_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_Initialize_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawSurface_Initialize_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawSurface_IsLost_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDrawSurface_IsLost_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDrawSurface_Lock_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectDrawSurface_Lock_c
        Call_Asm_Epilogue_0 5

align 16
IDirectDrawSurface_ReleaseDC_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_ReleaseDC_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_Restore_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDrawSurface_Restore_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDrawSurface_SetClipper_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_SetClipper_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_SetColorKey_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawSurface_SetColorKey_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawSurface_SetOverlayPosition_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawSurface_SetOverlayPosition_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawSurface_SetPalette_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_SetPalette_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_Unlock_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_Unlock_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_UpdateOverlay_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call IDirectDrawSurface_UpdateOverlay_c
        Call_Asm_Epilogue_0 6

align 16
IDirectDrawSurface_UpdateOverlayDisplay_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawSurface_UpdateOverlayDisplay_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawSurface_UpdateOverlayZOrder_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawSurface_UpdateOverlayZOrder_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawPalette_QueryInterface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawPalette_QueryInterface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawPalette_AddRef_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDrawPalette_AddRef_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDrawPalette_Release_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDrawPalette_Release_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDrawPalette_GetCaps_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawPalette_GetCaps_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawPalette_GetEntries_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectDrawPalette_GetEntries_c
        Call_Asm_Epilogue_0 5

align 16
IDirectDrawPalette_Initialize_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectDrawPalette_Initialize_c
        Call_Asm_Epilogue_0 4

align 16
IDirectDrawPalette_SetEntries_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call IDirectDrawPalette_SetEntries_c
        Call_Asm_Epilogue_0 5

align 16
IDirectDrawClipper_QueryInterface_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawClipper_QueryInterface_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawClipper_AddRef_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDrawClipper_AddRef_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDrawClipper_Release_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call IDirectDrawClipper_Release_c
        Call_Asm_Epilogue_0 1

align 16
IDirectDrawClipper_GetClipList_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call IDirectDrawClipper_GetClipList_c
        Call_Asm_Epilogue_0 4

align 16
IDirectDrawClipper_GetHWnd_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawClipper_GetHWnd_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawClipper_Initialize_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawClipper_Initialize_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawClipper_IsClipListChanged_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call IDirectDrawClipper_IsClipListChanged_c
        Call_Asm_Epilogue_0 2

align 16
IDirectDrawClipper_SetClipList_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawClipper_SetClipList_c
        Call_Asm_Epilogue_0 3

align 16
IDirectDrawClipper_SetHWnd_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call IDirectDrawClipper_SetHWnd_c
        Call_Asm_Epilogue_0 3


section .rodata progbits alloc noexec nowrite align=4

IDirectSoundVtbl_asm2c:
        dd IDirectSound_QueryInterface_asm2c
        dd IDirectSound_AddRef_asm2c
        dd IDirectSound_Release_asm2c
        dd IDirectSound_CreateSoundBuffer_asm2c
        dd IDirectSound_GetCaps_asm2c
        dd IDirectSound_DuplicateSoundBuffer_asm2c
        dd IDirectSound_SetCooperativeLevel_asm2c
        dd IDirectSound_Compact_asm2c
        dd IDirectSound_GetSpeakerConfig_asm2c
        dd IDirectSound_SetSpeakerConfig_asm2c
        dd IDirectSound_Initialize_asm2c

IDirectSoundBufferVtbl_asm2c:
        dd IDirectSoundBuffer_QueryInterface_asm2c
        dd IDirectSoundBuffer_AddRef_asm2c
        dd IDirectSoundBuffer_Release_asm2c
        dd IDirectSoundBuffer_GetCaps_asm2c
        dd IDirectSoundBuffer_GetCurrentPosition_asm2c
        dd IDirectSoundBuffer_GetFormat_asm2c
        dd IDirectSoundBuffer_GetVolume_asm2c
        dd IDirectSoundBuffer_GetPan_asm2c
        dd IDirectSoundBuffer_GetFrequency_asm2c
        dd IDirectSoundBuffer_GetStatus_asm2c
        dd IDirectSoundBuffer_Initialize_asm2c
        dd IDirectSoundBuffer_Lock_asm2c
        dd IDirectSoundBuffer_Play_asm2c
        dd IDirectSoundBuffer_SetCurrentPosition_asm2c
        dd IDirectSoundBuffer_SetFormat_asm2c
        dd IDirectSoundBuffer_SetVolume_asm2c
        dd IDirectSoundBuffer_SetPan_asm2c
        dd IDirectSoundBuffer_SetFrequency_asm2c
        dd IDirectSoundBuffer_Stop_asm2c
        dd IDirectSoundBuffer_Unlock_asm2c
        dd IDirectSoundBuffer_Restore_asm2c

IDirectSound3DListenerVtbl_asm2c:
        dd IDirectSound3DListener_QueryInterface_asm2c
        dd IDirectSound3DListener_AddRef_asm2c
        dd IDirectSound3DListener_Release_asm2c
        dd IDirectSound3DListener_GetAllParameters_asm2c
        dd IDirectSound3DListener_GetDistanceFactor_asm2c
        dd IDirectSound3DListener_GetDopplerFactor_asm2c
        dd IDirectSound3DListener_GetOrientation_asm2c
        dd IDirectSound3DListener_GetPosition_asm2c
        dd IDirectSound3DListener_GetRolloffFactor_asm2c
        dd IDirectSound3DListener_GetVelocity_asm2c
        dd IDirectSound3DListener_SetAllParameters_asm2c
        dd IDirectSound3DListener_SetDistanceFactor_asm2c
        dd IDirectSound3DListener_SetDopplerFactor_asm2c
        dd IDirectSound3DListener_SetOrientation_asm2c
        dd IDirectSound3DListener_SetPosition_asm2c
        dd IDirectSound3DListener_SetRolloffFactor_asm2c
        dd IDirectSound3DListener_SetVelocity_asm2c
        dd IDirectSound3DListener_CommitDeferredSettings_asm2c

IDirectSound3DBufferVtbl_asm2c:
        dd IDirectSound3DBuffer_QueryInterface_asm2c
        dd IDirectSound3DBuffer_AddRef_asm2c
        dd IDirectSound3DBuffer_Release_asm2c
        dd IDirectSound3DBuffer_GetAllParameters_asm2c
        dd IDirectSound3DBuffer_GetConeAngles_asm2c
        dd IDirectSound3DBuffer_GetConeOrientation_asm2c
        dd IDirectSound3DBuffer_GetConeOutsideVolume_asm2c
        dd IDirectSound3DBuffer_GetMaxDistance_asm2c
        dd IDirectSound3DBuffer_GetMinDistance_asm2c
        dd IDirectSound3DBuffer_GetMode_asm2c
        dd IDirectSound3DBuffer_GetPosition_asm2c
        dd IDirectSound3DBuffer_GetVelocity_asm2c
        dd IDirectSound3DBuffer_SetAllParameters_asm2c
        dd IDirectSound3DBuffer_SetConeAngles_asm2c
        dd IDirectSound3DBuffer_SetConeOrientation_asm2c
        dd IDirectSound3DBuffer_SetConeOutsideVolume_asm2c
        dd IDirectSound3DBuffer_SetMaxDistance_asm2c
        dd IDirectSound3DBuffer_SetMinDistance_asm2c
        dd IDirectSound3DBuffer_SetMode_asm2c
        dd IDirectSound3DBuffer_SetPosition_asm2c
        dd IDirectSound3DBuffer_SetVelocity_asm2c

IDirectDrawVtbl_asm2c:
        dd IDirectDraw_QueryInterface_asm2c
        dd IDirectDraw_AddRef_asm2c
        dd IDirectDraw_Release_asm2c
        dd IDirectDraw_Compact_asm2c
        dd IDirectDraw_CreateClipper_asm2c
        dd IDirectDraw_CreatePalette_asm2c
        dd IDirectDraw_CreateSurface_asm2c
        dd IDirectDraw_DuplicateSurface_asm2c
        dd IDirectDraw_EnumDisplayModes_asm2c
        dd IDirectDraw_EnumSurfaces_asm2c
        dd IDirectDraw_FlipToGDISurface_asm2c
        dd IDirectDraw_GetCaps_asm2c
        dd IDirectDraw_GetDisplayMode_asm2c
        dd IDirectDraw_GetFourCCCodes_asm2c
        dd IDirectDraw_GetGDISurface_asm2c
        dd IDirectDraw_GetMonitorFrequency_asm2c
        dd IDirectDraw_GetScanLine_asm2c
        dd IDirectDraw_GetVerticalBlankStatus_asm2c
        dd IDirectDraw_Initialize_asm2c
        dd IDirectDraw_RestoreDisplayMode_asm2c
        dd IDirectDraw_SetCooperativeLevel_asm2c
        dd IDirectDraw_SetDisplayMode_asm2c
        dd IDirectDraw_WaitForVerticalBlank_asm2c

IDirectDraw2Vtbl_asm2c:
        dd IDirectDraw2_QueryInterface_asm2c
        dd IDirectDraw2_AddRef_asm2c
        dd IDirectDraw2_Release_asm2c
        dd IDirectDraw2_Compact_asm2c
        dd IDirectDraw2_CreateClipper_asm2c
        dd IDirectDraw2_CreatePalette_asm2c
        dd IDirectDraw2_CreateSurface_asm2c
        dd IDirectDraw2_DuplicateSurface_asm2c
        dd IDirectDraw2_EnumDisplayModes_asm2c
        dd IDirectDraw2_EnumSurfaces_asm2c
        dd IDirectDraw2_FlipToGDISurface_asm2c
        dd IDirectDraw2_GetCaps_asm2c
        dd IDirectDraw2_GetDisplayMode_asm2c
        dd IDirectDraw2_GetFourCCCodes_asm2c
        dd IDirectDraw2_GetGDISurface_asm2c
        dd IDirectDraw2_GetMonitorFrequency_asm2c
        dd IDirectDraw2_GetScanLine_asm2c
        dd IDirectDraw2_GetVerticalBlankStatus_asm2c
        dd IDirectDraw2_Initialize_asm2c
        dd IDirectDraw2_RestoreDisplayMode_asm2c
        dd IDirectDraw2_SetCooperativeLevel_asm2c
        dd IDirectDraw2_SetDisplayMode_asm2c
        dd IDirectDraw2_WaitForVerticalBlank_asm2c
        dd IDirectDraw2_GetAvailableVidMem_asm2c

IDirectDrawSurfaceVtbl_asm2c:
        dd IDirectDrawSurface_QueryInterface_asm2c
        dd IDirectDrawSurface_AddRef_asm2c
        dd IDirectDrawSurface_Release_asm2c
        dd IDirectDrawSurface_AddAttachedSurface_asm2c
        dd IDirectDrawSurface_AddOverlayDirtyRect_asm2c
        dd IDirectDrawSurface_Blt_asm2c
        dd IDirectDrawSurface_BltBatch_asm2c
        dd IDirectDrawSurface_BltFast_asm2c
        dd IDirectDrawSurface_DeleteAttachedSurface_asm2c
        dd IDirectDrawSurface_EnumAttachedSurfaces_asm2c
        dd IDirectDrawSurface_EnumOverlayZOrders_asm2c
        dd IDirectDrawSurface_Flip_asm2c
        dd IDirectDrawSurface_GetAttachedSurface_asm2c
        dd IDirectDrawSurface_GetBltStatus_asm2c
        dd IDirectDrawSurface_GetCaps_asm2c
        dd IDirectDrawSurface_GetClipper_asm2c
        dd IDirectDrawSurface_GetColorKey_asm2c
        dd IDirectDrawSurface_GetDC_asm2c
        dd IDirectDrawSurface_GetFlipStatus_asm2c
        dd IDirectDrawSurface_GetOverlayPosition_asm2c
        dd IDirectDrawSurface_GetPalette_asm2c
        dd IDirectDrawSurface_GetPixelFormat_asm2c
        dd IDirectDrawSurface_GetSurfaceDesc_asm2c
        dd IDirectDrawSurface_Initialize_asm2c
        dd IDirectDrawSurface_IsLost_asm2c
        dd IDirectDrawSurface_Lock_asm2c
        dd IDirectDrawSurface_ReleaseDC_asm2c
        dd IDirectDrawSurface_Restore_asm2c
        dd IDirectDrawSurface_SetClipper_asm2c
        dd IDirectDrawSurface_SetColorKey_asm2c
        dd IDirectDrawSurface_SetOverlayPosition_asm2c
        dd IDirectDrawSurface_SetPalette_asm2c
        dd IDirectDrawSurface_Unlock_asm2c
        dd IDirectDrawSurface_UpdateOverlay_asm2c
        dd IDirectDrawSurface_UpdateOverlayDisplay_asm2c
        dd IDirectDrawSurface_UpdateOverlayZOrder_asm2c

IDirectDrawPaletteVtbl_asm2c:
        dd IDirectDrawPalette_QueryInterface_asm2c
        dd IDirectDrawPalette_AddRef_asm2c
        dd IDirectDrawPalette_Release_asm2c
        dd IDirectDrawPalette_GetCaps_asm2c
        dd IDirectDrawPalette_GetEntries_asm2c
        dd IDirectDrawPalette_Initialize_asm2c
        dd IDirectDrawPalette_SetEntries_asm2c

IDirectDrawClipperVtbl_asm2c:
        dd IDirectDrawClipper_QueryInterface_asm2c
        dd IDirectDrawClipper_AddRef_asm2c
        dd IDirectDrawClipper_Release_asm2c
        dd IDirectDrawClipper_GetClipList_asm2c
        dd IDirectDrawClipper_GetHWnd_asm2c
        dd IDirectDrawClipper_Initialize_asm2c
        dd IDirectDrawClipper_IsClipListChanged_asm2c
        dd IDirectDrawClipper_SetClipList_asm2c
        dd IDirectDrawClipper_SetHWnd_asm2c

