;; generated by gen_imports.py from imports.spec - do not edit

%include "x64inc.inc"
%include "asm-calls.inc"

extern operator_new_c
extern operator_delete_c
extern _access_c
extern _assert_c
extern _CIacos_c
extern _CIasin_c
extern _CIatan2_c
extern _CIfmod_c
extern _CIpow_c
extern _close_c
extern _errno_c
extern _findclose_c
extern _findfirst_c
extern _findnext_c
extern grAlphaBlendFunction_c
extern grAlphaCombine_c
extern grBufferClear_c
extern grBufferSwap_c
extern grChromakeyMode_c
extern grChromakeyValue_c
extern grColorCombine_c
extern grConstantColorValue_c
extern grCullMode_c
extern grDepthBufferFunction_c
extern grDepthBufferMode_c
extern grDepthMask_c
extern grDrawLine_c
extern grDrawPoint_c
extern grDrawTriangle_c
extern grFogColorValue_c
extern grFogMode_c
extern grGlideGetState_c
extern grGlideInit_c
extern grGlideSetState_c
extern grGlideShutdown_c
extern grLfbLock_c
extern grLfbUnlock_c
extern grRenderBuffer_c
extern grSstQueryBoards_c
extern grSstQueryHardware_c
extern grSstSelect_c
extern grSstWinClose_c
extern grSstWinOpen_c
extern grTexCalcMemRequired_c
extern grTexClampMode_c
extern grTexCombine_c
extern grTexDownloadMipMap_c
extern grTexDownloadTable_c
extern grTexFilterMode_c
extern grTexMaxAddress_c
extern grTexMinAddress_c
extern grTexMipMapMode_c
extern grTexSource_c
extern _isctype_c
extern _ismbcalnum_c
extern _ismbcpunct_c
extern _ismbcspace_c
extern _isnan_c
extern _itoa_c
extern _lseek_c
extern _mbsicmp_c
extern _mbsnbcat_c
extern _mbsnbcpy_c
extern _mbsnbicmp_c
extern _mkdir_c
extern _msize_c
extern _open_c
extern _putch_c
extern _read_c
extern _splitpath_c
extern _stat_c
extern _stricmp_c
extern _strlwr_c
extern _strnicmp_c
extern _unlink_c
extern _vsnprintf_c
extern abort_c
extern AddFontResourceA_c
extern AdjustWindowRect_c
extern atoi_c
extern atol_c
extern auxGetDevCapsA_c
extern auxGetNumDevs_c
extern auxSetVolume_c
extern BeginPaint_c
extern BitBlt_c
extern bsearch_c
extern calloc_c
extern ClientToScreen_c
extern ClipCursor_c
extern clock_c
extern CloseHandle_c
extern CoInitialize_c
extern CopyFileA_c
extern CoUninitialize_c
extern CreateCompatibleDC_c
extern CreateDIBSection_c
extern CreateFileA_c
extern CreateFileMappingA_c
extern CreateFontIndirectA_c
extern CreatePalette_c
extern CreateProcessA_c
extern CreateScalableFontResourceA_c
extern CreateThread_c
extern CreateWindowExA_c
extern DefWindowProcA_c
extern DeleteCriticalSection_c
extern DeleteDC_c
extern DeleteFileA_c
extern DeleteObject_c
extern DestroyWindow_c
extern DialogBoxParamA_c
extern difftime_c
extern DirectDrawCreate_c
extern DirectDrawEnumerateA_c
extern DirectSoundCreate_c
extern DispatchMessageA_c
extern msvcrt_div_c
extern dp_enableDebugPrint_c
extern dpAddPlayerToGroup_c
extern dpClose_c
extern dpCreate_c
extern dpCreateGroup_c
extern dpCreatePlayer_c
extern dpDestroy_c
extern dpDestroyPlayer_c
extern dpEnumGroupPlayers_c
extern dpEnumGroups_c
extern dpEnumPlayers_c
extern dpEnumSessions_c
extern dpFreeze_c
extern dpEnumTransports_c
extern dpGetPlayerData_c
extern dpGetPlayerName_c
extern dpGetSessionDesc_c
extern dpOpen_c
extern dpReceive_c
extern dpSend_c
extern dpSetGameServer_c
extern dpSetPlayerData_c
extern EndDialog_c
extern EndPaint_c
extern EnterCriticalSection_c
extern exit_c
extern ExitProcess_c
extern fclose_c
extern fflush_c
extern fgetc_c
extern fgets_c
extern FindClose_c
extern FindFirstFileA_c
extern FindNextFileA_c
extern FindWindowA_c
extern floor_c
extern FlushFileBuffers_c
extern fopen_c
extern fprintf_c
extern fputc_c
extern fputs_c
extern fread_c
extern free_c
extern FreeLibrary_c
extern fscanf_c
extern fseek_c
extern ftell_c
extern fwrite_c
extern GdiFlush_c
extern GetAsyncKeyState_c
extern getc_c
extern GetClientRect_c
extern GetCPInfo_c
extern GetCurrentDirectoryA_c
extern GetCurrentProcess_c
extern GetCurrentThreadId_c
extern GetCursorPos_c
extern GetDC_c
extern GetDeviceCaps_c
extern GetDlgItem_c
extern GetDlgItemTextA_c
extern GetDriveTypeA_c
extern GetFileTime_c
extern GetFileType_c
extern GetFocus_c
extern GetKeyboardType_c
extern GetKeyState_c
extern GetLastError_c
extern GetLocaleInfoA_c
extern GetLocaleInfoW_c
extern GetLogicalDrives_c
extern GetLogicalDriveStringsA_c
extern GetModuleFileNameA_c
extern GetModuleHandleA_c
extern GetProcAddress_c
extern GetProcessHeap_c
extern GetStdHandle_c
extern GetStockObject_c
extern GetStringTypeA_c
extern GetStringTypeW_c
extern GetSystemDefaultLCID_c
extern GetSystemInfo_c
extern GetSystemMetrics_c
extern GetSystemPaletteEntries_c
extern GetTextExtentExPointA_c
extern GetTextExtentPoint32A_c
extern GetTickCount_c
extern GetVolumeInformationA_c
extern GetWindowLongA_c
extern GetWindowRect_c
extern GetWindowsDirectoryA_c
extern HeapAlloc_c
extern HeapCompact_c
extern HeapCreate_c
extern HeapDestroy_c
extern HeapFree_c
extern HeapReAlloc_c
extern HeapSize_c
extern ImmAssociateContext_c
extern InitializeCriticalSection_c
extern InterlockedDecrement_c
extern InterlockedIncrement_c
extern isspace_c
extern joyGetDevCapsA_c
extern joyGetNumDevs_c
extern joyGetPos_c
extern joyGetPosEx_c
extern LCMapStringA_c
extern LCMapStringW_c
extern LeaveCriticalSection_c
extern LoadCursorA_c
extern LoadCursorFromFileA_c
extern LoadLibraryA_c
extern LoadModule_c
extern lstrcatA_c
extern lstrcpyA_c
extern malloc_c
extern MapViewOfFile_c
extern MapVirtualKeyA_c
extern mciGetErrorStringA_c
extern mciSendCommandA_c
extern memmove_c
extern MessageBoxA_c
extern MultiByteToWideChar_c
extern OutputDebugStringA_c
extern PeekMessageA_c
extern PostMessageA_c
extern PostQuitMessage_c
extern qsort_c
extern rand_c
extern ReadFile_c
extern RealizePalette_c
extern realloc_c
extern Rectangle_c
extern RegCloseKey_c
extern RegCreateKeyExA_c
extern RegisterClassA_c
extern RegOpenKeyExA_c
extern RegQueryValueExA_c
extern RegSetValueExA_c
extern ReleaseDC_c
extern RemoveFontResourceA_c
extern ScreenToClient_c
extern SelectObject_c
extern SelectPalette_c
extern SendDlgItemMessageA_c
extern SendMessageA_c
extern SetBkColor_c
extern SetBkMode_c
extern SetCursor_c
extern SetCursorPos_c
extern SetDIBColorTable_c
extern SetDIBitsToDevice_c
extern SetDlgItemTextA_c
extern SetEndOfFile_c
extern SetFileAttributesA_c
extern SetFilePointer_c
extern SetFocus_c
extern SetLastError_c
extern setlocale_c
extern SetMapperFlags_c
extern SetMenu_c
extern SetPaletteEntries_c
extern SetPriorityClass_c
extern SetRect_c
extern SetStdHandle_c
extern SetSystemPaletteUse_c
extern SetTextColor_c
extern setvbuf_c
extern SetWindowLongA_c
extern SetWindowPos_c
extern ShowCursor_c
extern ShowWindow_c
extern Sleep_c
extern SmackBufferBlit_c
extern SmackBufferClose_c
extern SmackBufferNewPalette_c
extern SmackBufferOpen_c
extern SmackBufferSetPalette_c
extern SmackClose_c
extern SmackColorRemap_c
extern SmackDoFrame_c
extern SmackNextFrame_c
extern SmackOpen_c
extern SmackSoundOnOff_c
extern SmackSoundUseDirectSound_c
extern SmackToBuffer_c
extern SmackToBufferRect_c
extern SmackWait_c
extern sprintf_c
extern srand_c
extern sscanf_c
extern strchr_c
extern StretchBlt_c
extern strncmp_c
extern strncpy_c
extern strpbrk_c
extern strrchr_c
extern strstr_c
extern strtok_c
extern TerminateProcess_c
extern TextOutA_c
extern time_c
extern timeGetTime_c
extern TlsGetValue_c
extern TlsSetValue_c
extern ToAscii_c
extern tolower_c
extern toupper_c
extern TranslateMessage_c
extern UnmapViewOfFile_c
extern UpdateWindow_c
extern ValidateRect_c
extern VirtualAlloc_c
extern VirtualFree_c
extern VirtualQuery_c
extern WaitForSingleObject_c
extern WideCharToMultiByte_c
extern WriteFile_c
extern wsprintfA_c
extern wvsprintfA_c
extern strspn_c
extern strcspn_c
extern strncat_c
extern vsprintf_c
extern memcpy_c
extern printf_c
extern ungetc_c
extern _filbuf_c
extern i76_frame_tick_c
extern i76shell_part_strncmp_c

global operator_new_asm2c
global operator_delete_asm2c
global _access_asm2c
global _assert_asm2c
global _CIacos_asm2c
global _CIasin_asm2c
global _CIatan2_asm2c
global _CIfmod_asm2c
global _CIpow_asm2c
global _close_asm2c
global _errno_asm2c
global _findclose_asm2c
global _findfirst_asm2c
global _findnext_asm2c
global grAlphaBlendFunction_asm2c
global grAlphaCombine_asm2c
global grBufferClear_asm2c
global grBufferSwap_asm2c
global grChromakeyMode_asm2c
global grChromakeyValue_asm2c
global grColorCombine_asm2c
global grConstantColorValue_asm2c
global grCullMode_asm2c
global grDepthBufferFunction_asm2c
global grDepthBufferMode_asm2c
global grDepthMask_asm2c
global grDrawLine_asm2c
global grDrawPoint_asm2c
global grDrawTriangle_asm2c
global grFogColorValue_asm2c
global grFogMode_asm2c
global grGlideGetState_asm2c
global grGlideInit_asm2c
global grGlideSetState_asm2c
global grGlideShutdown_asm2c
global grLfbLock_asm2c
global grLfbUnlock_asm2c
global grRenderBuffer_asm2c
global grSstQueryBoards_asm2c
global grSstQueryHardware_asm2c
global grSstSelect_asm2c
global grSstWinClose_asm2c
global grSstWinOpen_asm2c
global grTexCalcMemRequired_asm2c
global grTexClampMode_asm2c
global grTexCombine_asm2c
global grTexDownloadMipMap_asm2c
global grTexDownloadTable_asm2c
global grTexFilterMode_asm2c
global grTexMaxAddress_asm2c
global grTexMinAddress_asm2c
global grTexMipMapMode_asm2c
global grTexSource_asm2c
global _isctype_asm2c
global _ismbcalnum_asm2c
global _ismbcpunct_asm2c
global _ismbcspace_asm2c
global _isnan_asm2c
global _itoa_asm2c
global _lseek_asm2c
global _mbsicmp_asm2c
global _mbsnbcat_asm2c
global _mbsnbcpy_asm2c
global _mbsnbicmp_asm2c
global _mkdir_asm2c
global _msize_asm2c
global _open_asm2c
global _putch_asm2c
global _read_asm2c
global _splitpath_asm2c
global _stat_asm2c
global _stricmp_asm2c
global _strlwr_asm2c
global _strnicmp_asm2c
global _unlink_asm2c
global _vsnprintf_asm2c
global abort_asm2c
global AddFontResourceA_asm2c
global AdjustWindowRect_asm2c
global atoi_asm2c
global atol_asm2c
global auxGetDevCapsA_asm2c
global auxGetNumDevs_asm2c
global auxSetVolume_asm2c
global BeginPaint_asm2c
global BitBlt_asm2c
global bsearch_asm2c
global calloc_asm2c
global ClientToScreen_asm2c
global ClipCursor_asm2c
global clock_asm2c
global CloseHandle_asm2c
global CoInitialize_asm2c
global CopyFileA_asm2c
global CoUninitialize_asm2c
global CreateCompatibleDC_asm2c
global CreateDIBSection_asm2c
global CreateFileA_asm2c
global CreateFileMappingA_asm2c
global CreateFontIndirectA_asm2c
global CreatePalette_asm2c
global CreateProcessA_asm2c
global CreateScalableFontResourceA_asm2c
global CreateThread_asm2c
global CreateWindowExA_asm2c
global DefWindowProcA_asm2c
global DeleteCriticalSection_asm2c
global DeleteDC_asm2c
global DeleteFileA_asm2c
global DeleteObject_asm2c
global DestroyWindow_asm2c
global DialogBoxParamA_asm2c
global difftime_asm2c
global DirectDrawCreate_asm2c
global DirectDrawEnumerateA_asm2c
global DirectSoundCreate_asm2c
global DispatchMessageA_asm2c
global msvcrt_div_asm2c
global dp_enableDebugPrint_asm2c
global dpAddPlayerToGroup_asm2c
global dpClose_asm2c
global dpCreate_asm2c
global dpCreateGroup_asm2c
global dpCreatePlayer_asm2c
global dpDestroy_asm2c
global dpDestroyPlayer_asm2c
global dpEnumGroupPlayers_asm2c
global dpEnumGroups_asm2c
global dpEnumPlayers_asm2c
global dpEnumSessions_asm2c
global dpFreeze_asm2c
global dpEnumTransports_asm2c
global dpGetPlayerData_asm2c
global dpGetPlayerName_asm2c
global dpGetSessionDesc_asm2c
global dpOpen_asm2c
global dpReceive_asm2c
global dpSend_asm2c
global dpSetGameServer_asm2c
global dpSetPlayerData_asm2c
global EndDialog_asm2c
global EndPaint_asm2c
global EnterCriticalSection_asm2c
global exit_asm2c
global ExitProcess_asm2c
global fclose_asm2c
global fflush_asm2c
global fgetc_asm2c
global fgets_asm2c
global FindClose_asm2c
global FindFirstFileA_asm2c
global FindNextFileA_asm2c
global FindWindowA_asm2c
global floor_asm2c
global FlushFileBuffers_asm2c
global fopen_asm2c
global fprintf_asm2c
global fputc_asm2c
global fputs_asm2c
global fread_asm2c
global free_asm2c
global FreeLibrary_asm2c
global fscanf_asm2c
global fseek_asm2c
global ftell_asm2c
global fwrite_asm2c
global GdiFlush_asm2c
global GetAsyncKeyState_asm2c
global getc_asm2c
global GetClientRect_asm2c
global GetCPInfo_asm2c
global GetCurrentDirectoryA_asm2c
global GetCurrentProcess_asm2c
global GetCurrentThreadId_asm2c
global GetCursorPos_asm2c
global GetDC_asm2c
global GetDeviceCaps_asm2c
global GetDlgItem_asm2c
global GetDlgItemTextA_asm2c
global GetDriveTypeA_asm2c
global GetFileTime_asm2c
global GetFileType_asm2c
global GetFocus_asm2c
global GetKeyboardType_asm2c
global GetKeyState_asm2c
global GetLastError_asm2c
global GetLocaleInfoA_asm2c
global GetLocaleInfoW_asm2c
global GetLogicalDrives_asm2c
global GetLogicalDriveStringsA_asm2c
global GetModuleFileNameA_asm2c
global GetModuleHandleA_asm2c
global GetProcAddress_asm2c
global GetProcessHeap_asm2c
global GetStdHandle_asm2c
global GetStockObject_asm2c
global GetStringTypeA_asm2c
global GetStringTypeW_asm2c
global GetSystemDefaultLCID_asm2c
global GetSystemInfo_asm2c
global GetSystemMetrics_asm2c
global GetSystemPaletteEntries_asm2c
global GetTextExtentExPointA_asm2c
global GetTextExtentPoint32A_asm2c
global GetTickCount_asm2c
global GetVolumeInformationA_asm2c
global GetWindowLongA_asm2c
global GetWindowRect_asm2c
global GetWindowsDirectoryA_asm2c
global HeapAlloc_asm2c
global HeapCompact_asm2c
global HeapCreate_asm2c
global HeapDestroy_asm2c
global HeapFree_asm2c
global HeapReAlloc_asm2c
global HeapSize_asm2c
global ImmAssociateContext_asm2c
global InitializeCriticalSection_asm2c
global InterlockedDecrement_asm2c
global InterlockedIncrement_asm2c
global isspace_asm2c
global joyGetDevCapsA_asm2c
global joyGetNumDevs_asm2c
global joyGetPos_asm2c
global joyGetPosEx_asm2c
global LCMapStringA_asm2c
global LCMapStringW_asm2c
global LeaveCriticalSection_asm2c
global LoadCursorA_asm2c
global LoadCursorFromFileA_asm2c
global LoadLibraryA_asm2c
global LoadModule_asm2c
global lstrcatA_asm2c
global lstrcpyA_asm2c
global malloc_asm2c
global MapViewOfFile_asm2c
global MapVirtualKeyA_asm2c
global mciGetErrorStringA_asm2c
global mciSendCommandA_asm2c
global memmove_asm2c
global MessageBoxA_asm2c
global MultiByteToWideChar_asm2c
global OutputDebugStringA_asm2c
global PeekMessageA_asm2c
global PostMessageA_asm2c
global PostQuitMessage_asm2c
global qsort_asm2c
global rand_asm2c
global ReadFile_asm2c
global RealizePalette_asm2c
global realloc_asm2c
global Rectangle_asm2c
global RegCloseKey_asm2c
global RegCreateKeyExA_asm2c
global RegisterClassA_asm2c
global RegOpenKeyExA_asm2c
global RegQueryValueExA_asm2c
global RegSetValueExA_asm2c
global ReleaseDC_asm2c
global RemoveFontResourceA_asm2c
global ScreenToClient_asm2c
global SelectObject_asm2c
global SelectPalette_asm2c
global SendDlgItemMessageA_asm2c
global SendMessageA_asm2c
global SetBkColor_asm2c
global SetBkMode_asm2c
global SetCursor_asm2c
global SetCursorPos_asm2c
global SetDIBColorTable_asm2c
global SetDIBitsToDevice_asm2c
global SetDlgItemTextA_asm2c
global SetEndOfFile_asm2c
global SetFileAttributesA_asm2c
global SetFilePointer_asm2c
global SetFocus_asm2c
global SetLastError_asm2c
global setlocale_asm2c
global SetMapperFlags_asm2c
global SetMenu_asm2c
global SetPaletteEntries_asm2c
global SetPriorityClass_asm2c
global SetRect_asm2c
global SetStdHandle_asm2c
global SetSystemPaletteUse_asm2c
global SetTextColor_asm2c
global setvbuf_asm2c
global SetWindowLongA_asm2c
global SetWindowPos_asm2c
global ShowCursor_asm2c
global ShowWindow_asm2c
global Sleep_asm2c
global SmackBufferBlit_asm2c
global SmackBufferClose_asm2c
global SmackBufferNewPalette_asm2c
global SmackBufferOpen_asm2c
global SmackBufferSetPalette_asm2c
global SmackClose_asm2c
global SmackColorRemap_asm2c
global SmackDoFrame_asm2c
global SmackNextFrame_asm2c
global SmackOpen_asm2c
global SmackSoundOnOff_asm2c
global SmackSoundUseDirectSound_asm2c
global SmackToBuffer_asm2c
global SmackToBufferRect_asm2c
global SmackWait_asm2c
global sprintf_asm2c
global srand_asm2c
global sscanf_asm2c
global strchr_asm2c
global StretchBlt_asm2c
global strncmp_asm2c
global strncpy_asm2c
global strpbrk_asm2c
global strrchr_asm2c
global strstr_asm2c
global strtok_asm2c
global TerminateProcess_asm2c
global TextOutA_asm2c
global time_asm2c
global timeGetTime_asm2c
global TlsGetValue_asm2c
global TlsSetValue_asm2c
global ToAscii_asm2c
global tolower_asm2c
global toupper_asm2c
global TranslateMessage_asm2c
global UnmapViewOfFile_asm2c
global UpdateWindow_asm2c
global ValidateRect_asm2c
global VirtualAlloc_asm2c
global VirtualFree_asm2c
global VirtualQuery_asm2c
global WaitForSingleObject_asm2c
global WideCharToMultiByte_asm2c
global WriteFile_asm2c
global wsprintfA_asm2c
global wvsprintfA_asm2c
global strspn_asm2c
global strcspn_asm2c
global strncat_asm2c
global vsprintf_asm2c
global memcpy_asm2c
global printf_asm2c
global ungetc_asm2c
global _filbuf_asm2c
global i76_frame_tick_asm2c
global i76shell_part_strncmp_asm2c

%ifidn __OUTPUT_FORMAT__, elf64
section .note.GNU-stack noalloc noexec nowrite progbits
section .text progbits alloc exec nowrite align=16
%else
%error "only elf64 (SysV) is supported"
%endif

; ??2@YAPAXI@Z (c1, MSVCRT.dll)
align 16
operator_new_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call operator_new_c
        Call_Asm_Epilogue_0 0

; ??3@YAXPAX@Z (c1, MSVCRT.dll)
align 16
operator_delete_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call operator_delete_c
        Call_Asm_Epilogue_0 0

; _access (c2, MSVCRT.dll)
align 16
_access_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call _access_c
        Call_Asm_Epilogue_0 0

; _assert (c3, MSVCRT.dll)
align 16
_assert_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call _assert_c
        Call_Asm_Epilogue_0 0

; _CIacos (f1f, MSVCRT.dll)
align 16
_CIacos_asm2c:
        Call_Asm_Float1_Float _CIacos_c

; _CIasin (f1f, MSVCRT.dll)
align 16
_CIasin_asm2c:
        Call_Asm_Float1_Float _CIasin_c

; _CIatan2 (f2f, MSVCRT.dll)
align 16
_CIatan2_asm2c:
        Call_Asm_Float2_Float _CIatan2_c

; _CIfmod (f2f, MSVCRT.dll)
align 16
_CIfmod_asm2c:
        Call_Asm_Float2_Float _CIfmod_c

; _CIpow (f2f, MSVCRT.dll)
align 16
_CIpow_asm2c:
        Call_Asm_Float2_Float _CIpow_c

; _close (c1, MSVCRT.dll)
align 16
_close_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call _close_c
        Call_Asm_Epilogue_0 0

; _errno (c0, MSVCRT.dll)
align 16
_errno_asm2c:
        Call_Asm_Prologue_0
        call _errno_c
        Call_Asm_Epilogue_0 0

; _findclose (c1, MSVCRT.dll)
align 16
_findclose_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call _findclose_c
        Call_Asm_Epilogue_0 0

; _findfirst (c2, MSVCRT.dll)
align 16
_findfirst_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call _findfirst_c
        Call_Asm_Epilogue_0 0

; _findnext (c2, MSVCRT.dll)
align 16
_findnext_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call _findnext_c
        Call_Asm_Epilogue_0 0

; _grAlphaBlendFunction@16 (std4, glide2x.dll)
align 16
grAlphaBlendFunction_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call grAlphaBlendFunction_c
        Call_Asm_Epilogue_0 4

; _grAlphaCombine@20 (std5, glide2x.dll)
align 16
grAlphaCombine_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call grAlphaCombine_c
        Call_Asm_Epilogue_0 5

; _grBufferClear@12 (std3, glide2x.dll)
align 16
grBufferClear_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call grBufferClear_c
        Call_Asm_Epilogue_0 3

; _grBufferSwap@4 (std1, glide2x.dll)
align 16
grBufferSwap_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grBufferSwap_c
        Call_Asm_Epilogue_0 1

; _grChromakeyMode@4 (std1, glide2x.dll)
align 16
grChromakeyMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grChromakeyMode_c
        Call_Asm_Epilogue_0 1

; _grChromakeyValue@4 (std1, glide2x.dll)
align 16
grChromakeyValue_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grChromakeyValue_c
        Call_Asm_Epilogue_0 1

; _grColorCombine@20 (std5, glide2x.dll)
align 16
grColorCombine_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call grColorCombine_c
        Call_Asm_Epilogue_0 5

; _grConstantColorValue@4 (std1, glide2x.dll)
align 16
grConstantColorValue_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grConstantColorValue_c
        Call_Asm_Epilogue_0 1

; _grCullMode@4 (std1, glide2x.dll)
align 16
grCullMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grCullMode_c
        Call_Asm_Epilogue_0 1

; _grDepthBufferFunction@4 (std1, glide2x.dll)
align 16
grDepthBufferFunction_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grDepthBufferFunction_c
        Call_Asm_Epilogue_0 1

; _grDepthBufferMode@4 (std1, glide2x.dll)
align 16
grDepthBufferMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grDepthBufferMode_c
        Call_Asm_Epilogue_0 1

; _grDepthMask@4 (std1, glide2x.dll)
align 16
grDepthMask_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grDepthMask_c
        Call_Asm_Epilogue_0 1

; _grDrawLine@8 (std2, glide2x.dll)
align 16
grDrawLine_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call grDrawLine_c
        Call_Asm_Epilogue_0 2

; _grDrawPoint@4 (std1, glide2x.dll)
align 16
grDrawPoint_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grDrawPoint_c
        Call_Asm_Epilogue_0 1

; _grDrawTriangle@12 (std3, glide2x.dll)
align 16
grDrawTriangle_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call grDrawTriangle_c
        Call_Asm_Epilogue_0 3

; _grFogColorValue@4 (std1, glide2x.dll)
align 16
grFogColorValue_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grFogColorValue_c
        Call_Asm_Epilogue_0 1

; _grFogMode@4 (std1, glide2x.dll)
align 16
grFogMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grFogMode_c
        Call_Asm_Epilogue_0 1

; _grGlideGetState@4 (std1, glide2x.dll)
align 16
grGlideGetState_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grGlideGetState_c
        Call_Asm_Epilogue_0 1

; _grGlideInit@0 (std0, glide2x.dll)
align 16
grGlideInit_asm2c:
        Call_Asm_Prologue_0
        call grGlideInit_c
        Call_Asm_Epilogue_0 0

; _grGlideSetState@4 (std1, glide2x.dll)
align 16
grGlideSetState_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grGlideSetState_c
        Call_Asm_Epilogue_0 1

; _grGlideShutdown@0 (std0, glide2x.dll)
align 16
grGlideShutdown_asm2c:
        Call_Asm_Prologue_0
        call grGlideShutdown_c
        Call_Asm_Epilogue_0 0

; _grLfbLock@24 (std6, glide2x.dll)
align 16
grLfbLock_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call grLfbLock_c
        Call_Asm_Epilogue_0 6

; _grLfbUnlock@8 (std2, glide2x.dll)
align 16
grLfbUnlock_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call grLfbUnlock_c
        Call_Asm_Epilogue_0 2

; _grRenderBuffer@4 (std1, glide2x.dll)
align 16
grRenderBuffer_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grRenderBuffer_c
        Call_Asm_Epilogue_0 1

; _grSstQueryBoards@4 (std1, glide2x.dll)
align 16
grSstQueryBoards_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grSstQueryBoards_c
        Call_Asm_Epilogue_0 1

; _grSstQueryHardware@4 (std1, glide2x.dll)
align 16
grSstQueryHardware_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grSstQueryHardware_c
        Call_Asm_Epilogue_0 1

; _grSstSelect@4 (std1, glide2x.dll)
align 16
grSstSelect_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grSstSelect_c
        Call_Asm_Epilogue_0 1

; _grSstWinClose@0 (std0, glide2x.dll)
align 16
grSstWinClose_asm2c:
        Call_Asm_Prologue_0
        call grSstWinClose_c
        Call_Asm_Epilogue_0 0

; _grSstWinOpen@28 (std7, glide2x.dll)
align 16
grSstWinOpen_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 16
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call grSstWinOpen_c
        add rsp, 16
        Call_Asm_Epilogue_0 7

; _grTexCalcMemRequired@16 (std4, glide2x.dll)
align 16
grTexCalcMemRequired_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call grTexCalcMemRequired_c
        Call_Asm_Epilogue_0 4

; _grTexClampMode@12 (std3, glide2x.dll)
align 16
grTexClampMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call grTexClampMode_c
        Call_Asm_Epilogue_0 3

; _grTexCombine@28 (std7, glide2x.dll)
align 16
grTexCombine_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 16
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call grTexCombine_c
        add rsp, 16
        Call_Asm_Epilogue_0 7

; _grTexDownloadMipMap@16 (std4, glide2x.dll)
align 16
grTexDownloadMipMap_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call grTexDownloadMipMap_c
        Call_Asm_Epilogue_0 4

; _grTexDownloadTable@12 (std3, glide2x.dll)
align 16
grTexDownloadTable_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call grTexDownloadTable_c
        Call_Asm_Epilogue_0 3

; _grTexFilterMode@12 (std3, glide2x.dll)
align 16
grTexFilterMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call grTexFilterMode_c
        Call_Asm_Epilogue_0 3

; _grTexMaxAddress@4 (std1, glide2x.dll)
align 16
grTexMaxAddress_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grTexMaxAddress_c
        Call_Asm_Epilogue_0 1

; _grTexMinAddress@4 (std1, glide2x.dll)
align 16
grTexMinAddress_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call grTexMinAddress_c
        Call_Asm_Epilogue_0 1

; _grTexMipMapMode@12 (std3, glide2x.dll)
align 16
grTexMipMapMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call grTexMipMapMode_c
        Call_Asm_Epilogue_0 3

; _grTexSource@16 (std4, glide2x.dll)
align 16
grTexSource_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call grTexSource_c
        Call_Asm_Epilogue_0 4

; _isctype (c2, MSVCRT.dll)
align 16
_isctype_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call _isctype_c
        Call_Asm_Epilogue_0 0

; _ismbcalnum (c1, MSVCRT.dll)
align 16
_ismbcalnum_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call _ismbcalnum_c
        Call_Asm_Epilogue_0 0

; _ismbcpunct (c1, MSVCRT.dll)
align 16
_ismbcpunct_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call _ismbcpunct_c
        Call_Asm_Epilogue_0 0

; _ismbcspace (c1, MSVCRT.dll)
align 16
_ismbcspace_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call _ismbcspace_c
        Call_Asm_Epilogue_0 0

; _isnan (c2, MSVCRT.dll)
align 16
_isnan_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call _isnan_c
        Call_Asm_Epilogue_0 0

; _itoa (c3, MSVCRT.dll)
align 16
_itoa_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call _itoa_c
        Call_Asm_Epilogue_0 0

; _lseek (c3, MSVCRT.dll)
align 16
_lseek_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call _lseek_c
        Call_Asm_Epilogue_0 0

; _mbsicmp (c2, MSVCRT.dll)
align 16
_mbsicmp_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call _mbsicmp_c
        Call_Asm_Epilogue_0 0

; _mbsnbcat (c3, MSVCRT.dll)
align 16
_mbsnbcat_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call _mbsnbcat_c
        Call_Asm_Epilogue_0 0

; _mbsnbcpy (c3, MSVCRT.dll)
align 16
_mbsnbcpy_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call _mbsnbcpy_c
        Call_Asm_Epilogue_0 0

; _mbsnbicmp (c3, MSVCRT.dll)
align 16
_mbsnbicmp_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call _mbsnbicmp_c
        Call_Asm_Epilogue_0 0

; _mkdir (c1, MSVCRT.dll)
align 16
_mkdir_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call _mkdir_c
        Call_Asm_Epilogue_0 0

; _msize (c1, MSVCRT.dll)
align 16
_msize_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call _msize_c
        Call_Asm_Epilogue_0 0

; _open (v2, MSVCRT.dll)
align 16
_open_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        lea edx, [r11d+20]
        call _open_c
        Call_Asm_Epilogue_0 0

; _putch (c1, MSVCRT.dll)
align 16
_putch_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call _putch_c
        Call_Asm_Epilogue_0 0

; _read (c3, MSVCRT.dll)
align 16
_read_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call _read_c
        Call_Asm_Epilogue_0 0

; _splitpath (c5, MSVCRT.dll)
align 16
_splitpath_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call _splitpath_c
        Call_Asm_Epilogue_0 0

; _stat (c2, MSVCRT.dll)
align 16
_stat_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call _stat_c
        Call_Asm_Epilogue_0 0

; _stricmp (c2, MSVCRT.dll)
align 16
_stricmp_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call _stricmp_c
        Call_Asm_Epilogue_0 0

; _strlwr (c1, MSVCRT.dll)
align 16
_strlwr_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call _strlwr_c
        Call_Asm_Epilogue_0 0

; _strnicmp (c3, MSVCRT.dll)
align 16
_strnicmp_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call _strnicmp_c
        Call_Asm_Epilogue_0 0

; _unlink (c1, MSVCRT.dll)
align 16
_unlink_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call _unlink_c
        Call_Asm_Epilogue_0 0

; _vsnprintf (c4, MSVCRT.dll)
align 16
_vsnprintf_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call _vsnprintf_c
        Call_Asm_Epilogue_0 0

; abort (c0, MSVCRT.dll)
align 16
abort_asm2c:
        Call_Asm_Prologue_0
        call abort_c
        Call_Asm_Epilogue_0 0

; AddFontResourceA (std1, GDI32.dll)
align 16
AddFontResourceA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call AddFontResourceA_c
        Call_Asm_Epilogue_0 1

; AdjustWindowRect (std3, USER32.dll)
align 16
AdjustWindowRect_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call AdjustWindowRect_c
        Call_Asm_Epilogue_0 3

; atoi (c1, MSVCRT.dll)
align 16
atoi_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call atoi_c
        Call_Asm_Epilogue_0 0

; atol (c1, MSVCRT.dll)
align 16
atol_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call atol_c
        Call_Asm_Epilogue_0 0

; auxGetDevCapsA (std3, WIN32.dll)
align 16
auxGetDevCapsA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call auxGetDevCapsA_c
        Call_Asm_Epilogue_0 3

; auxGetNumDevs (std0, WIN32.dll)
align 16
auxGetNumDevs_asm2c:
        Call_Asm_Prologue_0
        call auxGetNumDevs_c
        Call_Asm_Epilogue_0 0

; auxSetVolume (std2, WIN32.dll)
align 16
auxSetVolume_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call auxSetVolume_c
        Call_Asm_Epilogue_0 2

; BeginPaint (std2, USER32.dll)
align 16
BeginPaint_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call BeginPaint_c
        Call_Asm_Epilogue_0 2

; BitBlt (std9, GDI32.dll)
align 16
BitBlt_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 32
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov eax, [r11d+40]
        mov [rsp+8], rax
        mov eax, [r11d+44]
        mov [rsp+16], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call BitBlt_c
        add rsp, 32
        Call_Asm_Epilogue_0 9

; bsearch (c5, MSVCRT.dll)
align 16
bsearch_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call bsearch_c
        Call_Asm_Epilogue_0 0

; calloc (c2, MSVCRT.dll)
align 16
calloc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call calloc_c
        Call_Asm_Epilogue_0 0

; ClientToScreen (std2, USER32.dll)
align 16
ClientToScreen_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call ClientToScreen_c
        Call_Asm_Epilogue_0 2

; ClipCursor (std1, USER32.dll)
align 16
ClipCursor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call ClipCursor_c
        Call_Asm_Epilogue_0 1

; clock (c0, MSVCRT.dll)
align 16
clock_asm2c:
        Call_Asm_Prologue_0
        call clock_c
        Call_Asm_Epilogue_0 0

; CloseHandle (std1, KERNEL32.dll)
align 16
CloseHandle_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call CloseHandle_c
        Call_Asm_Epilogue_0 1

; CoInitialize (std1, ole32.dll)
align 16
CoInitialize_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call CoInitialize_c
        Call_Asm_Epilogue_0 1

; CopyFileA (std3, KERNEL32.dll)
align 16
CopyFileA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call CopyFileA_c
        Call_Asm_Epilogue_0 3

; CoUninitialize (std0, ole32.dll)
align 16
CoUninitialize_asm2c:
        Call_Asm_Prologue_0
        call CoUninitialize_c
        Call_Asm_Epilogue_0 0

; CreateCompatibleDC (std1, GDI32.dll)
align 16
CreateCompatibleDC_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call CreateCompatibleDC_c
        Call_Asm_Epilogue_0 1

; CreateDIBSection (std6, GDI32.dll)
align 16
CreateDIBSection_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call CreateDIBSection_c
        Call_Asm_Epilogue_0 6

; CreateFileA (std7, KERNEL32.dll)
align 16
CreateFileA_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 16
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call CreateFileA_c
        add rsp, 16
        Call_Asm_Epilogue_0 7

; CreateFileMappingA (std6, KERNEL32.dll)
align 16
CreateFileMappingA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call CreateFileMappingA_c
        Call_Asm_Epilogue_0 6

; CreateFontIndirectA (std1, GDI32.dll)
align 16
CreateFontIndirectA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call CreateFontIndirectA_c
        Call_Asm_Epilogue_0 1

; CreatePalette (std1, GDI32.dll)
align 16
CreatePalette_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call CreatePalette_c
        Call_Asm_Epilogue_0 1

; CreateProcessA (std10, KERNEL32.dll)
align 16
CreateProcessA_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 32
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov eax, [r11d+40]
        mov [rsp+8], rax
        mov eax, [r11d+44]
        mov [rsp+16], rax
        mov eax, [r11d+48]
        mov [rsp+24], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call CreateProcessA_c
        add rsp, 32
        Call_Asm_Epilogue_0 10

; CreateScalableFontResourceA (std4, GDI32.dll)
align 16
CreateScalableFontResourceA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call CreateScalableFontResourceA_c
        Call_Asm_Epilogue_0 4

; CreateThread (std6, KERNEL32.dll)
align 16
CreateThread_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call CreateThread_c
        Call_Asm_Epilogue_0 6

; CreateWindowExA (std12, USER32.dll)
align 16
CreateWindowExA_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 48
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov eax, [r11d+40]
        mov [rsp+8], rax
        mov eax, [r11d+44]
        mov [rsp+16], rax
        mov eax, [r11d+48]
        mov [rsp+24], rax
        mov eax, [r11d+52]
        mov [rsp+32], rax
        mov eax, [r11d+56]
        mov [rsp+40], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call CreateWindowExA_c
        add rsp, 48
        Call_Asm_Epilogue_0 12

; DefWindowProcA (std4, USER32.dll)
align 16
DefWindowProcA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call DefWindowProcA_c
        Call_Asm_Epilogue_0 4

; DeleteCriticalSection (std1, KERNEL32.dll)
align 16
DeleteCriticalSection_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call DeleteCriticalSection_c
        Call_Asm_Epilogue_0 1

; DeleteDC (std1, GDI32.dll)
align 16
DeleteDC_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call DeleteDC_c
        Call_Asm_Epilogue_0 1

; DeleteFileA (std1, KERNEL32.dll)
align 16
DeleteFileA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call DeleteFileA_c
        Call_Asm_Epilogue_0 1

; DeleteObject (std1, GDI32.dll)
align 16
DeleteObject_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call DeleteObject_c
        Call_Asm_Epilogue_0 1

; DestroyWindow (std1, USER32.dll)
align 16
DestroyWindow_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call DestroyWindow_c
        Call_Asm_Epilogue_0 1

; DialogBoxParamA (std5, USER32.dll)
align 16
DialogBoxParamA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call DialogBoxParamA_c
        Call_Asm_Epilogue_0 5

; difftime (c2, MSVCRT.dll)
align 16
difftime_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call difftime_c
        movsd [rsp-8], xmm0
        fld qword [rsp-8]
        Call_Asm_Epilogue_0 0

; DirectDrawCreate (std3, DDRAW.dll)
align 16
DirectDrawCreate_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call DirectDrawCreate_c
        Call_Asm_Epilogue_0 3

; DirectDrawEnumerateA (std2, DDRAW.dll)
align 16
DirectDrawEnumerateA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call DirectDrawEnumerateA_c
        Call_Asm_Epilogue_0 2

; DirectSoundCreate (std3, DSOUND.dll)
align 16
DirectSoundCreate_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call DirectSoundCreate_c
        Call_Asm_Epilogue_0 3

; DispatchMessageA (std1, USER32.dll)
align 16
DispatchMessageA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call DispatchMessageA_c
        Call_Asm_Epilogue_0 1

; msvcrt_div (c2, MSVCRT.dll)
align 16
msvcrt_div_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call msvcrt_div_c
        mov rdx, rax
        shr rdx, 32
        mov eax, eax
        Call_Asm_Epilogue_0 0

; dp_enableDebugPrint (c1, anetdll.dll)
align 16
dp_enableDebugPrint_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call dp_enableDebugPrint_c
        Call_Asm_Epilogue_0 0

; dpAddPlayerToGroup (c3, anetdll.dll)
align 16
dpAddPlayerToGroup_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call dpAddPlayerToGroup_c
        Call_Asm_Epilogue_0 0

; dpClose (c1, anetdll.dll)
align 16
dpClose_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call dpClose_c
        Call_Asm_Epilogue_0 0

; dpCreate (c4, anetdll.dll)
align 16
dpCreate_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call dpCreate_c
        Call_Asm_Epilogue_0 0

; dpCreateGroup (c3, anetdll.dll)
align 16
dpCreateGroup_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call dpCreateGroup_c
        Call_Asm_Epilogue_0 0

; dpCreatePlayer (c4, anetdll.dll)
align 16
dpCreatePlayer_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call dpCreatePlayer_c
        Call_Asm_Epilogue_0 0

; dpDestroy (c2, anetdll.dll)
align 16
dpDestroy_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call dpDestroy_c
        Call_Asm_Epilogue_0 0

; dpDestroyPlayer (c2, anetdll.dll)
align 16
dpDestroyPlayer_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call dpDestroyPlayer_c
        Call_Asm_Epilogue_0 0

; dpEnumGroupPlayers (c6, anetdll.dll)
align 16
dpEnumGroupPlayers_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call dpEnumGroupPlayers_c
        Call_Asm_Epilogue_0 0

; dpEnumGroups (c5, anetdll.dll)
align 16
dpEnumGroups_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call dpEnumGroups_c
        Call_Asm_Epilogue_0 0

; dpEnumPlayers (c5, anetdll.dll)
align 16
dpEnumPlayers_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call dpEnumPlayers_c
        Call_Asm_Epilogue_0 0

; dpEnumSessions (c6, anetdll.dll)
align 16
dpEnumSessions_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call dpEnumSessions_c
        Call_Asm_Epilogue_0 0

; dpFreeze (c2, anetdll.dll)
align 16
dpFreeze_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call dpFreeze_c
        Call_Asm_Epilogue_0 0

; dpEnumTransports (c3, anetdll.dll)
align 16
dpEnumTransports_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call dpEnumTransports_c
        Call_Asm_Epilogue_0 0

; dpGetPlayerData (c6, anetdll.dll)
align 16
dpGetPlayerData_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call dpGetPlayerData_c
        Call_Asm_Epilogue_0 0

; dpGetPlayerName (c4, anetdll.dll)
align 16
dpGetPlayerName_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call dpGetPlayerName_c
        Call_Asm_Epilogue_0 0

; dpGetSessionDesc (c3, anetdll.dll)
align 16
dpGetSessionDesc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call dpGetSessionDesc_c
        Call_Asm_Epilogue_0 0

; dpOpen (c4, anetdll.dll)
align 16
dpOpen_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call dpOpen_c
        Call_Asm_Epilogue_0 0

; dpReceive (c6, anetdll.dll)
align 16
dpReceive_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call dpReceive_c
        Call_Asm_Epilogue_0 0

; dpSend (c6, anetdll.dll)
align 16
dpSend_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call dpSend_c
        Call_Asm_Epilogue_0 0

; dpSetGameServer (c2, anetdll.dll)
align 16
dpSetGameServer_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call dpSetGameServer_c
        Call_Asm_Epilogue_0 0

; dpSetPlayerData (c6, anetdll.dll)
align 16
dpSetPlayerData_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call dpSetPlayerData_c
        Call_Asm_Epilogue_0 0

; EndDialog (std2, USER32.dll)
align 16
EndDialog_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call EndDialog_c
        Call_Asm_Epilogue_0 2

; EndPaint (std2, USER32.dll)
align 16
EndPaint_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call EndPaint_c
        Call_Asm_Epilogue_0 2

; EnterCriticalSection (std1, KERNEL32.dll)
align 16
EnterCriticalSection_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call EnterCriticalSection_c
        Call_Asm_Epilogue_0 1

; exit (c1, MSVCRT.dll)
align 16
exit_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call exit_c
        Call_Asm_Epilogue_0 0

; ExitProcess (std1, KERNEL32.dll)
align 16
ExitProcess_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call ExitProcess_c
        Call_Asm_Epilogue_0 1

; fclose (c1, MSVCRT.dll)
align 16
fclose_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call fclose_c
        Call_Asm_Epilogue_0 0

; fflush (c1, MSVCRT.dll)
align 16
fflush_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call fflush_c
        Call_Asm_Epilogue_0 0

; fgetc (c1, MSVCRT.dll)
align 16
fgetc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call fgetc_c
        Call_Asm_Epilogue_0 0

; fgets (c3, MSVCRT.dll)
align 16
fgets_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call fgets_c
        Call_Asm_Epilogue_0 0

; FindClose (std1, KERNEL32.dll)
align 16
FindClose_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call FindClose_c
        Call_Asm_Epilogue_0 1

; FindFirstFileA (std2, KERNEL32.dll)
align 16
FindFirstFileA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call FindFirstFileA_c
        Call_Asm_Epilogue_0 2

; FindNextFileA (std2, KERNEL32.dll)
align 16
FindNextFileA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call FindNextFileA_c
        Call_Asm_Epilogue_0 2

; FindWindowA (std2, USER32.dll)
align 16
FindWindowA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call FindWindowA_c
        Call_Asm_Epilogue_0 2

; floor (c2, MSVCRT.dll)
align 16
floor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call floor_c
        movsd [rsp-8], xmm0
        fld qword [rsp-8]
        Call_Asm_Epilogue_0 0

; FlushFileBuffers (std1, KERNEL32.dll)
align 16
FlushFileBuffers_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call FlushFileBuffers_c
        Call_Asm_Epilogue_0 1

; fopen (c2, MSVCRT.dll)
align 16
fopen_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call fopen_c
        Call_Asm_Epilogue_0 0

; fprintf (v2, MSVCRT.dll)
align 16
fprintf_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        lea edx, [r11d+20]
        call fprintf_c
        Call_Asm_Epilogue_0 0

; fputc (c2, MSVCRT.dll)
align 16
fputc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call fputc_c
        Call_Asm_Epilogue_0 0

; fputs (c2, MSVCRT.dll)
align 16
fputs_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call fputs_c
        Call_Asm_Epilogue_0 0

; fread (c4, MSVCRT.dll)
align 16
fread_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call fread_c
        Call_Asm_Epilogue_0 0

; free (c1, MSVCRT.dll)
align 16
free_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call free_c
        Call_Asm_Epilogue_0 0

; FreeLibrary (std1, KERNEL32.dll)
align 16
FreeLibrary_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call FreeLibrary_c
        Call_Asm_Epilogue_0 1

; fscanf (v2, MSVCRT.dll)
align 16
fscanf_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        lea edx, [r11d+20]
        call fscanf_c
        Call_Asm_Epilogue_0 0

; fseek (c3, MSVCRT.dll)
align 16
fseek_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call fseek_c
        Call_Asm_Epilogue_0 0

; ftell (c1, MSVCRT.dll)
align 16
ftell_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call ftell_c
        Call_Asm_Epilogue_0 0

; fwrite (c4, MSVCRT.dll)
align 16
fwrite_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call fwrite_c
        Call_Asm_Epilogue_0 0

; GdiFlush (std0, GDI32.dll)
align 16
GdiFlush_asm2c:
        Call_Asm_Prologue_0
        call GdiFlush_c
        Call_Asm_Epilogue_0 0

; GetAsyncKeyState (std1, USER32.dll)
align 16
GetAsyncKeyState_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetAsyncKeyState_c
        Call_Asm_Epilogue_0 1

; getc (c1, MSVCRT.dll)
align 16
getc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call getc_c
        Call_Asm_Epilogue_0 0

; GetClientRect (std2, USER32.dll)
align 16
GetClientRect_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call GetClientRect_c
        Call_Asm_Epilogue_0 2

; GetCPInfo (std2, KERNEL32.dll)
align 16
GetCPInfo_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call GetCPInfo_c
        Call_Asm_Epilogue_0 2

; GetCurrentDirectoryA (std2, KERNEL32.dll)
align 16
GetCurrentDirectoryA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call GetCurrentDirectoryA_c
        Call_Asm_Epilogue_0 2

; GetCurrentProcess (std0, KERNEL32.dll)
align 16
GetCurrentProcess_asm2c:
        Call_Asm_Prologue_0
        call GetCurrentProcess_c
        Call_Asm_Epilogue_0 0

; GetCurrentThreadId (std0, KERNEL32.dll)
align 16
GetCurrentThreadId_asm2c:
        Call_Asm_Prologue_0
        call GetCurrentThreadId_c
        Call_Asm_Epilogue_0 0

; GetCursorPos (std1, USER32.dll)
align 16
GetCursorPos_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetCursorPos_c
        Call_Asm_Epilogue_0 1

; GetDC (std1, USER32.dll)
align 16
GetDC_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetDC_c
        Call_Asm_Epilogue_0 1

; GetDeviceCaps (std2, GDI32.dll)
align 16
GetDeviceCaps_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call GetDeviceCaps_c
        Call_Asm_Epilogue_0 2

; GetDlgItem (std2, USER32.dll)
align 16
GetDlgItem_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call GetDlgItem_c
        Call_Asm_Epilogue_0 2

; GetDlgItemTextA (std4, USER32.dll)
align 16
GetDlgItemTextA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call GetDlgItemTextA_c
        Call_Asm_Epilogue_0 4

; GetDriveTypeA (std1, KERNEL32.dll)
align 16
GetDriveTypeA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetDriveTypeA_c
        Call_Asm_Epilogue_0 1

; GetFileTime (std4, KERNEL32.dll)
align 16
GetFileTime_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call GetFileTime_c
        Call_Asm_Epilogue_0 4

; GetFileType (std1, KERNEL32.dll)
align 16
GetFileType_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetFileType_c
        Call_Asm_Epilogue_0 1

; GetFocus (std0, USER32.dll)
align 16
GetFocus_asm2c:
        Call_Asm_Prologue_0
        call GetFocus_c
        Call_Asm_Epilogue_0 0

; GetKeyboardType (std1, USER32.dll)
align 16
GetKeyboardType_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetKeyboardType_c
        Call_Asm_Epilogue_0 1

; GetKeyState (std1, USER32.dll)
align 16
GetKeyState_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetKeyState_c
        Call_Asm_Epilogue_0 1

; GetLastError (std0, KERNEL32.dll)
align 16
GetLastError_asm2c:
        Call_Asm_Prologue_0
        call GetLastError_c
        Call_Asm_Epilogue_0 0

; GetLocaleInfoA (std4, KERNEL32.dll)
align 16
GetLocaleInfoA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call GetLocaleInfoA_c
        Call_Asm_Epilogue_0 4

; GetLocaleInfoW (std4, KERNEL32.dll)
align 16
GetLocaleInfoW_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call GetLocaleInfoW_c
        Call_Asm_Epilogue_0 4

; GetLogicalDrives (std0, KERNEL32.dll)
align 16
GetLogicalDrives_asm2c:
        Call_Asm_Prologue_0
        call GetLogicalDrives_c
        Call_Asm_Epilogue_0 0

; GetLogicalDriveStringsA (std2, KERNEL32.dll)
align 16
GetLogicalDriveStringsA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call GetLogicalDriveStringsA_c
        Call_Asm_Epilogue_0 2

; GetModuleFileNameA (std3, KERNEL32.dll)
align 16
GetModuleFileNameA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call GetModuleFileNameA_c
        Call_Asm_Epilogue_0 3

; GetModuleHandleA (std1, KERNEL32.dll)
align 16
GetModuleHandleA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetModuleHandleA_c
        Call_Asm_Epilogue_0 1

; GetProcAddress (std2, KERNEL32.dll)
align 16
GetProcAddress_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call GetProcAddress_c
        Call_Asm_Epilogue_0 2

; GetProcessHeap (std0, KERNEL32.dll)
align 16
GetProcessHeap_asm2c:
        Call_Asm_Prologue_0
        call GetProcessHeap_c
        Call_Asm_Epilogue_0 0

; GetStdHandle (std1, KERNEL32.dll)
align 16
GetStdHandle_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetStdHandle_c
        Call_Asm_Epilogue_0 1

; GetStockObject (std1, GDI32.dll)
align 16
GetStockObject_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetStockObject_c
        Call_Asm_Epilogue_0 1

; GetStringTypeA (std5, KERNEL32.dll)
align 16
GetStringTypeA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call GetStringTypeA_c
        Call_Asm_Epilogue_0 5

; GetStringTypeW (std4, KERNEL32.dll)
align 16
GetStringTypeW_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call GetStringTypeW_c
        Call_Asm_Epilogue_0 4

; GetSystemDefaultLCID (std0, KERNEL32.dll)
align 16
GetSystemDefaultLCID_asm2c:
        Call_Asm_Prologue_0
        call GetSystemDefaultLCID_c
        Call_Asm_Epilogue_0 0

; GetSystemInfo (std1, KERNEL32.dll)
align 16
GetSystemInfo_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetSystemInfo_c
        Call_Asm_Epilogue_0 1

; GetSystemMetrics (std1, USER32.dll)
align 16
GetSystemMetrics_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call GetSystemMetrics_c
        Call_Asm_Epilogue_0 1

; GetSystemPaletteEntries (std4, GDI32.dll)
align 16
GetSystemPaletteEntries_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call GetSystemPaletteEntries_c
        Call_Asm_Epilogue_0 4

; GetTextExtentExPointA (std7, GDI32.dll)
align 16
GetTextExtentExPointA_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 16
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call GetTextExtentExPointA_c
        add rsp, 16
        Call_Asm_Epilogue_0 7

; GetTextExtentPoint32A (std4, GDI32.dll)
align 16
GetTextExtentPoint32A_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call GetTextExtentPoint32A_c
        Call_Asm_Epilogue_0 4

; GetTickCount (std0, KERNEL32.dll)
align 16
GetTickCount_asm2c:
        Call_Asm_Prologue_0
        call GetTickCount_c
        Call_Asm_Epilogue_0 0

; GetVolumeInformationA (std8, KERNEL32.dll)
align 16
GetVolumeInformationA_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 16
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov eax, [r11d+40]
        mov [rsp+8], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call GetVolumeInformationA_c
        add rsp, 16
        Call_Asm_Epilogue_0 8

; GetWindowLongA (std2, USER32.dll)
align 16
GetWindowLongA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call GetWindowLongA_c
        Call_Asm_Epilogue_0 2

; GetWindowRect (std2, USER32.dll)
align 16
GetWindowRect_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call GetWindowRect_c
        Call_Asm_Epilogue_0 2

; GetWindowsDirectoryA (std2, KERNEL32.dll)
align 16
GetWindowsDirectoryA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call GetWindowsDirectoryA_c
        Call_Asm_Epilogue_0 2

; HeapAlloc (std3, KERNEL32.dll)
align 16
HeapAlloc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call HeapAlloc_c
        Call_Asm_Epilogue_0 3

; HeapCompact (std2, KERNEL32.dll)
align 16
HeapCompact_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call HeapCompact_c
        Call_Asm_Epilogue_0 2

; HeapCreate (std3, KERNEL32.dll)
align 16
HeapCreate_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call HeapCreate_c
        Call_Asm_Epilogue_0 3

; HeapDestroy (std1, KERNEL32.dll)
align 16
HeapDestroy_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call HeapDestroy_c
        Call_Asm_Epilogue_0 1

; HeapFree (std3, KERNEL32.dll)
align 16
HeapFree_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call HeapFree_c
        Call_Asm_Epilogue_0 3

; HeapReAlloc (std4, KERNEL32.dll)
align 16
HeapReAlloc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call HeapReAlloc_c
        Call_Asm_Epilogue_0 4

; HeapSize (std3, KERNEL32.dll)
align 16
HeapSize_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call HeapSize_c
        Call_Asm_Epilogue_0 3

; ImmAssociateContext (std2, IMM32.dll)
align 16
ImmAssociateContext_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call ImmAssociateContext_c
        Call_Asm_Epilogue_0 2

; InitializeCriticalSection (std1, KERNEL32.dll)
align 16
InitializeCriticalSection_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call InitializeCriticalSection_c
        Call_Asm_Epilogue_0 1

; InterlockedDecrement (std1, KERNEL32.dll)
align 16
InterlockedDecrement_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call InterlockedDecrement_c
        Call_Asm_Epilogue_0 1

; InterlockedIncrement (std1, KERNEL32.dll)
align 16
InterlockedIncrement_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call InterlockedIncrement_c
        Call_Asm_Epilogue_0 1

; isspace (c1, MSVCRT.dll)
align 16
isspace_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call isspace_c
        Call_Asm_Epilogue_0 0

; joyGetDevCapsA (std3, WIN32.dll)
align 16
joyGetDevCapsA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call joyGetDevCapsA_c
        Call_Asm_Epilogue_0 3

; joyGetNumDevs (std0, WIN32.dll)
align 16
joyGetNumDevs_asm2c:
        Call_Asm_Prologue_0
        call joyGetNumDevs_c
        Call_Asm_Epilogue_0 0

; joyGetPos (std2, WINMM.dll)
align 16
joyGetPos_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call joyGetPos_c
        Call_Asm_Epilogue_0 2

; joyGetPosEx (std2, WIN32.dll)
align 16
joyGetPosEx_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call joyGetPosEx_c
        Call_Asm_Epilogue_0 2

; LCMapStringA (std6, KERNEL32.dll)
align 16
LCMapStringA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call LCMapStringA_c
        Call_Asm_Epilogue_0 6

; LCMapStringW (std6, KERNEL32.dll)
align 16
LCMapStringW_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call LCMapStringW_c
        Call_Asm_Epilogue_0 6

; LeaveCriticalSection (std1, KERNEL32.dll)
align 16
LeaveCriticalSection_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call LeaveCriticalSection_c
        Call_Asm_Epilogue_0 1

; LoadCursorA (std2, USER32.dll)
align 16
LoadCursorA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call LoadCursorA_c
        Call_Asm_Epilogue_0 2

; LoadCursorFromFileA (std1, USER32.dll)
align 16
LoadCursorFromFileA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call LoadCursorFromFileA_c
        Call_Asm_Epilogue_0 1

; LoadLibraryA (std1, KERNEL32.dll)
align 16
LoadLibraryA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call LoadLibraryA_c
        Call_Asm_Epilogue_0 1

; LoadModule (std2, KERNEL32.dll)
align 16
LoadModule_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call LoadModule_c
        Call_Asm_Epilogue_0 2

; lstrcatA (std2, KERNEL32.dll)
align 16
lstrcatA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call lstrcatA_c
        Call_Asm_Epilogue_0 2

; lstrcpyA (std2, KERNEL32.dll)
align 16
lstrcpyA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call lstrcpyA_c
        Call_Asm_Epilogue_0 2

; malloc (c1, MSVCRT.dll)
align 16
malloc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call malloc_c
        Call_Asm_Epilogue_0 0

; MapViewOfFile (std5, KERNEL32.dll)
align 16
MapViewOfFile_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call MapViewOfFile_c
        Call_Asm_Epilogue_0 5

; MapVirtualKeyA (std2, USER32.dll)
align 16
MapVirtualKeyA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call MapVirtualKeyA_c
        Call_Asm_Epilogue_0 2

; mciGetErrorStringA (std3, WIN32.dll)
align 16
mciGetErrorStringA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call mciGetErrorStringA_c
        Call_Asm_Epilogue_0 3

; mciSendCommandA (std4, WIN32.dll)
align 16
mciSendCommandA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call mciSendCommandA_c
        Call_Asm_Epilogue_0 4

; memmove (c3, MSVCRT.dll)
align 16
memmove_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call memmove_c
        Call_Asm_Epilogue_0 0

; MessageBoxA (std4, USER32.dll)
align 16
MessageBoxA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call MessageBoxA_c
        Call_Asm_Epilogue_0 4

; MultiByteToWideChar (std6, KERNEL32.dll)
align 16
MultiByteToWideChar_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call MultiByteToWideChar_c
        Call_Asm_Epilogue_0 6

; OutputDebugStringA (std1, KERNEL32.dll)
align 16
OutputDebugStringA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call OutputDebugStringA_c
        Call_Asm_Epilogue_0 1

; PeekMessageA (std5, USER32.dll)
align 16
PeekMessageA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call PeekMessageA_c
        Call_Asm_Epilogue_0 5

; PostMessageA (std4, USER32.dll)
align 16
PostMessageA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call PostMessageA_c
        Call_Asm_Epilogue_0 4

; PostQuitMessage (std1, USER32.dll)
align 16
PostQuitMessage_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call PostQuitMessage_c
        Call_Asm_Epilogue_0 1

; qsort (c4, MSVCRT.dll)
align 16
qsort_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call qsort_c
        Call_Asm_Epilogue_0 0

; rand (c0, MSVCRT.dll)
align 16
rand_asm2c:
        Call_Asm_Prologue_0
        call rand_c
        Call_Asm_Epilogue_0 0

; ReadFile (std5, KERNEL32.dll)
align 16
ReadFile_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call ReadFile_c
        Call_Asm_Epilogue_0 5

; RealizePalette (std1, GDI32.dll)
align 16
RealizePalette_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call RealizePalette_c
        Call_Asm_Epilogue_0 1

; realloc (c2, MSVCRT.dll)
align 16
realloc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call realloc_c
        Call_Asm_Epilogue_0 0

; Rectangle (std5, GDI32.dll)
align 16
Rectangle_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call Rectangle_c
        Call_Asm_Epilogue_0 5

; RegCloseKey (std1, ADVAPI32.dll)
align 16
RegCloseKey_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call RegCloseKey_c
        Call_Asm_Epilogue_0 1

; RegCreateKeyExA (std9, ADVAPI32.dll)
align 16
RegCreateKeyExA_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 32
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov eax, [r11d+40]
        mov [rsp+8], rax
        mov eax, [r11d+44]
        mov [rsp+16], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call RegCreateKeyExA_c
        add rsp, 32
        Call_Asm_Epilogue_0 9

; RegisterClassA (std1, USER32.dll)
align 16
RegisterClassA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call RegisterClassA_c
        Call_Asm_Epilogue_0 1

; RegOpenKeyExA (std5, ADVAPI32.dll)
align 16
RegOpenKeyExA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call RegOpenKeyExA_c
        Call_Asm_Epilogue_0 5

; RegQueryValueExA (std6, ADVAPI32.dll)
align 16
RegQueryValueExA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call RegQueryValueExA_c
        Call_Asm_Epilogue_0 6

; RegSetValueExA (std6, ADVAPI32.dll)
align 16
RegSetValueExA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call RegSetValueExA_c
        Call_Asm_Epilogue_0 6

; ReleaseDC (std2, USER32.dll)
align 16
ReleaseDC_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call ReleaseDC_c
        Call_Asm_Epilogue_0 2

; RemoveFontResourceA (std1, GDI32.dll)
align 16
RemoveFontResourceA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call RemoveFontResourceA_c
        Call_Asm_Epilogue_0 1

; ScreenToClient (std2, USER32.dll)
align 16
ScreenToClient_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call ScreenToClient_c
        Call_Asm_Epilogue_0 2

; SelectObject (std2, GDI32.dll)
align 16
SelectObject_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SelectObject_c
        Call_Asm_Epilogue_0 2

; SelectPalette (std3, GDI32.dll)
align 16
SelectPalette_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call SelectPalette_c
        Call_Asm_Epilogue_0 3

; SendDlgItemMessageA (std5, USER32.dll)
align 16
SendDlgItemMessageA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call SendDlgItemMessageA_c
        Call_Asm_Epilogue_0 5

; SendMessageA (std4, USER32.dll)
align 16
SendMessageA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call SendMessageA_c
        Call_Asm_Epilogue_0 4

; SetBkColor (std2, GDI32.dll)
align 16
SetBkColor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SetBkColor_c
        Call_Asm_Epilogue_0 2

; SetBkMode (std2, GDI32.dll)
align 16
SetBkMode_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SetBkMode_c
        Call_Asm_Epilogue_0 2

; SetCursor (std1, USER32.dll)
align 16
SetCursor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call SetCursor_c
        Call_Asm_Epilogue_0 1

; SetCursorPos (std2, USER32.dll)
align 16
SetCursorPos_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SetCursorPos_c
        Call_Asm_Epilogue_0 2

; SetDIBColorTable (std4, GDI32.dll)
align 16
SetDIBColorTable_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call SetDIBColorTable_c
        Call_Asm_Epilogue_0 4

; SetDIBitsToDevice (std12, GDI32.dll)
align 16
SetDIBitsToDevice_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 48
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov eax, [r11d+40]
        mov [rsp+8], rax
        mov eax, [r11d+44]
        mov [rsp+16], rax
        mov eax, [r11d+48]
        mov [rsp+24], rax
        mov eax, [r11d+52]
        mov [rsp+32], rax
        mov eax, [r11d+56]
        mov [rsp+40], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call SetDIBitsToDevice_c
        add rsp, 48
        Call_Asm_Epilogue_0 12

; SetDlgItemTextA (std3, USER32.dll)
align 16
SetDlgItemTextA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call SetDlgItemTextA_c
        Call_Asm_Epilogue_0 3

; SetEndOfFile (std1, KERNEL32.dll)
align 16
SetEndOfFile_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call SetEndOfFile_c
        Call_Asm_Epilogue_0 1

; SetFileAttributesA (std2, KERNEL32.dll)
align 16
SetFileAttributesA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SetFileAttributesA_c
        Call_Asm_Epilogue_0 2

; SetFilePointer (std4, KERNEL32.dll)
align 16
SetFilePointer_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call SetFilePointer_c
        Call_Asm_Epilogue_0 4

; SetFocus (std1, USER32.dll)
align 16
SetFocus_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call SetFocus_c
        Call_Asm_Epilogue_0 1

; SetLastError (std1, KERNEL32.dll)
align 16
SetLastError_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call SetLastError_c
        Call_Asm_Epilogue_0 1

; setlocale (c2, MSVCRT.dll)
align 16
setlocale_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call setlocale_c
        Call_Asm_Epilogue_0 0

; SetMapperFlags (std2, GDI32.dll)
align 16
SetMapperFlags_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SetMapperFlags_c
        Call_Asm_Epilogue_0 2

; SetMenu (std2, USER32.dll)
align 16
SetMenu_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SetMenu_c
        Call_Asm_Epilogue_0 2

; SetPaletteEntries (std4, GDI32.dll)
align 16
SetPaletteEntries_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call SetPaletteEntries_c
        Call_Asm_Epilogue_0 4

; SetPriorityClass (std2, KERNEL32.dll)
align 16
SetPriorityClass_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SetPriorityClass_c
        Call_Asm_Epilogue_0 2

; SetRect (std5, USER32.dll)
align 16
SetRect_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call SetRect_c
        Call_Asm_Epilogue_0 5

; SetStdHandle (std2, KERNEL32.dll)
align 16
SetStdHandle_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SetStdHandle_c
        Call_Asm_Epilogue_0 2

; SetSystemPaletteUse (std2, GDI32.dll)
align 16
SetSystemPaletteUse_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SetSystemPaletteUse_c
        Call_Asm_Epilogue_0 2

; SetTextColor (std2, GDI32.dll)
align 16
SetTextColor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SetTextColor_c
        Call_Asm_Epilogue_0 2

; setvbuf (c4, MSVCRT.dll)
align 16
setvbuf_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call setvbuf_c
        Call_Asm_Epilogue_0 0

; SetWindowLongA (std3, USER32.dll)
align 16
SetWindowLongA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call SetWindowLongA_c
        Call_Asm_Epilogue_0 3

; SetWindowPos (std7, USER32.dll)
align 16
SetWindowPos_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 16
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call SetWindowPos_c
        add rsp, 16
        Call_Asm_Epilogue_0 7

; ShowCursor (std1, USER32.dll)
align 16
ShowCursor_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call ShowCursor_c
        Call_Asm_Epilogue_0 1

; ShowWindow (std2, USER32.dll)
align 16
ShowWindow_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call ShowWindow_c
        Call_Asm_Epilogue_0 2

; Sleep (std1, KERNEL32.dll)
align 16
Sleep_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call Sleep_c
        Call_Asm_Epilogue_0 1

; SmackBufferBlit (std8, smackw32.DLL)
align 16
SmackBufferBlit_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 16
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov eax, [r11d+40]
        mov [rsp+8], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call SmackBufferBlit_c
        add rsp, 16
        Call_Asm_Epilogue_0 8

; SmackBufferClose (std1, smackw32.DLL)
align 16
SmackBufferClose_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call SmackBufferClose_c
        Call_Asm_Epilogue_0 1

; SmackBufferNewPalette (std3, smackw32.DLL)
align 16
SmackBufferNewPalette_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call SmackBufferNewPalette_c
        Call_Asm_Epilogue_0 3

; SmackBufferOpen (std6, smackw32.DLL)
align 16
SmackBufferOpen_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call SmackBufferOpen_c
        Call_Asm_Epilogue_0 6

; SmackBufferSetPalette (std1, smackw32.DLL)
align 16
SmackBufferSetPalette_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call SmackBufferSetPalette_c
        Call_Asm_Epilogue_0 1

; SmackClose (std1, smackw32.DLL)
align 16
SmackClose_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call SmackClose_c
        Call_Asm_Epilogue_0 1

; SmackColorRemap (std4, smackw32.DLL)
align 16
SmackColorRemap_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call SmackColorRemap_c
        Call_Asm_Epilogue_0 4

; SmackDoFrame (std1, smackw32.DLL)
align 16
SmackDoFrame_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call SmackDoFrame_c
        Call_Asm_Epilogue_0 1

; SmackNextFrame (std1, smackw32.DLL)
align 16
SmackNextFrame_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call SmackNextFrame_c
        Call_Asm_Epilogue_0 1

; SmackOpen (std3, smackw32.DLL)
align 16
SmackOpen_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call SmackOpen_c
        Call_Asm_Epilogue_0 3

; SmackSoundOnOff (std2, smackw32.DLL)
align 16
SmackSoundOnOff_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SmackSoundOnOff_c
        Call_Asm_Epilogue_0 2

; SmackSoundUseDirectSound (std1, smackw32.DLL)
align 16
SmackSoundUseDirectSound_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call SmackSoundUseDirectSound_c
        Call_Asm_Epilogue_0 1

; SmackToBuffer (std7, smackw32.DLL)
align 16
SmackToBuffer_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 16
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call SmackToBuffer_c
        add rsp, 16
        Call_Asm_Epilogue_0 7

; SmackToBufferRect (std2, smackw32.DLL)
align 16
SmackToBufferRect_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call SmackToBufferRect_c
        Call_Asm_Epilogue_0 2

; SmackWait (std1, smackw32.DLL)
align 16
SmackWait_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call SmackWait_c
        Call_Asm_Epilogue_0 1

; sprintf (v2, MSVCRT.dll)
align 16
sprintf_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        lea edx, [r11d+20]
        call sprintf_c
        Call_Asm_Epilogue_0 0

; srand (c1, MSVCRT.dll)
align 16
srand_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call srand_c
        Call_Asm_Epilogue_0 0

; sscanf (v2, MSVCRT.dll)
align 16
sscanf_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        lea edx, [r11d+20]
        call sscanf_c
        Call_Asm_Epilogue_0 0

; strchr (c2, MSVCRT.dll)
align 16
strchr_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call strchr_c
        Call_Asm_Epilogue_0 0

; StretchBlt (std11, GDI32.dll)
align 16
StretchBlt_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 48
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov eax, [r11d+40]
        mov [rsp+8], rax
        mov eax, [r11d+44]
        mov [rsp+16], rax
        mov eax, [r11d+48]
        mov [rsp+24], rax
        mov eax, [r11d+52]
        mov [rsp+32], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call StretchBlt_c
        add rsp, 48
        Call_Asm_Epilogue_0 11

; strncmp (c3, MSVCRT.dll)
align 16
strncmp_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call strncmp_c
        Call_Asm_Epilogue_0 0

; strncpy (c3, MSVCRT.dll)
align 16
strncpy_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call strncpy_c
        Call_Asm_Epilogue_0 0

; strpbrk (c2, MSVCRT.dll)
align 16
strpbrk_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call strpbrk_c
        Call_Asm_Epilogue_0 0

; strrchr (c2, MSVCRT.dll)
align 16
strrchr_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call strrchr_c
        Call_Asm_Epilogue_0 0

; strstr (c2, MSVCRT.dll)
align 16
strstr_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call strstr_c
        Call_Asm_Epilogue_0 0

; strtok (c2, MSVCRT.dll)
align 16
strtok_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call strtok_c
        Call_Asm_Epilogue_0 0

; TerminateProcess (std2, KERNEL32.dll)
align 16
TerminateProcess_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call TerminateProcess_c
        Call_Asm_Epilogue_0 2

; TextOutA (std5, GDI32.dll)
align 16
TextOutA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call TextOutA_c
        Call_Asm_Epilogue_0 5

; time (c1, MSVCRT.dll)
align 16
time_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call time_c
        Call_Asm_Epilogue_0 0

; timeGetTime (std0, WIN32.dll)
align 16
timeGetTime_asm2c:
        Call_Asm_Prologue_0
        call timeGetTime_c
        Call_Asm_Epilogue_0 0

; TlsGetValue (std1, KERNEL32.dll)
align 16
TlsGetValue_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call TlsGetValue_c
        Call_Asm_Epilogue_0 1

; TlsSetValue (std2, KERNEL32.dll)
align 16
TlsSetValue_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call TlsSetValue_c
        Call_Asm_Epilogue_0 2

; ToAscii (std5, USER32.dll)
align 16
ToAscii_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call ToAscii_c
        Call_Asm_Epilogue_0 5

; tolower (c1, MSVCRT.dll)
align 16
tolower_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call tolower_c
        Call_Asm_Epilogue_0 0

; toupper (c1, MSVCRT.dll)
align 16
toupper_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call toupper_c
        Call_Asm_Epilogue_0 0

; TranslateMessage (std1, USER32.dll)
align 16
TranslateMessage_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call TranslateMessage_c
        Call_Asm_Epilogue_0 1

; UnmapViewOfFile (std1, KERNEL32.dll)
align 16
UnmapViewOfFile_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call UnmapViewOfFile_c
        Call_Asm_Epilogue_0 1

; UpdateWindow (std1, USER32.dll)
align 16
UpdateWindow_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call UpdateWindow_c
        Call_Asm_Epilogue_0 1

; ValidateRect (std2, USER32.dll)
align 16
ValidateRect_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call ValidateRect_c
        Call_Asm_Epilogue_0 2

; VirtualAlloc (std4, KERNEL32.dll)
align 16
VirtualAlloc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        call VirtualAlloc_c
        Call_Asm_Epilogue_0 4

; VirtualFree (std3, KERNEL32.dll)
align 16
VirtualFree_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call VirtualFree_c
        Call_Asm_Epilogue_0 3

; VirtualQuery (std3, KERNEL32.dll)
align 16
VirtualQuery_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call VirtualQuery_c
        Call_Asm_Epilogue_0 3

; WaitForSingleObject (std2, KERNEL32.dll)
align 16
WaitForSingleObject_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call WaitForSingleObject_c
        Call_Asm_Epilogue_0 2

; WideCharToMultiByte (std8, KERNEL32.dll)
align 16
WideCharToMultiByte_asm2c:
        Call_Asm_Prologue_0
        sub rsp, 16
        mov eax, [r11d+36]
        mov [rsp+0], rax
        mov eax, [r11d+40]
        mov [rsp+8], rax
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        mov r9d, [r11d+32]
        call WideCharToMultiByte_c
        add rsp, 16
        Call_Asm_Epilogue_0 8

; WriteFile (std5, KERNEL32.dll)
align 16
WriteFile_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        mov ecx, [r11d+24]
        mov r8d, [r11d+28]
        call WriteFile_c
        Call_Asm_Epilogue_0 5

; wsprintfA (v2, USER32.dll)
align 16
wsprintfA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        lea edx, [r11d+20]
        call wsprintfA_c
        Call_Asm_Epilogue_0 0

; wvsprintfA (std3, USER32.dll)
align 16
wvsprintfA_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call wvsprintfA_c
        Call_Asm_Epilogue_0 3

; strspn (c2, static)
align 16
strspn_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call strspn_c
        Call_Asm_Epilogue_0 0

; strcspn (c2, static)
align 16
strcspn_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call strcspn_c
        Call_Asm_Epilogue_0 0

; strncat (c3, static)
align 16
strncat_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call strncat_c
        Call_Asm_Epilogue_0 0

; vsprintf (c3, static)
align 16
vsprintf_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call vsprintf_c
        Call_Asm_Epilogue_0 0

; memcpy (c3, static)
align 16
memcpy_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call memcpy_c
        Call_Asm_Epilogue_0 0

; printf (v1, static)
align 16
printf_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        lea esi, [r11d+16]
        call printf_c
        Call_Asm_Epilogue_0 0

; ungetc (c2, static)
align 16
ungetc_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        call ungetc_c
        Call_Asm_Epilogue_0 0

; _filbuf (c1, static)
align 16
_filbuf_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        call _filbuf_c
        Call_Asm_Epilogue_0 0

; i76_frame_tick (std0, runtime)
align 16
i76_frame_tick_asm2c:
        Call_Asm_Prologue_0
        call i76_frame_tick_c
        Call_Asm_Epilogue_0 0

; i76shell_part_strncmp (c3, runtime)
align 16
i76shell_part_strncmp_asm2c:
        Call_Asm_Prologue_0
        mov edi, [r11d+12]
        mov esi, [r11d+16]
        mov edx, [r11d+20]
        call i76shell_part_strncmp_c
        Call_Asm_Epilogue_0 0

