import os
import re
import shutil
import sys

Import('device env')

include_re = re.compile(r'^%include\s+"(\S+)"\r?$', re.M)

def nasmfile_scan(node, env, path):
    contents = node.get_text_contents()
    includes = include_re.findall(contents)
    if len(includes) > 0:
        dirparts = node.dir.path.split(os.sep)
        if len(dirparts) >= 2 and dirparts[0] == 'x64':
            includes = ['../' + include if not node.File(include).exists() and node.File('../' + include).exists() else include for include in includes]
    return includes

nasmscan = Scanner(function = nasmfile_scan,
                   skeys = ['.asm'],
                   recursive = True)

SourceFileScanner.add_scanner('.asm', nasmscan)

env1 = Environment(tools=['nasm'], ASFLAGS = ('-fwin64' if device == 'pc64-windows' else '-felf64') + ' -w+orphan-labels -w-number-overflow -ix64/')
if device == 'pc64-windows':
    env1['OBJSUFFIX'] = '.w64.o'    # the Linux x64 build uses .o in the same directories
env1_path = env1['ENV']['PATH'].split(os.pathsep)
nasm_path = shutil.which('nasm')
if nasm_path is not None:
    nasm_dir = os.path.dirname(nasm_path)
    if nasm_dir not in env1_path:
        env1_path.append(nasm_dir)
env1['ENV']['PATH'] = os.pathsep.join(env1_path)
env2 = env1.Clone()
env1.Append(ASFLAGS = ' -Ox')
env2.Append(ASFLAGS = ' -O1')

module_objs = []
for module in ['i76', 'i76shell', 'zglide', 'strlkup']:
    module_objs += SConscript(module + '/SConscript', exports='device env2')

obj = env1.Object(Glob('*.asm')) + env.Object(Glob('*.c')) + module_objs

Return('obj')
