#! /usr/bin/python3
#
#  Generates the import glue for the recompiled Interstate '76 modules from imports.spec:
#    x86/imports.inc       - maps every imported name to its asm2c stub (or runtime data symbol)
#    x86/imports-asm.asm   - asm2c stubs (align stack to 16 bytes and call the C implementation)
#    imports-stubs.c       - weak default C implementations (log "unimplemented" and return 0)
#
#  Real implementations are ordinary (strong) C functions named <cname>_c and override the weak ones.
#

import os
import re
import sys

base = os.path.dirname(os.path.abspath(__file__))

special_names = {
    '??2@YAPAXI@Z': 'operator_new',
    '??3@YAXPAX@Z': 'operator_delete',
}


def cname(name):
    if name in special_names:
        return special_names[name]
    m = re.match(r'^_(\w+)@\d+$', name)
    if m:
        return m.group(1)
    return re.sub(r'[^A-Za-z0-9_]', '_', name)


def load_spec():
    items = []
    for line in open(os.path.join(base, 'imports.spec')):
        line = line.split('#', 1)[0].strip()
        if not line:
            continue
        f = line.split()
        items.append({'name': f[0], 'conv': f[1], 'flags': f[2], 'dll': f[3], 'c': cname(f[0])})
    return items


def conv_args(conv):
    m = re.match(r'^(std|c|v)(\d+)$', conv)
    if m:
        return m.group(1), int(m.group(2))
    return conv, 0


header_asm = ''';; generated by gen_imports.py from imports.spec - do not edit

'''


def write_extern_inc(items):
    out = [header_asm]
    for it in items:
        kind, n = conv_args(it['conv'])
        if kind == 'module':
            continue
        if kind == 'data':
            out.append('extern msvcrt_%s\n%%define %s msvcrt_%s\n' % (it['c'], it['name'], it['c']))
        else:
            out.append('extern %s_asm2c\n%%define %s %s_asm2c\n' % (it['c'], it['name'], it['c']))
    open(os.path.join(base, 'x86', 'imports.inc'), 'w').write(''.join(out))


def write_imports_asm(items):
    out = [header_asm, '%include "asm-calls.inc"\n\n']
    funcs = [it for it in items if conv_args(it['conv'])[0] in ('std', 'c', 'v', 'f1f', 'f2f')]
    for it in funcs:
        out.append('extern %s_c\n' % it['c'])
    out.append('\n')
    for it in funcs:
        out.append('global %s_asm2c\n' % it['c'])
    out.append('''
%ifidn __OUTPUT_FORMAT__, elf32
section .note.GNU-stack noalloc noexec nowrite progbits
section .text progbits alloc exec nowrite align=16
%else
section .text code align=16
%endif

''')
    for it in funcs:
        kind, n = conv_args(it['conv'])
        out.append('align 16\n%s_asm2c:\n; %s (%s, %s)\n' % (it['c'], it['name'], it['conv'], it['dll']))
        if kind == 'std':
            out.append('        Call_Asm_Stack%d %s_c, %d\n\n' % (n, it['c'], n))
        elif kind == 'c':
            out.append('        Call_Asm_Stack%d %s_c\n\n' % (n, it['c']))
        elif kind == 'v':
            out.append('        Call_Asm_VariableStack%d %s_c\n\n' % (n, it['c']))
        elif kind == 'f1f':
            out.append('        Call_Asm_Float1_Float %s_c\n\n' % it['c'])
        elif kind == 'f2f':
            out.append('        Call_Asm_Float2_Float %s_c\n\n' % it['c'])
    open(os.path.join(base, 'x86', 'imports-asm.asm'), 'w').write(''.join(out))


def write_stubs_c(items):
    out = ['''/* generated by gen_imports.py from imports.spec - do not edit */

#include <stdint.h>
#include <stdio.h>
#include "platform.h"

static void unimplemented(const char *name, int *reported)
{
    if (!*reported)
    {
        *reported = 1;
        fprintf(stderr, "unimplemented import: %s\\n", name);
    }
}

#define WEAK __attribute__((weak))

''']
    for it in items:
        kind, n = conv_args(it['conv'])
        c = it['c']
        ret = 'double' if it['flags'] == 'fret' else 'uint32_t'
        if kind in ('std', 'c'):
            args = ', '.join('uint32_t a%d' % i for i in range(n)) or 'void'
        elif kind == 'v':
            args = ', '.join(['uint32_t a%d' % i for i in range(n)] + ['uint32_t *ap'])
        elif kind in ('f1f', 'f2f'):
            args = 'double *args'
            ret = 'void'
        else:
            continue
        body = 'unimplemented("%s", &reported);' % it['name'].replace('\\', '\\\\')
        if ret != 'void':
            body += ' return 0;'
        # stdcall/cdecl only matters for the asm2c stub, the C side is always called as cdecl
        out.append('WEAK %s CCALL %s_c(%s) { static int reported; %s }\n' % (ret, c, args, body))
    open(os.path.join(base, 'imports-stubs.c'), 'w').write(''.join(out))


items = load_spec()
write_extern_inc(items)
write_imports_asm(items)
write_stubs_c(items)
print('%d imports' % len(items))
