#! /usr/bin/python3
#
#  Generates the import glue for the recompiled Interstate '76 modules from imports.spec:
#    x86/imports.inc       - maps every imported name to its asm2c stub (or runtime data symbol)
#    x86/imports-asm.asm   - asm2c stubs (align stack to 16 bytes and call the C implementation)
#    imports-stubs.c       - weak default C implementations (log "unimplemented" and return 0)
#  x64/imports-asm.asm and x64/com-asm.asm are the x86-64 (OUT_X64, SysV ABI) versions: each stub loads its
#  arguments from the emulated x86 stack (r11d) explicitly (Septerra's x64 asm-calls.inc macros only for the
#  FPU intrinsics), converts double (xmm0 -> st0) and 64-bit (rax -> edx:eax) results.
#  and the COM glue from com.spec:
#    x86/com-asm.asm       - <Iface>_<Method>_asm2c stubs and <Iface>Vtbl_asm2c vtables
#    com-stubs.c           - weak <Iface>_<Method>_c implementations returning E_NOTIMPL
#
#  Real implementations are ordinary (strong) C functions named <cname>_c and override the weak ones.
#

import glob
import os
import re
import sys

base = os.path.dirname(os.path.abspath(__file__))

special_names = {
    '??2@YAPAXI@Z': 'operator_new',
    '??3@YAXPAX@Z': 'operator_delete',
    '_vsnprintf': 'ms_vsnprintf',       # _vsnprintf_c is a function of the Windows CRT
}


def cname(name):
    if name in special_names:
        return special_names[name]
    m = re.match(r'^_(\w+)@\d+$', name)
    if m:
        return m.group(1)
    return re.sub(r'[^A-Za-z0-9_]', '_', name)


def load_spec():
    items = []
    for line in open(os.path.join(base, 'imports.spec')):
        line = line.split('#', 1)[0].strip()
        if not line:
            continue
        f = line.split()
        items.append({'name': f[0], 'conv': f[1], 'flags': f[2], 'dll': f[3], 'c': cname(f[0])})
    return items


def conv_args(conv):
    m = re.match(r'^(std|c|v)(\d+)$', conv)
    if m:
        return m.group(1), int(m.group(2))
    return conv, 0


header_asm = ''';; generated by gen_imports.py from imports.spec - do not edit

'''


def write_extern_inc(items):
    out = [header_asm]
    for it in items:
        kind, n = conv_args(it['conv'])
        if kind == 'module':
            continue
        if kind == 'data':
            out.append('extern msvcrt_%s\n%%define %s msvcrt_%s\n' % (it['c'], it['name'], it['c']))
        else:
            out.append('extern %s_asm2c\n%%define %s %s_asm2c\n' % (it['c'], it['name'], it['c']))
    open(os.path.join(base, 'x86', 'imports.inc'), 'w').write(''.join(out))
    open(os.path.join(base, 'x64', 'imports.inc'), 'w').write(''.join(out))


def write_imports_asm(items):
    out = [header_asm, '%include "asm-calls.inc"\n\n']
    funcs = [it for it in items if conv_args(it['conv'])[0] in ('std', 'c', 'v', 'f1f', 'f2f')]
    for it in funcs:
        out.append('extern %s_c\n' % it['c'])
    out.append('\n')
    for it in funcs:
        out.append('global %s_asm2c\n' % it['c'])
    out.append('''
%ifidn __OUTPUT_FORMAT__, elf32
section .note.GNU-stack noalloc noexec nowrite progbits
section .text progbits alloc exec nowrite align=16
%else
section .text code align=16
%endif

''')
    for it in funcs:
        kind, n = conv_args(it['conv'])
        out.append('align 16\n%s_asm2c:\n; %s (%s, %s)\n' % (it['c'], it['name'], it['conv'], it['dll']))
        if kind == 'std':
            out.append('        Call_Asm_Stack%d %s_c, %d\n\n' % (n, it['c'], n))
        elif kind == 'c':
            out.append('        Call_Asm_Stack%d %s_c\n\n' % (n, it['c']))
        elif kind == 'v':
            out.append('        Call_Asm_VariableStack%d %s_c\n\n' % (n, it['c']))
        elif kind == 'f1f':
            out.append('        Call_Asm_Float1_Float %s_c\n\n' % it['c'])
        elif kind == 'f2f':
            out.append('        Call_Asm_Float2_Float %s_c\n\n' % it['c'])
    open(os.path.join(base, 'x86', 'imports-asm.asm'), 'w').write(''.join(out))


X64_ARG_REGS = ['edi', 'esi', 'edx', 'ecx', 'r8d', 'r9d']

x64_header = '''%include "x64inc.inc"
%include "asm-calls.inc"

'''

x64_sections = '''
%ifidn __OUTPUT_FORMAT__, elf64
section .note.GNU-stack noalloc noexec nowrite progbits
section .text progbits alloc exec nowrite align=16
%else
section .text code align=16
%endif

'''

X64_WIN64_ARG_REGS = ['ecx', 'edx', 'r8d', 'r9d']


def x64_stub_win64(cfunc, nargs, pop, ret='', varargs=False):
    # Win64: game code runs inside a frame made by c_call_asm_n / the entry trampolines (asm_unwind.inc
    # SECTION_PROLOG): [rsp] = 4 free parameter slots (shadow space) for calls, [rsp+FIRST_PARAMETER_OFFSET] =
    # _stack*; rsi/rdi are preserved by C functions. Emulated x86 stack: [r11d] return address,
    # [r11d+4] first argument.
    regs_args = nargs + (1 if varargs else 0)
    stack_args = max(0, regs_args - 4)
    extra = (stack_args * 8 + 15) & ~15
    o = ['        mov r10, [rsp+FIRST_PARAMETER_OFFSET]\n        mov [r10], r11d\n']
    if extra:
        o.append('        sub rsp, %d\n' % extra)
    for i in range(4, regs_args):
        if varargs and i == nargs:
            o.append('        lea eax, [r11d+%d]\n' % ((1 + nargs) * 4))
        else:
            o.append('        mov eax, [r11d+%d]\n' % ((1 + i) * 4))
        o.append('        mov [rsp+%d], rax\n' % (32 + (i - 4) * 8))
    for i in range(min(4, regs_args)):
        if varargs and i == nargs:
            o.append('        lea %s, [r11d+%d]\n' % (X64_WIN64_ARG_REGS[i], (1 + nargs) * 4))
        else:
            o.append('        mov %s, [r11d+%d]\n' % (X64_WIN64_ARG_REGS[i], (1 + i) * 4))
    o.append('        call %s\n' % cfunc)
    if extra:
        o.append('        add rsp, %d\n' % extra)
    if ret == 'fret':
        o.append('        movsd [rsp], xmm0\n        fld qword [rsp]\n')
    elif ret == 'u64':
        o.append('        mov rdx, rax\n        shr rdx, 32\n        mov eax, eax\n')
    o.append('        mov r10, [rsp+FIRST_PARAMETER_OFFSET]\n        mov r11d, [r10]\n'
             '        mov r8d, [r11d]\n        add r11d, byte 4+%d\n        jmp r8\n' % (pop * 4))
    return ''.join(o)


def x64_stub(label, cfunc, nargs, pop, ret='', varargs=False):
    return ('align 16\n%s:\n%%ifidn __OUTPUT_FORMAT__, win64\n' % label +
            x64_stub_win64(cfunc, nargs, pop, ret, varargs) + '%else\n' +
            x64_stub_sysv(cfunc, nargs, pop, ret, varargs) + '%endif\n\n')


def x64_stub_sysv(cfunc, nargs, pop, ret='', varargs=False):
    # emulated x86 stack after Call_Asm_Prologue_0: [r11d] esi, [r11d+4] edi, [r11d+8] return address,
    # [r11d+12] first argument; [rsp] = _stack* and rsp is 16-byte aligned
    regs_args = nargs + (1 if varargs else 0)
    stack_args = max(0, regs_args - 6)
    pad = (stack_args * 8 + 15) & ~15
    o = ['        Call_Asm_Prologue_0\n']
    if pad:
        o.append('        sub rsp, %d\n' % pad)
    for i in range(6, regs_args):
        if varargs and i == nargs:
            o.append('        lea eax, [r11d+%d]\n' % ((3 + nargs) * 4))
        else:
            o.append('        mov eax, [r11d+%d]\n' % ((3 + i) * 4))
        o.append('        mov [rsp+%d], rax\n' % ((i - 6) * 8))
    for i in range(min(6, regs_args)):
        if varargs and i == nargs:
            o.append('        lea %s, [r11d+%d]\n' % (X64_ARG_REGS[i], (3 + nargs) * 4))
        else:
            o.append('        mov %s, [r11d+%d]\n' % (X64_ARG_REGS[i], (3 + i) * 4))
    o.append('        call %s\n' % cfunc)
    if pad:
        o.append('        add rsp, %d\n' % pad)
    if ret == 'fret':
        o.append('        movsd [rsp-8], xmm0\n        fld qword [rsp-8]\n')
    elif ret == 'u64':
        o.append('        mov rdx, rax\n        shr rdx, 32\n        mov eax, eax\n')
    o.append('        Call_Asm_Epilogue_0 %d\n' % pop)
    return ''.join(o)


def write_imports_asm_x64(items):
    out = [header_asm, x64_header]
    funcs = [it for it in items if conv_args(it['conv'])[0] in ('std', 'c', 'v', 'f1f', 'f2f')]
    for it in funcs:
        out.append('extern %s_c\n' % it['c'])
    out.append('\n')
    for it in funcs:
        out.append('global %s_asm2c\n' % it['c'])
    out.append(x64_sections)
    for it in funcs:
        kind, n = conv_args(it['conv'])
        label = '%s_asm2c' % it['c']
        out.append('; %s (%s, %s)\n' % (it['name'], it['conv'], it['dll']))
        if kind == 'f1f':
            out.append('align 16\n%s:\n        Call_Asm_Float1_Float %s_c\n\n' % (label, it['c']))
        elif kind == 'f2f':
            out.append('align 16\n%s:\n        Call_Asm_Float2_Float %s_c\n\n' % (label, it['c']))
        else:
            out.append(x64_stub(label, it['c'] + '_c', n, n if kind == 'std' else 0,
                                it['flags'] if it['flags'] in ('fret', 'u64') else '', kind == 'v'))
    open(os.path.join(base, 'x64', 'imports-asm.asm'), 'w').write(''.join(out))


def implemented_c_functions():
    # names of the <name>_c functions defined in the runtime's C files: stubs are only generated for the others
    # (weak symbols don't work reliably with PE/COFF, so the stubs are ordinary definitions)
    names = set()
    for fn in glob.glob(os.path.join(base, '*.c')):
        if os.path.basename(fn) in ('imports-stubs.c', 'com-stubs.c'):
            continue
        text = open(fn, encoding='latin-1').read()
        for m in re.finditer(r'CCALL\s+(\w+_c)\s*\(', text):
            depth, i = 1, m.end()
            while i < len(text) and depth:
                depth += {'(': 1, ')': -1}.get(text[i], 0)
                i += 1
            rest = text[i:i + 200].lstrip()
            if rest.startswith('{'):
                names.add(m.group(1))
    return names


def write_stubs_c(items):
    out = ['''/* generated by gen_imports.py from imports.spec - do not edit */

#include <stdint.h>
#include <stdio.h>
#include "platform.h"

EXTERN_C_BEGIN

static void unimplemented(const char *name, int *reported)
{
    if (!*reported)
    {
        *reported = 1;
        fprintf(stderr, "unimplemented import: %s\\n", name);
    }
}

''']
    implemented = implemented_c_functions()
    for it in items:
        kind, n = conv_args(it['conv'])
        c = it['c']
        ret = 'double' if it['flags'] == 'fret' else 'uint32_t'
        if kind in ('std', 'c'):
            args = ', '.join('uint32_t a%d' % i for i in range(n)) or 'void'
        elif kind == 'v':
            args = ', '.join(['uint32_t a%d' % i for i in range(n)] + ['uint32_t *ap'])
        elif kind in ('f1f', 'f2f'):
            args = 'double *args'
            ret = 'void'
        else:
            continue
        body = 'unimplemented("%s", &reported);' % it['name'].replace('\\', '\\\\')
        if ret != 'void':
            body += ' return 0;'
        # stdcall/cdecl only matters for the asm2c stub, the C side is always called as cdecl
        if c + '_c' in implemented:
            continue
        out.append('%s CCALL %s_c(%s) { static int reported; %s }\n' % (ret, c, args, body))
    out.append('\nEXTERN_C_END\n')
    open(os.path.join(base, 'imports-stubs.c'), 'w').write(''.join(out))


def load_com():
    ifaces = []
    for line in open(os.path.join(base, 'com.spec')):
        line = line.split('#', 1)[0].strip()
        if not line:
            continue
        f = line.split()
        if f[0] == 'interface':
            ifaces.append((f[1], []))
        else:
            ifaces[-1][1].append((f[0], int(f[1])))
    return ifaces


def write_com(ifaces):
    out = [header_asm, '%include "asm-calls.inc"\n\n']
    for iface, methods in ifaces:
        for m, n in methods:
            out.append('extern %s_%s_c\n' % (iface, m))
    for iface, methods in ifaces:
        out.append('global %sVtbl_asm2c\n' % iface)
    out.append('''
%ifidn __OUTPUT_FORMAT__, elf32
section .note.GNU-stack noalloc noexec nowrite progbits
section .text progbits alloc exec nowrite align=16
%else
section .text code align=16
%endif

''')
    for iface, methods in ifaces:
        for m, n in methods:
            out.append('align 16\n%s_%s_asm2c:\n        Call_Asm_Stack%d %s_%s_c, %d\n\n' % (iface, m, n, iface, m, n))
    out.append('''
%ifidn __OUTPUT_FORMAT__, elf32
section .rodata progbits alloc noexec nowrite align=4
%else
section .rdata rdata align=4
%endif

''')
    for iface, methods in ifaces:
        out.append('%sVtbl_asm2c:\n' % iface)
        for m, n in methods:
            out.append('        dd %s_%s_asm2c\n' % (iface, m))
        out.append('\n')
    open(os.path.join(base, 'x86', 'com-asm.asm'), 'w').write(''.join(out))

    out = [header_asm, x64_header]
    for iface, methods in ifaces:
        for m, n in methods:
            out.append('extern %s_%s_c\n' % (iface, m))
    for iface, methods in ifaces:
        out.append('global %sVtbl_asm2c\n' % iface)
    out.append(x64_sections)
    for iface, methods in ifaces:
        for m, n in methods:
            out.append(x64_stub('%s_%s_asm2c' % (iface, m), '%s_%s_c' % (iface, m), n, n))
    out.append('''
section .rodata progbits alloc noexec nowrite align=4

''')
    for iface, methods in ifaces:
        out.append('%sVtbl_asm2c:\n' % iface)
        for m, n in methods:
            out.append('        dd %s_%s_asm2c\n' % (iface, m))
        out.append('\n')
    open(os.path.join(base, 'x64', 'com-asm.asm'), 'w').write(''.join(out))

    c = ['''/* generated by gen_imports.py from com.spec - do not edit */

#include <stdint.h>
#include <stdio.h>
#include "platform.h"

EXTERN_C_BEGIN

#define E_NOTIMPL 0x80004001

''']
    implemented = implemented_c_functions()
    for iface, methods in ifaces:
        for m, n in methods:
            args = ', '.join('uint32_t a%d' % i for i in range(n))
            if '%s_%s_c' % (iface, m) in implemented:
                continue
            c.append('uint32_t CCALL %s_%s_c(%s) { static int reported; if (!reported) { reported = 1; fprintf(stderr, "unimplemented COM method: %s::%s\\n"); } return E_NOTIMPL; }\n' % (iface, m, args, iface, m))
    c.append('\nEXTERN_C_END\n')
    open(os.path.join(base, 'com-stubs.c'), 'w').write(''.join(c))
    return sum(len(m) for i, m in ifaces)


items = load_spec()
write_extern_inc(items)
write_imports_asm(items)
write_imports_asm_x64(items)
write_stubs_c(items)
print('%d imports, %d COM methods' % (len(items), write_com(load_com())))
