/* generated by gen_imports.py from imports.spec - do not edit */

#include <stdint.h>
#include <stdio.h>
#include "platform.h"

EXTERN_C_BEGIN

static void unimplemented(const char *name, int *reported)
{
    if (!*reported)
    {
        *reported = 1;
        fprintf(stderr, "unimplemented import: %s\n", name);
    }
}

uint32_t CCALL CreateProcessA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6, uint32_t a7, uint32_t a8, uint32_t a9) { static int reported; unimplemented("CreateProcessA", &reported); return 0; }
uint32_t CCALL CreateThread_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("CreateThread", &reported); return 0; }
uint32_t CCALL GetLocaleInfoA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("GetLocaleInfoA", &reported); return 0; }
uint32_t CCALL GetLocaleInfoW_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("GetLocaleInfoW", &reported); return 0; }
uint32_t CCALL GetStringTypeA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("GetStringTypeA", &reported); return 0; }
uint32_t CCALL GetStringTypeW_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("GetStringTypeW", &reported); return 0; }
uint32_t CCALL LCMapStringA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("LCMapStringA", &reported); return 0; }
uint32_t CCALL LCMapStringW_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("LCMapStringW", &reported); return 0; }
uint32_t CCALL LoadModule_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("LoadModule", &reported); return 0; }

EXTERN_C_END
