/* generated by gen_imports.py from imports.spec - do not edit */

#include <stdint.h>
#include <stdio.h>
#include "platform.h"

static void unimplemented(const char *name, int *reported)
{
    if (!*reported)
    {
        *reported = 1;
        fprintf(stderr, "unimplemented import: %s\n", name);
    }
}

#define WEAK __attribute__((weak))

WEAK uint32_t CCALL operator_new_c(uint32_t a0) { static int reported; unimplemented("??2@YAPAXI@Z", &reported); return 0; }
WEAK uint32_t CCALL operator_delete_c(uint32_t a0) { static int reported; unimplemented("??3@YAXPAX@Z", &reported); return 0; }
WEAK uint32_t CCALL _access_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("_access", &reported); return 0; }
WEAK uint32_t CCALL _assert_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_assert", &reported); return 0; }
WEAK void CCALL _CIacos_c(double *args) { static int reported; unimplemented("_CIacos", &reported); }
WEAK void CCALL _CIasin_c(double *args) { static int reported; unimplemented("_CIasin", &reported); }
WEAK void CCALL _CIatan2_c(double *args) { static int reported; unimplemented("_CIatan2", &reported); }
WEAK void CCALL _CIfmod_c(double *args) { static int reported; unimplemented("_CIfmod", &reported); }
WEAK void CCALL _CIpow_c(double *args) { static int reported; unimplemented("_CIpow", &reported); }
WEAK uint32_t CCALL _close_c(uint32_t a0) { static int reported; unimplemented("_close", &reported); return 0; }
WEAK uint32_t CCALL _errno_c(void) { static int reported; unimplemented("_errno", &reported); return 0; }
WEAK uint32_t CCALL _findclose_c(uint32_t a0) { static int reported; unimplemented("_findclose", &reported); return 0; }
WEAK uint32_t CCALL _findfirst_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("_findfirst", &reported); return 0; }
WEAK uint32_t CCALL _findnext_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("_findnext", &reported); return 0; }
WEAK uint32_t CCALL grAlphaBlendFunction_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("_grAlphaBlendFunction@16", &reported); return 0; }
WEAK uint32_t CCALL grAlphaCombine_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("_grAlphaCombine@20", &reported); return 0; }
WEAK uint32_t CCALL grBufferClear_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_grBufferClear@12", &reported); return 0; }
WEAK uint32_t CCALL grBufferSwap_c(uint32_t a0) { static int reported; unimplemented("_grBufferSwap@4", &reported); return 0; }
WEAK uint32_t CCALL grChromakeyMode_c(uint32_t a0) { static int reported; unimplemented("_grChromakeyMode@4", &reported); return 0; }
WEAK uint32_t CCALL grChromakeyValue_c(uint32_t a0) { static int reported; unimplemented("_grChromakeyValue@4", &reported); return 0; }
WEAK uint32_t CCALL grColorCombine_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("_grColorCombine@20", &reported); return 0; }
WEAK uint32_t CCALL grConstantColorValue_c(uint32_t a0) { static int reported; unimplemented("_grConstantColorValue@4", &reported); return 0; }
WEAK uint32_t CCALL grCullMode_c(uint32_t a0) { static int reported; unimplemented("_grCullMode@4", &reported); return 0; }
WEAK uint32_t CCALL grDepthBufferFunction_c(uint32_t a0) { static int reported; unimplemented("_grDepthBufferFunction@4", &reported); return 0; }
WEAK uint32_t CCALL grDepthBufferMode_c(uint32_t a0) { static int reported; unimplemented("_grDepthBufferMode@4", &reported); return 0; }
WEAK uint32_t CCALL grDepthMask_c(uint32_t a0) { static int reported; unimplemented("_grDepthMask@4", &reported); return 0; }
WEAK uint32_t CCALL grDrawLine_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("_grDrawLine@8", &reported); return 0; }
WEAK uint32_t CCALL grDrawPoint_c(uint32_t a0) { static int reported; unimplemented("_grDrawPoint@4", &reported); return 0; }
WEAK uint32_t CCALL grDrawTriangle_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_grDrawTriangle@12", &reported); return 0; }
WEAK uint32_t CCALL grFogColorValue_c(uint32_t a0) { static int reported; unimplemented("_grFogColorValue@4", &reported); return 0; }
WEAK uint32_t CCALL grFogMode_c(uint32_t a0) { static int reported; unimplemented("_grFogMode@4", &reported); return 0; }
WEAK uint32_t CCALL grGlideGetState_c(uint32_t a0) { static int reported; unimplemented("_grGlideGetState@4", &reported); return 0; }
WEAK uint32_t CCALL grGlideInit_c(void) { static int reported; unimplemented("_grGlideInit@0", &reported); return 0; }
WEAK uint32_t CCALL grGlideSetState_c(uint32_t a0) { static int reported; unimplemented("_grGlideSetState@4", &reported); return 0; }
WEAK uint32_t CCALL grGlideShutdown_c(void) { static int reported; unimplemented("_grGlideShutdown@0", &reported); return 0; }
WEAK uint32_t CCALL grLfbLock_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("_grLfbLock@24", &reported); return 0; }
WEAK uint32_t CCALL grLfbUnlock_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("_grLfbUnlock@8", &reported); return 0; }
WEAK uint32_t CCALL grRenderBuffer_c(uint32_t a0) { static int reported; unimplemented("_grRenderBuffer@4", &reported); return 0; }
WEAK uint32_t CCALL grSstQueryBoards_c(uint32_t a0) { static int reported; unimplemented("_grSstQueryBoards@4", &reported); return 0; }
WEAK uint32_t CCALL grSstQueryHardware_c(uint32_t a0) { static int reported; unimplemented("_grSstQueryHardware@4", &reported); return 0; }
WEAK uint32_t CCALL grSstSelect_c(uint32_t a0) { static int reported; unimplemented("_grSstSelect@4", &reported); return 0; }
WEAK uint32_t CCALL grSstWinClose_c(void) { static int reported; unimplemented("_grSstWinClose@0", &reported); return 0; }
WEAK uint32_t CCALL grSstWinOpen_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6) { static int reported; unimplemented("_grSstWinOpen@28", &reported); return 0; }
WEAK uint32_t CCALL grTexCalcMemRequired_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("_grTexCalcMemRequired@16", &reported); return 0; }
WEAK uint32_t CCALL grTexClampMode_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_grTexClampMode@12", &reported); return 0; }
WEAK uint32_t CCALL grTexCombine_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6) { static int reported; unimplemented("_grTexCombine@28", &reported); return 0; }
WEAK uint32_t CCALL grTexDownloadMipMap_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("_grTexDownloadMipMap@16", &reported); return 0; }
WEAK uint32_t CCALL grTexDownloadTable_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_grTexDownloadTable@12", &reported); return 0; }
WEAK uint32_t CCALL grTexFilterMode_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_grTexFilterMode@12", &reported); return 0; }
WEAK uint32_t CCALL grTexMaxAddress_c(uint32_t a0) { static int reported; unimplemented("_grTexMaxAddress@4", &reported); return 0; }
WEAK uint32_t CCALL grTexMinAddress_c(uint32_t a0) { static int reported; unimplemented("_grTexMinAddress@4", &reported); return 0; }
WEAK uint32_t CCALL grTexMipMapMode_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_grTexMipMapMode@12", &reported); return 0; }
WEAK uint32_t CCALL grTexSource_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("_grTexSource@16", &reported); return 0; }
WEAK uint32_t CCALL _isctype_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("_isctype", &reported); return 0; }
WEAK uint32_t CCALL _ismbcalnum_c(uint32_t a0) { static int reported; unimplemented("_ismbcalnum", &reported); return 0; }
WEAK uint32_t CCALL _ismbcpunct_c(uint32_t a0) { static int reported; unimplemented("_ismbcpunct", &reported); return 0; }
WEAK uint32_t CCALL _ismbcspace_c(uint32_t a0) { static int reported; unimplemented("_ismbcspace", &reported); return 0; }
WEAK uint32_t CCALL _isnan_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("_isnan", &reported); return 0; }
WEAK uint32_t CCALL _itoa_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_itoa", &reported); return 0; }
WEAK uint32_t CCALL _lseek_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_lseek", &reported); return 0; }
WEAK uint32_t CCALL _mbsicmp_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("_mbsicmp", &reported); return 0; }
WEAK uint32_t CCALL _mbsnbcat_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_mbsnbcat", &reported); return 0; }
WEAK uint32_t CCALL _mbsnbcpy_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_mbsnbcpy", &reported); return 0; }
WEAK uint32_t CCALL _mbsnbicmp_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_mbsnbicmp", &reported); return 0; }
WEAK uint32_t CCALL _mkdir_c(uint32_t a0) { static int reported; unimplemented("_mkdir", &reported); return 0; }
WEAK uint32_t CCALL _msize_c(uint32_t a0) { static int reported; unimplemented("_msize", &reported); return 0; }
WEAK uint32_t CCALL _open_c(uint32_t a0, uint32_t a1, uint32_t *ap) { static int reported; unimplemented("_open", &reported); return 0; }
WEAK uint32_t CCALL _putch_c(uint32_t a0) { static int reported; unimplemented("_putch", &reported); return 0; }
WEAK uint32_t CCALL _read_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_read", &reported); return 0; }
WEAK uint32_t CCALL _splitpath_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("_splitpath", &reported); return 0; }
WEAK uint32_t CCALL _stat_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("_stat", &reported); return 0; }
WEAK uint32_t CCALL _stricmp_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("_stricmp", &reported); return 0; }
WEAK uint32_t CCALL _strlwr_c(uint32_t a0) { static int reported; unimplemented("_strlwr", &reported); return 0; }
WEAK uint32_t CCALL _strnicmp_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("_strnicmp", &reported); return 0; }
WEAK uint32_t CCALL _unlink_c(uint32_t a0) { static int reported; unimplemented("_unlink", &reported); return 0; }
WEAK uint32_t CCALL _vsnprintf_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("_vsnprintf", &reported); return 0; }
WEAK uint32_t CCALL abort_c(void) { static int reported; unimplemented("abort", &reported); return 0; }
WEAK uint32_t CCALL AddFontResourceA_c(uint32_t a0) { static int reported; unimplemented("AddFontResourceA", &reported); return 0; }
WEAK uint32_t CCALL AdjustWindowRect_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("AdjustWindowRect", &reported); return 0; }
WEAK uint32_t CCALL atoi_c(uint32_t a0) { static int reported; unimplemented("atoi", &reported); return 0; }
WEAK uint32_t CCALL atol_c(uint32_t a0) { static int reported; unimplemented("atol", &reported); return 0; }
WEAK uint32_t CCALL auxGetDevCapsA_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("auxGetDevCapsA", &reported); return 0; }
WEAK uint32_t CCALL auxGetNumDevs_c(void) { static int reported; unimplemented("auxGetNumDevs", &reported); return 0; }
WEAK uint32_t CCALL auxSetVolume_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("auxSetVolume", &reported); return 0; }
WEAK uint32_t CCALL BeginPaint_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("BeginPaint", &reported); return 0; }
WEAK uint32_t CCALL BitBlt_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6, uint32_t a7, uint32_t a8) { static int reported; unimplemented("BitBlt", &reported); return 0; }
WEAK uint32_t CCALL bsearch_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("bsearch", &reported); return 0; }
WEAK uint32_t CCALL calloc_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("calloc", &reported); return 0; }
WEAK uint32_t CCALL ClientToScreen_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("ClientToScreen", &reported); return 0; }
WEAK uint32_t CCALL ClipCursor_c(uint32_t a0) { static int reported; unimplemented("ClipCursor", &reported); return 0; }
WEAK uint32_t CCALL clock_c(void) { static int reported; unimplemented("clock", &reported); return 0; }
WEAK uint32_t CCALL CloseHandle_c(uint32_t a0) { static int reported; unimplemented("CloseHandle", &reported); return 0; }
WEAK uint32_t CCALL CoInitialize_c(uint32_t a0) { static int reported; unimplemented("CoInitialize", &reported); return 0; }
WEAK uint32_t CCALL CopyFileA_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("CopyFileA", &reported); return 0; }
WEAK uint32_t CCALL CoUninitialize_c(void) { static int reported; unimplemented("CoUninitialize", &reported); return 0; }
WEAK uint32_t CCALL CreateCompatibleDC_c(uint32_t a0) { static int reported; unimplemented("CreateCompatibleDC", &reported); return 0; }
WEAK uint32_t CCALL CreateDIBSection_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("CreateDIBSection", &reported); return 0; }
WEAK uint32_t CCALL CreateFileA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6) { static int reported; unimplemented("CreateFileA", &reported); return 0; }
WEAK uint32_t CCALL CreateFileMappingA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("CreateFileMappingA", &reported); return 0; }
WEAK uint32_t CCALL CreateFontIndirectA_c(uint32_t a0) { static int reported; unimplemented("CreateFontIndirectA", &reported); return 0; }
WEAK uint32_t CCALL CreatePalette_c(uint32_t a0) { static int reported; unimplemented("CreatePalette", &reported); return 0; }
WEAK uint32_t CCALL CreateProcessA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6, uint32_t a7, uint32_t a8, uint32_t a9) { static int reported; unimplemented("CreateProcessA", &reported); return 0; }
WEAK uint32_t CCALL CreateScalableFontResourceA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("CreateScalableFontResourceA", &reported); return 0; }
WEAK uint32_t CCALL CreateThread_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("CreateThread", &reported); return 0; }
WEAK uint32_t CCALL CreateWindowExA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6, uint32_t a7, uint32_t a8, uint32_t a9, uint32_t a10, uint32_t a11) { static int reported; unimplemented("CreateWindowExA", &reported); return 0; }
WEAK uint32_t CCALL DefWindowProcA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("DefWindowProcA", &reported); return 0; }
WEAK uint32_t CCALL DeleteCriticalSection_c(uint32_t a0) { static int reported; unimplemented("DeleteCriticalSection", &reported); return 0; }
WEAK uint32_t CCALL DeleteDC_c(uint32_t a0) { static int reported; unimplemented("DeleteDC", &reported); return 0; }
WEAK uint32_t CCALL DeleteFileA_c(uint32_t a0) { static int reported; unimplemented("DeleteFileA", &reported); return 0; }
WEAK uint32_t CCALL DeleteObject_c(uint32_t a0) { static int reported; unimplemented("DeleteObject", &reported); return 0; }
WEAK uint32_t CCALL DestroyWindow_c(uint32_t a0) { static int reported; unimplemented("DestroyWindow", &reported); return 0; }
WEAK uint32_t CCALL DialogBoxParamA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("DialogBoxParamA", &reported); return 0; }
WEAK double CCALL difftime_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("difftime", &reported); return 0; }
WEAK uint32_t CCALL DirectDrawCreate_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("DirectDrawCreate", &reported); return 0; }
WEAK uint32_t CCALL DirectDrawEnumerateA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("DirectDrawEnumerateA", &reported); return 0; }
WEAK uint32_t CCALL DirectSoundCreate_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("DirectSoundCreate", &reported); return 0; }
WEAK uint32_t CCALL DispatchMessageA_c(uint32_t a0) { static int reported; unimplemented("DispatchMessageA", &reported); return 0; }
WEAK uint32_t CCALL msvcrt_div_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("msvcrt_div", &reported); return 0; }
WEAK uint32_t CCALL dp_enableDebugPrint_c(uint32_t a0) { static int reported; unimplemented("dp_enableDebugPrint", &reported); return 0; }
WEAK uint32_t CCALL dpAddPlayerToGroup_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("dpAddPlayerToGroup", &reported); return 0; }
WEAK uint32_t CCALL dpClose_c(uint32_t a0) { static int reported; unimplemented("dpClose", &reported); return 0; }
WEAK uint32_t CCALL dpCreate_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("dpCreate", &reported); return 0; }
WEAK uint32_t CCALL dpCreateGroup_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("dpCreateGroup", &reported); return 0; }
WEAK uint32_t CCALL dpCreatePlayer_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("dpCreatePlayer", &reported); return 0; }
WEAK uint32_t CCALL dpDestroy_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("dpDestroy", &reported); return 0; }
WEAK uint32_t CCALL dpDestroyPlayer_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("dpDestroyPlayer", &reported); return 0; }
WEAK uint32_t CCALL dpEnumGroupPlayers_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("dpEnumGroupPlayers", &reported); return 0; }
WEAK uint32_t CCALL dpEnumGroups_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("dpEnumGroups", &reported); return 0; }
WEAK uint32_t CCALL dpEnumPlayers_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("dpEnumPlayers", &reported); return 0; }
WEAK uint32_t CCALL dpEnumSessions_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("dpEnumSessions", &reported); return 0; }
WEAK uint32_t CCALL dpFreeze_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("dpFreeze", &reported); return 0; }
WEAK uint32_t CCALL dpEnumTransports_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("dpEnumTransports", &reported); return 0; }
WEAK uint32_t CCALL dpGetPlayerData_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("dpGetPlayerData", &reported); return 0; }
WEAK uint32_t CCALL dpGetPlayerName_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("dpGetPlayerName", &reported); return 0; }
WEAK uint32_t CCALL dpGetSessionDesc_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("dpGetSessionDesc", &reported); return 0; }
WEAK uint32_t CCALL dpOpen_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("dpOpen", &reported); return 0; }
WEAK uint32_t CCALL dpReceive_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("dpReceive", &reported); return 0; }
WEAK uint32_t CCALL dpSend_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("dpSend", &reported); return 0; }
WEAK uint32_t CCALL dpSetGameServer_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("dpSetGameServer", &reported); return 0; }
WEAK uint32_t CCALL dpSetPlayerData_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("dpSetPlayerData", &reported); return 0; }
WEAK uint32_t CCALL EndDialog_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("EndDialog", &reported); return 0; }
WEAK uint32_t CCALL EndPaint_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("EndPaint", &reported); return 0; }
WEAK uint32_t CCALL EnterCriticalSection_c(uint32_t a0) { static int reported; unimplemented("EnterCriticalSection", &reported); return 0; }
WEAK uint32_t CCALL exit_c(uint32_t a0) { static int reported; unimplemented("exit", &reported); return 0; }
WEAK uint32_t CCALL ExitProcess_c(uint32_t a0) { static int reported; unimplemented("ExitProcess", &reported); return 0; }
WEAK uint32_t CCALL fclose_c(uint32_t a0) { static int reported; unimplemented("fclose", &reported); return 0; }
WEAK uint32_t CCALL fflush_c(uint32_t a0) { static int reported; unimplemented("fflush", &reported); return 0; }
WEAK uint32_t CCALL fgetc_c(uint32_t a0) { static int reported; unimplemented("fgetc", &reported); return 0; }
WEAK uint32_t CCALL fgets_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("fgets", &reported); return 0; }
WEAK uint32_t CCALL FindClose_c(uint32_t a0) { static int reported; unimplemented("FindClose", &reported); return 0; }
WEAK uint32_t CCALL FindFirstFileA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("FindFirstFileA", &reported); return 0; }
WEAK uint32_t CCALL FindNextFileA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("FindNextFileA", &reported); return 0; }
WEAK uint32_t CCALL FindWindowA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("FindWindowA", &reported); return 0; }
WEAK double CCALL floor_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("floor", &reported); return 0; }
WEAK uint32_t CCALL FlushFileBuffers_c(uint32_t a0) { static int reported; unimplemented("FlushFileBuffers", &reported); return 0; }
WEAK uint32_t CCALL fopen_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("fopen", &reported); return 0; }
WEAK uint32_t CCALL fprintf_c(uint32_t a0, uint32_t a1, uint32_t *ap) { static int reported; unimplemented("fprintf", &reported); return 0; }
WEAK uint32_t CCALL fputc_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("fputc", &reported); return 0; }
WEAK uint32_t CCALL fputs_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("fputs", &reported); return 0; }
WEAK uint32_t CCALL fread_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("fread", &reported); return 0; }
WEAK uint32_t CCALL free_c(uint32_t a0) { static int reported; unimplemented("free", &reported); return 0; }
WEAK uint32_t CCALL FreeLibrary_c(uint32_t a0) { static int reported; unimplemented("FreeLibrary", &reported); return 0; }
WEAK uint32_t CCALL fscanf_c(uint32_t a0, uint32_t a1, uint32_t *ap) { static int reported; unimplemented("fscanf", &reported); return 0; }
WEAK uint32_t CCALL fseek_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("fseek", &reported); return 0; }
WEAK uint32_t CCALL ftell_c(uint32_t a0) { static int reported; unimplemented("ftell", &reported); return 0; }
WEAK uint32_t CCALL fwrite_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("fwrite", &reported); return 0; }
WEAK uint32_t CCALL GdiFlush_c(void) { static int reported; unimplemented("GdiFlush", &reported); return 0; }
WEAK uint32_t CCALL GetAsyncKeyState_c(uint32_t a0) { static int reported; unimplemented("GetAsyncKeyState", &reported); return 0; }
WEAK uint32_t CCALL getc_c(uint32_t a0) { static int reported; unimplemented("getc", &reported); return 0; }
WEAK uint32_t CCALL GetClientRect_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("GetClientRect", &reported); return 0; }
WEAK uint32_t CCALL GetCPInfo_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("GetCPInfo", &reported); return 0; }
WEAK uint32_t CCALL GetCurrentDirectoryA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("GetCurrentDirectoryA", &reported); return 0; }
WEAK uint32_t CCALL GetCurrentProcess_c(void) { static int reported; unimplemented("GetCurrentProcess", &reported); return 0; }
WEAK uint32_t CCALL GetCurrentThreadId_c(void) { static int reported; unimplemented("GetCurrentThreadId", &reported); return 0; }
WEAK uint32_t CCALL GetCursorPos_c(uint32_t a0) { static int reported; unimplemented("GetCursorPos", &reported); return 0; }
WEAK uint32_t CCALL GetDC_c(uint32_t a0) { static int reported; unimplemented("GetDC", &reported); return 0; }
WEAK uint32_t CCALL GetDeviceCaps_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("GetDeviceCaps", &reported); return 0; }
WEAK uint32_t CCALL GetDlgItem_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("GetDlgItem", &reported); return 0; }
WEAK uint32_t CCALL GetDlgItemTextA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("GetDlgItemTextA", &reported); return 0; }
WEAK uint32_t CCALL GetDriveTypeA_c(uint32_t a0) { static int reported; unimplemented("GetDriveTypeA", &reported); return 0; }
WEAK uint32_t CCALL GetFileTime_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("GetFileTime", &reported); return 0; }
WEAK uint32_t CCALL GetFileType_c(uint32_t a0) { static int reported; unimplemented("GetFileType", &reported); return 0; }
WEAK uint32_t CCALL GetFocus_c(void) { static int reported; unimplemented("GetFocus", &reported); return 0; }
WEAK uint32_t CCALL GetKeyboardType_c(uint32_t a0) { static int reported; unimplemented("GetKeyboardType", &reported); return 0; }
WEAK uint32_t CCALL GetKeyState_c(uint32_t a0) { static int reported; unimplemented("GetKeyState", &reported); return 0; }
WEAK uint32_t CCALL GetLastError_c(void) { static int reported; unimplemented("GetLastError", &reported); return 0; }
WEAK uint32_t CCALL GetLocaleInfoA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("GetLocaleInfoA", &reported); return 0; }
WEAK uint32_t CCALL GetLocaleInfoW_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("GetLocaleInfoW", &reported); return 0; }
WEAK uint32_t CCALL GetLogicalDrives_c(void) { static int reported; unimplemented("GetLogicalDrives", &reported); return 0; }
WEAK uint32_t CCALL GetLogicalDriveStringsA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("GetLogicalDriveStringsA", &reported); return 0; }
WEAK uint32_t CCALL GetModuleFileNameA_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("GetModuleFileNameA", &reported); return 0; }
WEAK uint32_t CCALL GetModuleHandleA_c(uint32_t a0) { static int reported; unimplemented("GetModuleHandleA", &reported); return 0; }
WEAK uint32_t CCALL GetProcAddress_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("GetProcAddress", &reported); return 0; }
WEAK uint32_t CCALL GetProcessHeap_c(void) { static int reported; unimplemented("GetProcessHeap", &reported); return 0; }
WEAK uint32_t CCALL GetStdHandle_c(uint32_t a0) { static int reported; unimplemented("GetStdHandle", &reported); return 0; }
WEAK uint32_t CCALL GetStockObject_c(uint32_t a0) { static int reported; unimplemented("GetStockObject", &reported); return 0; }
WEAK uint32_t CCALL GetStringTypeA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("GetStringTypeA", &reported); return 0; }
WEAK uint32_t CCALL GetStringTypeW_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("GetStringTypeW", &reported); return 0; }
WEAK uint32_t CCALL GetSystemDefaultLCID_c(void) { static int reported; unimplemented("GetSystemDefaultLCID", &reported); return 0; }
WEAK uint32_t CCALL GetSystemInfo_c(uint32_t a0) { static int reported; unimplemented("GetSystemInfo", &reported); return 0; }
WEAK uint32_t CCALL GetSystemMetrics_c(uint32_t a0) { static int reported; unimplemented("GetSystemMetrics", &reported); return 0; }
WEAK uint32_t CCALL GetSystemPaletteEntries_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("GetSystemPaletteEntries", &reported); return 0; }
WEAK uint32_t CCALL GetTextExtentExPointA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6) { static int reported; unimplemented("GetTextExtentExPointA", &reported); return 0; }
WEAK uint32_t CCALL GetTextExtentPoint32A_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("GetTextExtentPoint32A", &reported); return 0; }
WEAK uint32_t CCALL GetTickCount_c(void) { static int reported; unimplemented("GetTickCount", &reported); return 0; }
WEAK uint32_t CCALL GetVolumeInformationA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6, uint32_t a7) { static int reported; unimplemented("GetVolumeInformationA", &reported); return 0; }
WEAK uint32_t CCALL GetWindowLongA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("GetWindowLongA", &reported); return 0; }
WEAK uint32_t CCALL GetWindowRect_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("GetWindowRect", &reported); return 0; }
WEAK uint32_t CCALL GetWindowsDirectoryA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("GetWindowsDirectoryA", &reported); return 0; }
WEAK uint32_t CCALL HeapAlloc_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("HeapAlloc", &reported); return 0; }
WEAK uint32_t CCALL HeapCompact_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("HeapCompact", &reported); return 0; }
WEAK uint32_t CCALL HeapCreate_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("HeapCreate", &reported); return 0; }
WEAK uint32_t CCALL HeapDestroy_c(uint32_t a0) { static int reported; unimplemented("HeapDestroy", &reported); return 0; }
WEAK uint32_t CCALL HeapFree_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("HeapFree", &reported); return 0; }
WEAK uint32_t CCALL HeapReAlloc_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("HeapReAlloc", &reported); return 0; }
WEAK uint32_t CCALL HeapSize_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("HeapSize", &reported); return 0; }
WEAK uint32_t CCALL ImmAssociateContext_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("ImmAssociateContext", &reported); return 0; }
WEAK uint32_t CCALL InitializeCriticalSection_c(uint32_t a0) { static int reported; unimplemented("InitializeCriticalSection", &reported); return 0; }
WEAK uint32_t CCALL InterlockedDecrement_c(uint32_t a0) { static int reported; unimplemented("InterlockedDecrement", &reported); return 0; }
WEAK uint32_t CCALL InterlockedIncrement_c(uint32_t a0) { static int reported; unimplemented("InterlockedIncrement", &reported); return 0; }
WEAK uint32_t CCALL isspace_c(uint32_t a0) { static int reported; unimplemented("isspace", &reported); return 0; }
WEAK uint32_t CCALL joyGetDevCapsA_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("joyGetDevCapsA", &reported); return 0; }
WEAK uint32_t CCALL joyGetNumDevs_c(void) { static int reported; unimplemented("joyGetNumDevs", &reported); return 0; }
WEAK uint32_t CCALL joyGetPos_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("joyGetPos", &reported); return 0; }
WEAK uint32_t CCALL joyGetPosEx_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("joyGetPosEx", &reported); return 0; }
WEAK uint32_t CCALL LCMapStringA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("LCMapStringA", &reported); return 0; }
WEAK uint32_t CCALL LCMapStringW_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("LCMapStringW", &reported); return 0; }
WEAK uint32_t CCALL LeaveCriticalSection_c(uint32_t a0) { static int reported; unimplemented("LeaveCriticalSection", &reported); return 0; }
WEAK uint32_t CCALL LoadCursorA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("LoadCursorA", &reported); return 0; }
WEAK uint32_t CCALL LoadCursorFromFileA_c(uint32_t a0) { static int reported; unimplemented("LoadCursorFromFileA", &reported); return 0; }
WEAK uint32_t CCALL LoadLibraryA_c(uint32_t a0) { static int reported; unimplemented("LoadLibraryA", &reported); return 0; }
WEAK uint32_t CCALL LoadModule_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("LoadModule", &reported); return 0; }
WEAK uint32_t CCALL lstrcatA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("lstrcatA", &reported); return 0; }
WEAK uint32_t CCALL lstrcpyA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("lstrcpyA", &reported); return 0; }
WEAK uint32_t CCALL malloc_c(uint32_t a0) { static int reported; unimplemented("malloc", &reported); return 0; }
WEAK uint32_t CCALL MapViewOfFile_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("MapViewOfFile", &reported); return 0; }
WEAK uint32_t CCALL MapVirtualKeyA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("MapVirtualKeyA", &reported); return 0; }
WEAK uint32_t CCALL mciGetErrorStringA_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("mciGetErrorStringA", &reported); return 0; }
WEAK uint32_t CCALL mciSendCommandA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("mciSendCommandA", &reported); return 0; }
WEAK uint32_t CCALL memmove_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("memmove", &reported); return 0; }
WEAK uint32_t CCALL MessageBoxA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("MessageBoxA", &reported); return 0; }
WEAK uint32_t CCALL MultiByteToWideChar_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("MultiByteToWideChar", &reported); return 0; }
WEAK uint32_t CCALL OutputDebugStringA_c(uint32_t a0) { static int reported; unimplemented("OutputDebugStringA", &reported); return 0; }
WEAK uint32_t CCALL PeekMessageA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("PeekMessageA", &reported); return 0; }
WEAK uint32_t CCALL PostMessageA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("PostMessageA", &reported); return 0; }
WEAK uint32_t CCALL PostQuitMessage_c(uint32_t a0) { static int reported; unimplemented("PostQuitMessage", &reported); return 0; }
WEAK uint32_t CCALL qsort_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("qsort", &reported); return 0; }
WEAK uint32_t CCALL rand_c(void) { static int reported; unimplemented("rand", &reported); return 0; }
WEAK uint32_t CCALL ReadFile_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("ReadFile", &reported); return 0; }
WEAK uint32_t CCALL RealizePalette_c(uint32_t a0) { static int reported; unimplemented("RealizePalette", &reported); return 0; }
WEAK uint32_t CCALL realloc_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("realloc", &reported); return 0; }
WEAK uint32_t CCALL Rectangle_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("Rectangle", &reported); return 0; }
WEAK uint32_t CCALL RegCloseKey_c(uint32_t a0) { static int reported; unimplemented("RegCloseKey", &reported); return 0; }
WEAK uint32_t CCALL RegCreateKeyExA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6, uint32_t a7, uint32_t a8) { static int reported; unimplemented("RegCreateKeyExA", &reported); return 0; }
WEAK uint32_t CCALL RegisterClassA_c(uint32_t a0) { static int reported; unimplemented("RegisterClassA", &reported); return 0; }
WEAK uint32_t CCALL RegOpenKeyExA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("RegOpenKeyExA", &reported); return 0; }
WEAK uint32_t CCALL RegQueryValueExA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("RegQueryValueExA", &reported); return 0; }
WEAK uint32_t CCALL RegSetValueExA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("RegSetValueExA", &reported); return 0; }
WEAK uint32_t CCALL ReleaseDC_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("ReleaseDC", &reported); return 0; }
WEAK uint32_t CCALL RemoveFontResourceA_c(uint32_t a0) { static int reported; unimplemented("RemoveFontResourceA", &reported); return 0; }
WEAK uint32_t CCALL ScreenToClient_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("ScreenToClient", &reported); return 0; }
WEAK uint32_t CCALL SelectObject_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SelectObject", &reported); return 0; }
WEAK uint32_t CCALL SelectPalette_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("SelectPalette", &reported); return 0; }
WEAK uint32_t CCALL SendDlgItemMessageA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("SendDlgItemMessageA", &reported); return 0; }
WEAK uint32_t CCALL SendMessageA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("SendMessageA", &reported); return 0; }
WEAK uint32_t CCALL SetBkColor_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SetBkColor", &reported); return 0; }
WEAK uint32_t CCALL SetBkMode_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SetBkMode", &reported); return 0; }
WEAK uint32_t CCALL SetCursor_c(uint32_t a0) { static int reported; unimplemented("SetCursor", &reported); return 0; }
WEAK uint32_t CCALL SetCursorPos_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SetCursorPos", &reported); return 0; }
WEAK uint32_t CCALL SetDIBColorTable_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("SetDIBColorTable", &reported); return 0; }
WEAK uint32_t CCALL SetDIBitsToDevice_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6, uint32_t a7, uint32_t a8, uint32_t a9, uint32_t a10, uint32_t a11) { static int reported; unimplemented("SetDIBitsToDevice", &reported); return 0; }
WEAK uint32_t CCALL SetDlgItemTextA_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("SetDlgItemTextA", &reported); return 0; }
WEAK uint32_t CCALL SetEndOfFile_c(uint32_t a0) { static int reported; unimplemented("SetEndOfFile", &reported); return 0; }
WEAK uint32_t CCALL SetFileAttributesA_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SetFileAttributesA", &reported); return 0; }
WEAK uint32_t CCALL SetFilePointer_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("SetFilePointer", &reported); return 0; }
WEAK uint32_t CCALL SetFocus_c(uint32_t a0) { static int reported; unimplemented("SetFocus", &reported); return 0; }
WEAK uint32_t CCALL SetLastError_c(uint32_t a0) { static int reported; unimplemented("SetLastError", &reported); return 0; }
WEAK uint32_t CCALL setlocale_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("setlocale", &reported); return 0; }
WEAK uint32_t CCALL SetMapperFlags_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SetMapperFlags", &reported); return 0; }
WEAK uint32_t CCALL SetMenu_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SetMenu", &reported); return 0; }
WEAK uint32_t CCALL SetPaletteEntries_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("SetPaletteEntries", &reported); return 0; }
WEAK uint32_t CCALL SetPriorityClass_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SetPriorityClass", &reported); return 0; }
WEAK uint32_t CCALL SetRect_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("SetRect", &reported); return 0; }
WEAK uint32_t CCALL SetStdHandle_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SetStdHandle", &reported); return 0; }
WEAK uint32_t CCALL SetSystemPaletteUse_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SetSystemPaletteUse", &reported); return 0; }
WEAK uint32_t CCALL SetTextColor_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SetTextColor", &reported); return 0; }
WEAK uint32_t CCALL setvbuf_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("setvbuf", &reported); return 0; }
WEAK uint32_t CCALL SetWindowLongA_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("SetWindowLongA", &reported); return 0; }
WEAK uint32_t CCALL SetWindowPos_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6) { static int reported; unimplemented("SetWindowPos", &reported); return 0; }
WEAK uint32_t CCALL ShowCursor_c(uint32_t a0) { static int reported; unimplemented("ShowCursor", &reported); return 0; }
WEAK uint32_t CCALL ShowWindow_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("ShowWindow", &reported); return 0; }
WEAK uint32_t CCALL Sleep_c(uint32_t a0) { static int reported; unimplemented("Sleep", &reported); return 0; }
WEAK uint32_t CCALL SmackBufferBlit_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6, uint32_t a7) { static int reported; unimplemented("SmackBufferBlit", &reported); return 0; }
WEAK uint32_t CCALL SmackBufferClose_c(uint32_t a0) { static int reported; unimplemented("SmackBufferClose", &reported); return 0; }
WEAK uint32_t CCALL SmackBufferNewPalette_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("SmackBufferNewPalette", &reported); return 0; }
WEAK uint32_t CCALL SmackBufferOpen_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) { static int reported; unimplemented("SmackBufferOpen", &reported); return 0; }
WEAK uint32_t CCALL SmackBufferSetPalette_c(uint32_t a0) { static int reported; unimplemented("SmackBufferSetPalette", &reported); return 0; }
WEAK uint32_t CCALL SmackClose_c(uint32_t a0) { static int reported; unimplemented("SmackClose", &reported); return 0; }
WEAK uint32_t CCALL SmackColorRemap_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("SmackColorRemap", &reported); return 0; }
WEAK uint32_t CCALL SmackDoFrame_c(uint32_t a0) { static int reported; unimplemented("SmackDoFrame", &reported); return 0; }
WEAK uint32_t CCALL SmackNextFrame_c(uint32_t a0) { static int reported; unimplemented("SmackNextFrame", &reported); return 0; }
WEAK uint32_t CCALL SmackOpen_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("SmackOpen", &reported); return 0; }
WEAK uint32_t CCALL SmackSoundOnOff_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SmackSoundOnOff", &reported); return 0; }
WEAK uint32_t CCALL SmackSoundUseDirectSound_c(uint32_t a0) { static int reported; unimplemented("SmackSoundUseDirectSound", &reported); return 0; }
WEAK uint32_t CCALL SmackToBuffer_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6) { static int reported; unimplemented("SmackToBuffer", &reported); return 0; }
WEAK uint32_t CCALL SmackToBufferRect_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("SmackToBufferRect", &reported); return 0; }
WEAK uint32_t CCALL SmackWait_c(uint32_t a0) { static int reported; unimplemented("SmackWait", &reported); return 0; }
WEAK uint32_t CCALL sprintf_c(uint32_t a0, uint32_t a1, uint32_t *ap) { static int reported; unimplemented("sprintf", &reported); return 0; }
WEAK uint32_t CCALL srand_c(uint32_t a0) { static int reported; unimplemented("srand", &reported); return 0; }
WEAK uint32_t CCALL sscanf_c(uint32_t a0, uint32_t a1, uint32_t *ap) { static int reported; unimplemented("sscanf", &reported); return 0; }
WEAK uint32_t CCALL strchr_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("strchr", &reported); return 0; }
WEAK uint32_t CCALL StretchBlt_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6, uint32_t a7, uint32_t a8, uint32_t a9, uint32_t a10) { static int reported; unimplemented("StretchBlt", &reported); return 0; }
WEAK uint32_t CCALL strncmp_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("strncmp", &reported); return 0; }
WEAK uint32_t CCALL strncpy_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("strncpy", &reported); return 0; }
WEAK uint32_t CCALL strpbrk_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("strpbrk", &reported); return 0; }
WEAK uint32_t CCALL strrchr_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("strrchr", &reported); return 0; }
WEAK uint32_t CCALL strstr_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("strstr", &reported); return 0; }
WEAK uint32_t CCALL strtok_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("strtok", &reported); return 0; }
WEAK uint32_t CCALL TerminateProcess_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("TerminateProcess", &reported); return 0; }
WEAK uint32_t CCALL TextOutA_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("TextOutA", &reported); return 0; }
WEAK uint32_t CCALL time_c(uint32_t a0) { static int reported; unimplemented("time", &reported); return 0; }
WEAK uint32_t CCALL timeGetTime_c(void) { static int reported; unimplemented("timeGetTime", &reported); return 0; }
WEAK uint32_t CCALL TlsGetValue_c(uint32_t a0) { static int reported; unimplemented("TlsGetValue", &reported); return 0; }
WEAK uint32_t CCALL TlsSetValue_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("TlsSetValue", &reported); return 0; }
WEAK uint32_t CCALL ToAscii_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("ToAscii", &reported); return 0; }
WEAK uint32_t CCALL tolower_c(uint32_t a0) { static int reported; unimplemented("tolower", &reported); return 0; }
WEAK uint32_t CCALL toupper_c(uint32_t a0) { static int reported; unimplemented("toupper", &reported); return 0; }
WEAK uint32_t CCALL TranslateMessage_c(uint32_t a0) { static int reported; unimplemented("TranslateMessage", &reported); return 0; }
WEAK uint32_t CCALL UnmapViewOfFile_c(uint32_t a0) { static int reported; unimplemented("UnmapViewOfFile", &reported); return 0; }
WEAK uint32_t CCALL UpdateWindow_c(uint32_t a0) { static int reported; unimplemented("UpdateWindow", &reported); return 0; }
WEAK uint32_t CCALL ValidateRect_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("ValidateRect", &reported); return 0; }
WEAK uint32_t CCALL VirtualAlloc_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) { static int reported; unimplemented("VirtualAlloc", &reported); return 0; }
WEAK uint32_t CCALL VirtualFree_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("VirtualFree", &reported); return 0; }
WEAK uint32_t CCALL VirtualQuery_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("VirtualQuery", &reported); return 0; }
WEAK uint32_t CCALL WaitForSingleObject_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("WaitForSingleObject", &reported); return 0; }
WEAK uint32_t CCALL WideCharToMultiByte_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6, uint32_t a7) { static int reported; unimplemented("WideCharToMultiByte", &reported); return 0; }
WEAK uint32_t CCALL WriteFile_c(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) { static int reported; unimplemented("WriteFile", &reported); return 0; }
WEAK uint32_t CCALL wsprintfA_c(uint32_t a0, uint32_t a1, uint32_t *ap) { static int reported; unimplemented("wsprintfA", &reported); return 0; }
WEAK uint32_t CCALL wvsprintfA_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("wvsprintfA", &reported); return 0; }
WEAK uint32_t CCALL strspn_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("strspn", &reported); return 0; }
WEAK uint32_t CCALL strcspn_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("strcspn", &reported); return 0; }
WEAK uint32_t CCALL strncat_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("strncat", &reported); return 0; }
WEAK uint32_t CCALL vsprintf_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("vsprintf", &reported); return 0; }
WEAK uint32_t CCALL memcpy_c(uint32_t a0, uint32_t a1, uint32_t a2) { static int reported; unimplemented("memcpy", &reported); return 0; }
WEAK uint32_t CCALL printf_c(uint32_t a0, uint32_t *ap) { static int reported; unimplemented("printf", &reported); return 0; }
WEAK uint32_t CCALL ungetc_c(uint32_t a0, uint32_t a1) { static int reported; unimplemented("ungetc", &reported); return 0; }
WEAK uint32_t CCALL _filbuf_c(uint32_t a0) { static int reported; unimplemented("_filbuf", &reported); return 0; }
WEAK uint32_t CCALL i76_frame_tick_c(void) { static int reported; unimplemented("i76_frame_tick", &reported); return 0; }
