;; generated by gen_imports.py from imports.spec - do not edit

%include "asm-calls.inc"

extern IDirectSound_QueryInterface_c
extern IDirectSound_AddRef_c
extern IDirectSound_Release_c
extern IDirectSound_CreateSoundBuffer_c
extern IDirectSound_GetCaps_c
extern IDirectSound_DuplicateSoundBuffer_c
extern IDirectSound_SetCooperativeLevel_c
extern IDirectSound_Compact_c
extern IDirectSound_GetSpeakerConfig_c
extern IDirectSound_SetSpeakerConfig_c
extern IDirectSound_Initialize_c
extern IDirectSoundBuffer_QueryInterface_c
extern IDirectSoundBuffer_AddRef_c
extern IDirectSoundBuffer_Release_c
extern IDirectSoundBuffer_GetCaps_c
extern IDirectSoundBuffer_GetCurrentPosition_c
extern IDirectSoundBuffer_GetFormat_c
extern IDirectSoundBuffer_GetVolume_c
extern IDirectSoundBuffer_GetPan_c
extern IDirectSoundBuffer_GetFrequency_c
extern IDirectSoundBuffer_GetStatus_c
extern IDirectSoundBuffer_Initialize_c
extern IDirectSoundBuffer_Lock_c
extern IDirectSoundBuffer_Play_c
extern IDirectSoundBuffer_SetCurrentPosition_c
extern IDirectSoundBuffer_SetFormat_c
extern IDirectSoundBuffer_SetVolume_c
extern IDirectSoundBuffer_SetPan_c
extern IDirectSoundBuffer_SetFrequency_c
extern IDirectSoundBuffer_Stop_c
extern IDirectSoundBuffer_Unlock_c
extern IDirectSoundBuffer_Restore_c
extern IDirectSound3DListener_QueryInterface_c
extern IDirectSound3DListener_AddRef_c
extern IDirectSound3DListener_Release_c
extern IDirectSound3DListener_GetAllParameters_c
extern IDirectSound3DListener_GetDistanceFactor_c
extern IDirectSound3DListener_GetDopplerFactor_c
extern IDirectSound3DListener_GetOrientation_c
extern IDirectSound3DListener_GetPosition_c
extern IDirectSound3DListener_GetRolloffFactor_c
extern IDirectSound3DListener_GetVelocity_c
extern IDirectSound3DListener_SetAllParameters_c
extern IDirectSound3DListener_SetDistanceFactor_c
extern IDirectSound3DListener_SetDopplerFactor_c
extern IDirectSound3DListener_SetOrientation_c
extern IDirectSound3DListener_SetPosition_c
extern IDirectSound3DListener_SetRolloffFactor_c
extern IDirectSound3DListener_SetVelocity_c
extern IDirectSound3DListener_CommitDeferredSettings_c
extern IDirectSound3DBuffer_QueryInterface_c
extern IDirectSound3DBuffer_AddRef_c
extern IDirectSound3DBuffer_Release_c
extern IDirectSound3DBuffer_GetAllParameters_c
extern IDirectSound3DBuffer_GetConeAngles_c
extern IDirectSound3DBuffer_GetConeOrientation_c
extern IDirectSound3DBuffer_GetConeOutsideVolume_c
extern IDirectSound3DBuffer_GetMaxDistance_c
extern IDirectSound3DBuffer_GetMinDistance_c
extern IDirectSound3DBuffer_GetMode_c
extern IDirectSound3DBuffer_GetPosition_c
extern IDirectSound3DBuffer_GetVelocity_c
extern IDirectSound3DBuffer_SetAllParameters_c
extern IDirectSound3DBuffer_SetConeAngles_c
extern IDirectSound3DBuffer_SetConeOrientation_c
extern IDirectSound3DBuffer_SetConeOutsideVolume_c
extern IDirectSound3DBuffer_SetMaxDistance_c
extern IDirectSound3DBuffer_SetMinDistance_c
extern IDirectSound3DBuffer_SetMode_c
extern IDirectSound3DBuffer_SetPosition_c
extern IDirectSound3DBuffer_SetVelocity_c
global IDirectSoundVtbl_asm2c
global IDirectSoundBufferVtbl_asm2c
global IDirectSound3DListenerVtbl_asm2c
global IDirectSound3DBufferVtbl_asm2c

%ifidn __OUTPUT_FORMAT__, elf32
section .note.GNU-stack noalloc noexec nowrite progbits
section .text progbits alloc exec nowrite align=16
%else
section .text code align=16
%endif

align 16
IDirectSound_QueryInterface_asm2c:
        Call_Asm_Stack3 IDirectSound_QueryInterface_c, 3

align 16
IDirectSound_AddRef_asm2c:
        Call_Asm_Stack1 IDirectSound_AddRef_c, 1

align 16
IDirectSound_Release_asm2c:
        Call_Asm_Stack1 IDirectSound_Release_c, 1

align 16
IDirectSound_CreateSoundBuffer_asm2c:
        Call_Asm_Stack4 IDirectSound_CreateSoundBuffer_c, 4

align 16
IDirectSound_GetCaps_asm2c:
        Call_Asm_Stack2 IDirectSound_GetCaps_c, 2

align 16
IDirectSound_DuplicateSoundBuffer_asm2c:
        Call_Asm_Stack3 IDirectSound_DuplicateSoundBuffer_c, 3

align 16
IDirectSound_SetCooperativeLevel_asm2c:
        Call_Asm_Stack3 IDirectSound_SetCooperativeLevel_c, 3

align 16
IDirectSound_Compact_asm2c:
        Call_Asm_Stack1 IDirectSound_Compact_c, 1

align 16
IDirectSound_GetSpeakerConfig_asm2c:
        Call_Asm_Stack2 IDirectSound_GetSpeakerConfig_c, 2

align 16
IDirectSound_SetSpeakerConfig_asm2c:
        Call_Asm_Stack2 IDirectSound_SetSpeakerConfig_c, 2

align 16
IDirectSound_Initialize_asm2c:
        Call_Asm_Stack2 IDirectSound_Initialize_c, 2

align 16
IDirectSoundBuffer_QueryInterface_asm2c:
        Call_Asm_Stack3 IDirectSoundBuffer_QueryInterface_c, 3

align 16
IDirectSoundBuffer_AddRef_asm2c:
        Call_Asm_Stack1 IDirectSoundBuffer_AddRef_c, 1

align 16
IDirectSoundBuffer_Release_asm2c:
        Call_Asm_Stack1 IDirectSoundBuffer_Release_c, 1

align 16
IDirectSoundBuffer_GetCaps_asm2c:
        Call_Asm_Stack2 IDirectSoundBuffer_GetCaps_c, 2

align 16
IDirectSoundBuffer_GetCurrentPosition_asm2c:
        Call_Asm_Stack3 IDirectSoundBuffer_GetCurrentPosition_c, 3

align 16
IDirectSoundBuffer_GetFormat_asm2c:
        Call_Asm_Stack4 IDirectSoundBuffer_GetFormat_c, 4

align 16
IDirectSoundBuffer_GetVolume_asm2c:
        Call_Asm_Stack2 IDirectSoundBuffer_GetVolume_c, 2

align 16
IDirectSoundBuffer_GetPan_asm2c:
        Call_Asm_Stack2 IDirectSoundBuffer_GetPan_c, 2

align 16
IDirectSoundBuffer_GetFrequency_asm2c:
        Call_Asm_Stack2 IDirectSoundBuffer_GetFrequency_c, 2

align 16
IDirectSoundBuffer_GetStatus_asm2c:
        Call_Asm_Stack2 IDirectSoundBuffer_GetStatus_c, 2

align 16
IDirectSoundBuffer_Initialize_asm2c:
        Call_Asm_Stack3 IDirectSoundBuffer_Initialize_c, 3

align 16
IDirectSoundBuffer_Lock_asm2c:
        Call_Asm_Stack8 IDirectSoundBuffer_Lock_c, 8

align 16
IDirectSoundBuffer_Play_asm2c:
        Call_Asm_Stack4 IDirectSoundBuffer_Play_c, 4

align 16
IDirectSoundBuffer_SetCurrentPosition_asm2c:
        Call_Asm_Stack2 IDirectSoundBuffer_SetCurrentPosition_c, 2

align 16
IDirectSoundBuffer_SetFormat_asm2c:
        Call_Asm_Stack2 IDirectSoundBuffer_SetFormat_c, 2

align 16
IDirectSoundBuffer_SetVolume_asm2c:
        Call_Asm_Stack2 IDirectSoundBuffer_SetVolume_c, 2

align 16
IDirectSoundBuffer_SetPan_asm2c:
        Call_Asm_Stack2 IDirectSoundBuffer_SetPan_c, 2

align 16
IDirectSoundBuffer_SetFrequency_asm2c:
        Call_Asm_Stack2 IDirectSoundBuffer_SetFrequency_c, 2

align 16
IDirectSoundBuffer_Stop_asm2c:
        Call_Asm_Stack1 IDirectSoundBuffer_Stop_c, 1

align 16
IDirectSoundBuffer_Unlock_asm2c:
        Call_Asm_Stack5 IDirectSoundBuffer_Unlock_c, 5

align 16
IDirectSoundBuffer_Restore_asm2c:
        Call_Asm_Stack1 IDirectSoundBuffer_Restore_c, 1

align 16
IDirectSound3DListener_QueryInterface_asm2c:
        Call_Asm_Stack3 IDirectSound3DListener_QueryInterface_c, 3

align 16
IDirectSound3DListener_AddRef_asm2c:
        Call_Asm_Stack1 IDirectSound3DListener_AddRef_c, 1

align 16
IDirectSound3DListener_Release_asm2c:
        Call_Asm_Stack1 IDirectSound3DListener_Release_c, 1

align 16
IDirectSound3DListener_GetAllParameters_asm2c:
        Call_Asm_Stack2 IDirectSound3DListener_GetAllParameters_c, 2

align 16
IDirectSound3DListener_GetDistanceFactor_asm2c:
        Call_Asm_Stack2 IDirectSound3DListener_GetDistanceFactor_c, 2

align 16
IDirectSound3DListener_GetDopplerFactor_asm2c:
        Call_Asm_Stack2 IDirectSound3DListener_GetDopplerFactor_c, 2

align 16
IDirectSound3DListener_GetOrientation_asm2c:
        Call_Asm_Stack3 IDirectSound3DListener_GetOrientation_c, 3

align 16
IDirectSound3DListener_GetPosition_asm2c:
        Call_Asm_Stack2 IDirectSound3DListener_GetPosition_c, 2

align 16
IDirectSound3DListener_GetRolloffFactor_asm2c:
        Call_Asm_Stack2 IDirectSound3DListener_GetRolloffFactor_c, 2

align 16
IDirectSound3DListener_GetVelocity_asm2c:
        Call_Asm_Stack2 IDirectSound3DListener_GetVelocity_c, 2

align 16
IDirectSound3DListener_SetAllParameters_asm2c:
        Call_Asm_Stack3 IDirectSound3DListener_SetAllParameters_c, 3

align 16
IDirectSound3DListener_SetDistanceFactor_asm2c:
        Call_Asm_Stack3 IDirectSound3DListener_SetDistanceFactor_c, 3

align 16
IDirectSound3DListener_SetDopplerFactor_asm2c:
        Call_Asm_Stack3 IDirectSound3DListener_SetDopplerFactor_c, 3

align 16
IDirectSound3DListener_SetOrientation_asm2c:
        Call_Asm_Stack8 IDirectSound3DListener_SetOrientation_c, 8

align 16
IDirectSound3DListener_SetPosition_asm2c:
        Call_Asm_Stack5 IDirectSound3DListener_SetPosition_c, 5

align 16
IDirectSound3DListener_SetRolloffFactor_asm2c:
        Call_Asm_Stack3 IDirectSound3DListener_SetRolloffFactor_c, 3

align 16
IDirectSound3DListener_SetVelocity_asm2c:
        Call_Asm_Stack5 IDirectSound3DListener_SetVelocity_c, 5

align 16
IDirectSound3DListener_CommitDeferredSettings_asm2c:
        Call_Asm_Stack1 IDirectSound3DListener_CommitDeferredSettings_c, 1

align 16
IDirectSound3DBuffer_QueryInterface_asm2c:
        Call_Asm_Stack3 IDirectSound3DBuffer_QueryInterface_c, 3

align 16
IDirectSound3DBuffer_AddRef_asm2c:
        Call_Asm_Stack1 IDirectSound3DBuffer_AddRef_c, 1

align 16
IDirectSound3DBuffer_Release_asm2c:
        Call_Asm_Stack1 IDirectSound3DBuffer_Release_c, 1

align 16
IDirectSound3DBuffer_GetAllParameters_asm2c:
        Call_Asm_Stack2 IDirectSound3DBuffer_GetAllParameters_c, 2

align 16
IDirectSound3DBuffer_GetConeAngles_asm2c:
        Call_Asm_Stack3 IDirectSound3DBuffer_GetConeAngles_c, 3

align 16
IDirectSound3DBuffer_GetConeOrientation_asm2c:
        Call_Asm_Stack2 IDirectSound3DBuffer_GetConeOrientation_c, 2

align 16
IDirectSound3DBuffer_GetConeOutsideVolume_asm2c:
        Call_Asm_Stack2 IDirectSound3DBuffer_GetConeOutsideVolume_c, 2

align 16
IDirectSound3DBuffer_GetMaxDistance_asm2c:
        Call_Asm_Stack2 IDirectSound3DBuffer_GetMaxDistance_c, 2

align 16
IDirectSound3DBuffer_GetMinDistance_asm2c:
        Call_Asm_Stack2 IDirectSound3DBuffer_GetMinDistance_c, 2

align 16
IDirectSound3DBuffer_GetMode_asm2c:
        Call_Asm_Stack2 IDirectSound3DBuffer_GetMode_c, 2

align 16
IDirectSound3DBuffer_GetPosition_asm2c:
        Call_Asm_Stack2 IDirectSound3DBuffer_GetPosition_c, 2

align 16
IDirectSound3DBuffer_GetVelocity_asm2c:
        Call_Asm_Stack2 IDirectSound3DBuffer_GetVelocity_c, 2

align 16
IDirectSound3DBuffer_SetAllParameters_asm2c:
        Call_Asm_Stack3 IDirectSound3DBuffer_SetAllParameters_c, 3

align 16
IDirectSound3DBuffer_SetConeAngles_asm2c:
        Call_Asm_Stack4 IDirectSound3DBuffer_SetConeAngles_c, 4

align 16
IDirectSound3DBuffer_SetConeOrientation_asm2c:
        Call_Asm_Stack5 IDirectSound3DBuffer_SetConeOrientation_c, 5

align 16
IDirectSound3DBuffer_SetConeOutsideVolume_asm2c:
        Call_Asm_Stack3 IDirectSound3DBuffer_SetConeOutsideVolume_c, 3

align 16
IDirectSound3DBuffer_SetMaxDistance_asm2c:
        Call_Asm_Stack3 IDirectSound3DBuffer_SetMaxDistance_c, 3

align 16
IDirectSound3DBuffer_SetMinDistance_asm2c:
        Call_Asm_Stack3 IDirectSound3DBuffer_SetMinDistance_c, 3

align 16
IDirectSound3DBuffer_SetMode_asm2c:
        Call_Asm_Stack3 IDirectSound3DBuffer_SetMode_c, 3

align 16
IDirectSound3DBuffer_SetPosition_asm2c:
        Call_Asm_Stack5 IDirectSound3DBuffer_SetPosition_c, 5

align 16
IDirectSound3DBuffer_SetVelocity_asm2c:
        Call_Asm_Stack5 IDirectSound3DBuffer_SetVelocity_c, 5


%ifidn __OUTPUT_FORMAT__, elf32
section .rodata progbits alloc noexec nowrite align=4
%else
section .rdata rdata align=4
%endif

IDirectSoundVtbl_asm2c:
        dd IDirectSound_QueryInterface_asm2c
        dd IDirectSound_AddRef_asm2c
        dd IDirectSound_Release_asm2c
        dd IDirectSound_CreateSoundBuffer_asm2c
        dd IDirectSound_GetCaps_asm2c
        dd IDirectSound_DuplicateSoundBuffer_asm2c
        dd IDirectSound_SetCooperativeLevel_asm2c
        dd IDirectSound_Compact_asm2c
        dd IDirectSound_GetSpeakerConfig_asm2c
        dd IDirectSound_SetSpeakerConfig_asm2c
        dd IDirectSound_Initialize_asm2c

IDirectSoundBufferVtbl_asm2c:
        dd IDirectSoundBuffer_QueryInterface_asm2c
        dd IDirectSoundBuffer_AddRef_asm2c
        dd IDirectSoundBuffer_Release_asm2c
        dd IDirectSoundBuffer_GetCaps_asm2c
        dd IDirectSoundBuffer_GetCurrentPosition_asm2c
        dd IDirectSoundBuffer_GetFormat_asm2c
        dd IDirectSoundBuffer_GetVolume_asm2c
        dd IDirectSoundBuffer_GetPan_asm2c
        dd IDirectSoundBuffer_GetFrequency_asm2c
        dd IDirectSoundBuffer_GetStatus_asm2c
        dd IDirectSoundBuffer_Initialize_asm2c
        dd IDirectSoundBuffer_Lock_asm2c
        dd IDirectSoundBuffer_Play_asm2c
        dd IDirectSoundBuffer_SetCurrentPosition_asm2c
        dd IDirectSoundBuffer_SetFormat_asm2c
        dd IDirectSoundBuffer_SetVolume_asm2c
        dd IDirectSoundBuffer_SetPan_asm2c
        dd IDirectSoundBuffer_SetFrequency_asm2c
        dd IDirectSoundBuffer_Stop_asm2c
        dd IDirectSoundBuffer_Unlock_asm2c
        dd IDirectSoundBuffer_Restore_asm2c

IDirectSound3DListenerVtbl_asm2c:
        dd IDirectSound3DListener_QueryInterface_asm2c
        dd IDirectSound3DListener_AddRef_asm2c
        dd IDirectSound3DListener_Release_asm2c
        dd IDirectSound3DListener_GetAllParameters_asm2c
        dd IDirectSound3DListener_GetDistanceFactor_asm2c
        dd IDirectSound3DListener_GetDopplerFactor_asm2c
        dd IDirectSound3DListener_GetOrientation_asm2c
        dd IDirectSound3DListener_GetPosition_asm2c
        dd IDirectSound3DListener_GetRolloffFactor_asm2c
        dd IDirectSound3DListener_GetVelocity_asm2c
        dd IDirectSound3DListener_SetAllParameters_asm2c
        dd IDirectSound3DListener_SetDistanceFactor_asm2c
        dd IDirectSound3DListener_SetDopplerFactor_asm2c
        dd IDirectSound3DListener_SetOrientation_asm2c
        dd IDirectSound3DListener_SetPosition_asm2c
        dd IDirectSound3DListener_SetRolloffFactor_asm2c
        dd IDirectSound3DListener_SetVelocity_asm2c
        dd IDirectSound3DListener_CommitDeferredSettings_asm2c

IDirectSound3DBufferVtbl_asm2c:
        dd IDirectSound3DBuffer_QueryInterface_asm2c
        dd IDirectSound3DBuffer_AddRef_asm2c
        dd IDirectSound3DBuffer_Release_asm2c
        dd IDirectSound3DBuffer_GetAllParameters_asm2c
        dd IDirectSound3DBuffer_GetConeAngles_asm2c
        dd IDirectSound3DBuffer_GetConeOrientation_asm2c
        dd IDirectSound3DBuffer_GetConeOutsideVolume_asm2c
        dd IDirectSound3DBuffer_GetMaxDistance_asm2c
        dd IDirectSound3DBuffer_GetMinDistance_asm2c
        dd IDirectSound3DBuffer_GetMode_asm2c
        dd IDirectSound3DBuffer_GetPosition_asm2c
        dd IDirectSound3DBuffer_GetVelocity_asm2c
        dd IDirectSound3DBuffer_SetAllParameters_asm2c
        dd IDirectSound3DBuffer_SetConeAngles_asm2c
        dd IDirectSound3DBuffer_SetConeOrientation_asm2c
        dd IDirectSound3DBuffer_SetConeOutsideVolume_asm2c
        dd IDirectSound3DBuffer_SetMaxDistance_asm2c
        dd IDirectSound3DBuffer_SetMinDistance_asm2c
        dd IDirectSound3DBuffer_SetMode_asm2c
        dd IDirectSound3DBuffer_SetPosition_asm2c
        dd IDirectSound3DBuffer_SetVelocity_asm2c

