;; generated by gen_imports.py from imports.spec - do not edit

%include "asm-calls.inc"

extern operator_new_c
extern operator_delete_c
extern _access_c
extern _assert_c
extern _CIacos_c
extern _CIasin_c
extern _CIatan2_c
extern _CIfmod_c
extern _CIpow_c
extern _close_c
extern _errno_c
extern _findclose_c
extern _findfirst_c
extern _findnext_c
extern grAlphaBlendFunction_c
extern grAlphaCombine_c
extern grBufferClear_c
extern grBufferSwap_c
extern grChromakeyMode_c
extern grChromakeyValue_c
extern grColorCombine_c
extern grConstantColorValue_c
extern grCullMode_c
extern grDepthBufferFunction_c
extern grDepthBufferMode_c
extern grDepthMask_c
extern grDrawLine_c
extern grDrawPoint_c
extern grDrawTriangle_c
extern grFogColorValue_c
extern grFogMode_c
extern grGlideGetState_c
extern grGlideInit_c
extern grGlideSetState_c
extern grGlideShutdown_c
extern grLfbLock_c
extern grLfbUnlock_c
extern grRenderBuffer_c
extern grSstQueryBoards_c
extern grSstQueryHardware_c
extern grSstSelect_c
extern grSstWinClose_c
extern grSstWinOpen_c
extern grTexCalcMemRequired_c
extern grTexClampMode_c
extern grTexCombine_c
extern grTexDownloadMipMap_c
extern grTexDownloadTable_c
extern grTexFilterMode_c
extern grTexMaxAddress_c
extern grTexMinAddress_c
extern grTexMipMapMode_c
extern grTexSource_c
extern _isctype_c
extern _ismbcalnum_c
extern _ismbcpunct_c
extern _ismbcspace_c
extern _isnan_c
extern _itoa_c
extern _lseek_c
extern _mbsicmp_c
extern _mbsnbcat_c
extern _mbsnbcpy_c
extern _mbsnbicmp_c
extern _mkdir_c
extern _msize_c
extern _open_c
extern _putch_c
extern _read_c
extern _splitpath_c
extern _stat_c
extern _stricmp_c
extern _strlwr_c
extern _strnicmp_c
extern _unlink_c
extern _vsnprintf_c
extern abort_c
extern AddFontResourceA_c
extern AdjustWindowRect_c
extern atoi_c
extern atol_c
extern auxGetDevCapsA_c
extern auxGetNumDevs_c
extern auxSetVolume_c
extern BeginPaint_c
extern BitBlt_c
extern bsearch_c
extern calloc_c
extern ClientToScreen_c
extern ClipCursor_c
extern clock_c
extern CloseHandle_c
extern CoInitialize_c
extern CopyFileA_c
extern CoUninitialize_c
extern CreateCompatibleDC_c
extern CreateDIBSection_c
extern CreateFileA_c
extern CreateFileMappingA_c
extern CreateFontIndirectA_c
extern CreatePalette_c
extern CreateProcessA_c
extern CreateScalableFontResourceA_c
extern CreateThread_c
extern CreateWindowExA_c
extern DefWindowProcA_c
extern DeleteCriticalSection_c
extern DeleteDC_c
extern DeleteFileA_c
extern DeleteObject_c
extern DestroyWindow_c
extern DialogBoxParamA_c
extern difftime_c
extern DirectDrawCreate_c
extern DirectDrawEnumerateA_c
extern DirectSoundCreate_c
extern DispatchMessageA_c
extern msvcrt_div_c
extern dp_enableDebugPrint_c
extern dpAddPlayerToGroup_c
extern dpClose_c
extern dpCreate_c
extern dpCreateGroup_c
extern dpCreatePlayer_c
extern dpDestroy_c
extern dpDestroyPlayer_c
extern dpEnumGroupPlayers_c
extern dpEnumGroups_c
extern dpEnumPlayers_c
extern dpEnumSessions_c
extern dpFreeze_c
extern dpEnumTransports_c
extern dpGetPlayerData_c
extern dpGetPlayerName_c
extern dpGetSessionDesc_c
extern dpOpen_c
extern dpReceive_c
extern dpSend_c
extern dpSetGameServer_c
extern dpSetPlayerData_c
extern EndDialog_c
extern EndPaint_c
extern EnterCriticalSection_c
extern exit_c
extern ExitProcess_c
extern fclose_c
extern fflush_c
extern fgetc_c
extern fgets_c
extern FindClose_c
extern FindFirstFileA_c
extern FindNextFileA_c
extern FindWindowA_c
extern floor_c
extern FlushFileBuffers_c
extern fopen_c
extern fprintf_c
extern fputc_c
extern fputs_c
extern fread_c
extern free_c
extern FreeLibrary_c
extern fscanf_c
extern fseek_c
extern ftell_c
extern fwrite_c
extern GdiFlush_c
extern GetAsyncKeyState_c
extern getc_c
extern GetClientRect_c
extern GetCPInfo_c
extern GetCurrentDirectoryA_c
extern GetCurrentProcess_c
extern GetCurrentThreadId_c
extern GetCursorPos_c
extern GetDC_c
extern GetDeviceCaps_c
extern GetDlgItem_c
extern GetDlgItemTextA_c
extern GetDriveTypeA_c
extern GetFileTime_c
extern GetFileType_c
extern GetFocus_c
extern GetKeyboardType_c
extern GetKeyState_c
extern GetLastError_c
extern GetLocaleInfoA_c
extern GetLocaleInfoW_c
extern GetLogicalDrives_c
extern GetLogicalDriveStringsA_c
extern GetModuleFileNameA_c
extern GetModuleHandleA_c
extern GetProcAddress_c
extern GetProcessHeap_c
extern GetStdHandle_c
extern GetStockObject_c
extern GetStringTypeA_c
extern GetStringTypeW_c
extern GetSystemDefaultLCID_c
extern GetSystemInfo_c
extern GetSystemMetrics_c
extern GetSystemPaletteEntries_c
extern GetTextExtentExPointA_c
extern GetTextExtentPoint32A_c
extern GetTickCount_c
extern GetVolumeInformationA_c
extern GetWindowLongA_c
extern GetWindowRect_c
extern GetWindowsDirectoryA_c
extern HeapAlloc_c
extern HeapCompact_c
extern HeapCreate_c
extern HeapDestroy_c
extern HeapFree_c
extern HeapReAlloc_c
extern HeapSize_c
extern ImmAssociateContext_c
extern InitializeCriticalSection_c
extern InterlockedDecrement_c
extern InterlockedIncrement_c
extern isspace_c
extern joyGetDevCapsA_c
extern joyGetNumDevs_c
extern joyGetPos_c
extern joyGetPosEx_c
extern LCMapStringA_c
extern LCMapStringW_c
extern LeaveCriticalSection_c
extern LoadCursorA_c
extern LoadCursorFromFileA_c
extern LoadLibraryA_c
extern LoadModule_c
extern lstrcatA_c
extern lstrcpyA_c
extern malloc_c
extern MapViewOfFile_c
extern MapVirtualKeyA_c
extern mciGetErrorStringA_c
extern mciSendCommandA_c
extern memmove_c
extern MessageBoxA_c
extern MultiByteToWideChar_c
extern OutputDebugStringA_c
extern PeekMessageA_c
extern PostMessageA_c
extern PostQuitMessage_c
extern qsort_c
extern rand_c
extern ReadFile_c
extern RealizePalette_c
extern realloc_c
extern Rectangle_c
extern RegCloseKey_c
extern RegCreateKeyExA_c
extern RegisterClassA_c
extern RegOpenKeyExA_c
extern RegQueryValueExA_c
extern RegSetValueExA_c
extern ReleaseDC_c
extern RemoveFontResourceA_c
extern ScreenToClient_c
extern SelectObject_c
extern SelectPalette_c
extern SendDlgItemMessageA_c
extern SendMessageA_c
extern SetBkColor_c
extern SetBkMode_c
extern SetCursor_c
extern SetCursorPos_c
extern SetDIBColorTable_c
extern SetDIBitsToDevice_c
extern SetDlgItemTextA_c
extern SetEndOfFile_c
extern SetFileAttributesA_c
extern SetFilePointer_c
extern SetFocus_c
extern SetLastError_c
extern setlocale_c
extern SetMapperFlags_c
extern SetMenu_c
extern SetPaletteEntries_c
extern SetPriorityClass_c
extern SetRect_c
extern SetStdHandle_c
extern SetSystemPaletteUse_c
extern SetTextColor_c
extern setvbuf_c
extern SetWindowLongA_c
extern SetWindowPos_c
extern ShowCursor_c
extern ShowWindow_c
extern Sleep_c
extern SmackBufferBlit_c
extern SmackBufferClose_c
extern SmackBufferNewPalette_c
extern SmackBufferOpen_c
extern SmackBufferSetPalette_c
extern SmackClose_c
extern SmackColorRemap_c
extern SmackDoFrame_c
extern SmackNextFrame_c
extern SmackOpen_c
extern SmackSoundOnOff_c
extern SmackSoundUseDirectSound_c
extern SmackToBuffer_c
extern SmackToBufferRect_c
extern SmackWait_c
extern sprintf_c
extern srand_c
extern sscanf_c
extern strchr_c
extern StretchBlt_c
extern strncmp_c
extern strncpy_c
extern strpbrk_c
extern strrchr_c
extern strstr_c
extern strtok_c
extern TerminateProcess_c
extern TextOutA_c
extern time_c
extern timeGetTime_c
extern TlsGetValue_c
extern TlsSetValue_c
extern ToAscii_c
extern tolower_c
extern toupper_c
extern TranslateMessage_c
extern UnmapViewOfFile_c
extern UpdateWindow_c
extern ValidateRect_c
extern VirtualAlloc_c
extern VirtualFree_c
extern VirtualQuery_c
extern WaitForSingleObject_c
extern WideCharToMultiByte_c
extern WriteFile_c
extern wsprintfA_c
extern wvsprintfA_c
extern strspn_c
extern strcspn_c
extern strncat_c
extern vsprintf_c
extern memcpy_c
extern printf_c
extern ungetc_c
extern _filbuf_c
extern i76_frame_tick_c
extern i76shell_part_strncmp_c

global operator_new_asm2c
global operator_delete_asm2c
global _access_asm2c
global _assert_asm2c
global _CIacos_asm2c
global _CIasin_asm2c
global _CIatan2_asm2c
global _CIfmod_asm2c
global _CIpow_asm2c
global _close_asm2c
global _errno_asm2c
global _findclose_asm2c
global _findfirst_asm2c
global _findnext_asm2c
global grAlphaBlendFunction_asm2c
global grAlphaCombine_asm2c
global grBufferClear_asm2c
global grBufferSwap_asm2c
global grChromakeyMode_asm2c
global grChromakeyValue_asm2c
global grColorCombine_asm2c
global grConstantColorValue_asm2c
global grCullMode_asm2c
global grDepthBufferFunction_asm2c
global grDepthBufferMode_asm2c
global grDepthMask_asm2c
global grDrawLine_asm2c
global grDrawPoint_asm2c
global grDrawTriangle_asm2c
global grFogColorValue_asm2c
global grFogMode_asm2c
global grGlideGetState_asm2c
global grGlideInit_asm2c
global grGlideSetState_asm2c
global grGlideShutdown_asm2c
global grLfbLock_asm2c
global grLfbUnlock_asm2c
global grRenderBuffer_asm2c
global grSstQueryBoards_asm2c
global grSstQueryHardware_asm2c
global grSstSelect_asm2c
global grSstWinClose_asm2c
global grSstWinOpen_asm2c
global grTexCalcMemRequired_asm2c
global grTexClampMode_asm2c
global grTexCombine_asm2c
global grTexDownloadMipMap_asm2c
global grTexDownloadTable_asm2c
global grTexFilterMode_asm2c
global grTexMaxAddress_asm2c
global grTexMinAddress_asm2c
global grTexMipMapMode_asm2c
global grTexSource_asm2c
global _isctype_asm2c
global _ismbcalnum_asm2c
global _ismbcpunct_asm2c
global _ismbcspace_asm2c
global _isnan_asm2c
global _itoa_asm2c
global _lseek_asm2c
global _mbsicmp_asm2c
global _mbsnbcat_asm2c
global _mbsnbcpy_asm2c
global _mbsnbicmp_asm2c
global _mkdir_asm2c
global _msize_asm2c
global _open_asm2c
global _putch_asm2c
global _read_asm2c
global _splitpath_asm2c
global _stat_asm2c
global _stricmp_asm2c
global _strlwr_asm2c
global _strnicmp_asm2c
global _unlink_asm2c
global _vsnprintf_asm2c
global abort_asm2c
global AddFontResourceA_asm2c
global AdjustWindowRect_asm2c
global atoi_asm2c
global atol_asm2c
global auxGetDevCapsA_asm2c
global auxGetNumDevs_asm2c
global auxSetVolume_asm2c
global BeginPaint_asm2c
global BitBlt_asm2c
global bsearch_asm2c
global calloc_asm2c
global ClientToScreen_asm2c
global ClipCursor_asm2c
global clock_asm2c
global CloseHandle_asm2c
global CoInitialize_asm2c
global CopyFileA_asm2c
global CoUninitialize_asm2c
global CreateCompatibleDC_asm2c
global CreateDIBSection_asm2c
global CreateFileA_asm2c
global CreateFileMappingA_asm2c
global CreateFontIndirectA_asm2c
global CreatePalette_asm2c
global CreateProcessA_asm2c
global CreateScalableFontResourceA_asm2c
global CreateThread_asm2c
global CreateWindowExA_asm2c
global DefWindowProcA_asm2c
global DeleteCriticalSection_asm2c
global DeleteDC_asm2c
global DeleteFileA_asm2c
global DeleteObject_asm2c
global DestroyWindow_asm2c
global DialogBoxParamA_asm2c
global difftime_asm2c
global DirectDrawCreate_asm2c
global DirectDrawEnumerateA_asm2c
global DirectSoundCreate_asm2c
global DispatchMessageA_asm2c
global msvcrt_div_asm2c
global dp_enableDebugPrint_asm2c
global dpAddPlayerToGroup_asm2c
global dpClose_asm2c
global dpCreate_asm2c
global dpCreateGroup_asm2c
global dpCreatePlayer_asm2c
global dpDestroy_asm2c
global dpDestroyPlayer_asm2c
global dpEnumGroupPlayers_asm2c
global dpEnumGroups_asm2c
global dpEnumPlayers_asm2c
global dpEnumSessions_asm2c
global dpFreeze_asm2c
global dpEnumTransports_asm2c
global dpGetPlayerData_asm2c
global dpGetPlayerName_asm2c
global dpGetSessionDesc_asm2c
global dpOpen_asm2c
global dpReceive_asm2c
global dpSend_asm2c
global dpSetGameServer_asm2c
global dpSetPlayerData_asm2c
global EndDialog_asm2c
global EndPaint_asm2c
global EnterCriticalSection_asm2c
global exit_asm2c
global ExitProcess_asm2c
global fclose_asm2c
global fflush_asm2c
global fgetc_asm2c
global fgets_asm2c
global FindClose_asm2c
global FindFirstFileA_asm2c
global FindNextFileA_asm2c
global FindWindowA_asm2c
global floor_asm2c
global FlushFileBuffers_asm2c
global fopen_asm2c
global fprintf_asm2c
global fputc_asm2c
global fputs_asm2c
global fread_asm2c
global free_asm2c
global FreeLibrary_asm2c
global fscanf_asm2c
global fseek_asm2c
global ftell_asm2c
global fwrite_asm2c
global GdiFlush_asm2c
global GetAsyncKeyState_asm2c
global getc_asm2c
global GetClientRect_asm2c
global GetCPInfo_asm2c
global GetCurrentDirectoryA_asm2c
global GetCurrentProcess_asm2c
global GetCurrentThreadId_asm2c
global GetCursorPos_asm2c
global GetDC_asm2c
global GetDeviceCaps_asm2c
global GetDlgItem_asm2c
global GetDlgItemTextA_asm2c
global GetDriveTypeA_asm2c
global GetFileTime_asm2c
global GetFileType_asm2c
global GetFocus_asm2c
global GetKeyboardType_asm2c
global GetKeyState_asm2c
global GetLastError_asm2c
global GetLocaleInfoA_asm2c
global GetLocaleInfoW_asm2c
global GetLogicalDrives_asm2c
global GetLogicalDriveStringsA_asm2c
global GetModuleFileNameA_asm2c
global GetModuleHandleA_asm2c
global GetProcAddress_asm2c
global GetProcessHeap_asm2c
global GetStdHandle_asm2c
global GetStockObject_asm2c
global GetStringTypeA_asm2c
global GetStringTypeW_asm2c
global GetSystemDefaultLCID_asm2c
global GetSystemInfo_asm2c
global GetSystemMetrics_asm2c
global GetSystemPaletteEntries_asm2c
global GetTextExtentExPointA_asm2c
global GetTextExtentPoint32A_asm2c
global GetTickCount_asm2c
global GetVolumeInformationA_asm2c
global GetWindowLongA_asm2c
global GetWindowRect_asm2c
global GetWindowsDirectoryA_asm2c
global HeapAlloc_asm2c
global HeapCompact_asm2c
global HeapCreate_asm2c
global HeapDestroy_asm2c
global HeapFree_asm2c
global HeapReAlloc_asm2c
global HeapSize_asm2c
global ImmAssociateContext_asm2c
global InitializeCriticalSection_asm2c
global InterlockedDecrement_asm2c
global InterlockedIncrement_asm2c
global isspace_asm2c
global joyGetDevCapsA_asm2c
global joyGetNumDevs_asm2c
global joyGetPos_asm2c
global joyGetPosEx_asm2c
global LCMapStringA_asm2c
global LCMapStringW_asm2c
global LeaveCriticalSection_asm2c
global LoadCursorA_asm2c
global LoadCursorFromFileA_asm2c
global LoadLibraryA_asm2c
global LoadModule_asm2c
global lstrcatA_asm2c
global lstrcpyA_asm2c
global malloc_asm2c
global MapViewOfFile_asm2c
global MapVirtualKeyA_asm2c
global mciGetErrorStringA_asm2c
global mciSendCommandA_asm2c
global memmove_asm2c
global MessageBoxA_asm2c
global MultiByteToWideChar_asm2c
global OutputDebugStringA_asm2c
global PeekMessageA_asm2c
global PostMessageA_asm2c
global PostQuitMessage_asm2c
global qsort_asm2c
global rand_asm2c
global ReadFile_asm2c
global RealizePalette_asm2c
global realloc_asm2c
global Rectangle_asm2c
global RegCloseKey_asm2c
global RegCreateKeyExA_asm2c
global RegisterClassA_asm2c
global RegOpenKeyExA_asm2c
global RegQueryValueExA_asm2c
global RegSetValueExA_asm2c
global ReleaseDC_asm2c
global RemoveFontResourceA_asm2c
global ScreenToClient_asm2c
global SelectObject_asm2c
global SelectPalette_asm2c
global SendDlgItemMessageA_asm2c
global SendMessageA_asm2c
global SetBkColor_asm2c
global SetBkMode_asm2c
global SetCursor_asm2c
global SetCursorPos_asm2c
global SetDIBColorTable_asm2c
global SetDIBitsToDevice_asm2c
global SetDlgItemTextA_asm2c
global SetEndOfFile_asm2c
global SetFileAttributesA_asm2c
global SetFilePointer_asm2c
global SetFocus_asm2c
global SetLastError_asm2c
global setlocale_asm2c
global SetMapperFlags_asm2c
global SetMenu_asm2c
global SetPaletteEntries_asm2c
global SetPriorityClass_asm2c
global SetRect_asm2c
global SetStdHandle_asm2c
global SetSystemPaletteUse_asm2c
global SetTextColor_asm2c
global setvbuf_asm2c
global SetWindowLongA_asm2c
global SetWindowPos_asm2c
global ShowCursor_asm2c
global ShowWindow_asm2c
global Sleep_asm2c
global SmackBufferBlit_asm2c
global SmackBufferClose_asm2c
global SmackBufferNewPalette_asm2c
global SmackBufferOpen_asm2c
global SmackBufferSetPalette_asm2c
global SmackClose_asm2c
global SmackColorRemap_asm2c
global SmackDoFrame_asm2c
global SmackNextFrame_asm2c
global SmackOpen_asm2c
global SmackSoundOnOff_asm2c
global SmackSoundUseDirectSound_asm2c
global SmackToBuffer_asm2c
global SmackToBufferRect_asm2c
global SmackWait_asm2c
global sprintf_asm2c
global srand_asm2c
global sscanf_asm2c
global strchr_asm2c
global StretchBlt_asm2c
global strncmp_asm2c
global strncpy_asm2c
global strpbrk_asm2c
global strrchr_asm2c
global strstr_asm2c
global strtok_asm2c
global TerminateProcess_asm2c
global TextOutA_asm2c
global time_asm2c
global timeGetTime_asm2c
global TlsGetValue_asm2c
global TlsSetValue_asm2c
global ToAscii_asm2c
global tolower_asm2c
global toupper_asm2c
global TranslateMessage_asm2c
global UnmapViewOfFile_asm2c
global UpdateWindow_asm2c
global ValidateRect_asm2c
global VirtualAlloc_asm2c
global VirtualFree_asm2c
global VirtualQuery_asm2c
global WaitForSingleObject_asm2c
global WideCharToMultiByte_asm2c
global WriteFile_asm2c
global wsprintfA_asm2c
global wvsprintfA_asm2c
global strspn_asm2c
global strcspn_asm2c
global strncat_asm2c
global vsprintf_asm2c
global memcpy_asm2c
global printf_asm2c
global ungetc_asm2c
global _filbuf_asm2c
global i76_frame_tick_asm2c
global i76shell_part_strncmp_asm2c

%ifidn __OUTPUT_FORMAT__, elf32
section .note.GNU-stack noalloc noexec nowrite progbits
section .text progbits alloc exec nowrite align=16
%else
section .text code align=16
%endif

align 16
operator_new_asm2c:
; ??2@YAPAXI@Z (c1, MSVCRT.dll)
        Call_Asm_Stack1 operator_new_c

align 16
operator_delete_asm2c:
; ??3@YAXPAX@Z (c1, MSVCRT.dll)
        Call_Asm_Stack1 operator_delete_c

align 16
_access_asm2c:
; _access (c2, MSVCRT.dll)
        Call_Asm_Stack2 _access_c

align 16
_assert_asm2c:
; _assert (c3, MSVCRT.dll)
        Call_Asm_Stack3 _assert_c

align 16
_CIacos_asm2c:
; _CIacos (f1f, MSVCRT.dll)
        Call_Asm_Float1_Float _CIacos_c

align 16
_CIasin_asm2c:
; _CIasin (f1f, MSVCRT.dll)
        Call_Asm_Float1_Float _CIasin_c

align 16
_CIatan2_asm2c:
; _CIatan2 (f2f, MSVCRT.dll)
        Call_Asm_Float2_Float _CIatan2_c

align 16
_CIfmod_asm2c:
; _CIfmod (f2f, MSVCRT.dll)
        Call_Asm_Float2_Float _CIfmod_c

align 16
_CIpow_asm2c:
; _CIpow (f2f, MSVCRT.dll)
        Call_Asm_Float2_Float _CIpow_c

align 16
_close_asm2c:
; _close (c1, MSVCRT.dll)
        Call_Asm_Stack1 _close_c

align 16
_errno_asm2c:
; _errno (c0, MSVCRT.dll)
        Call_Asm_Stack0 _errno_c

align 16
_findclose_asm2c:
; _findclose (c1, MSVCRT.dll)
        Call_Asm_Stack1 _findclose_c

align 16
_findfirst_asm2c:
; _findfirst (c2, MSVCRT.dll)
        Call_Asm_Stack2 _findfirst_c

align 16
_findnext_asm2c:
; _findnext (c2, MSVCRT.dll)
        Call_Asm_Stack2 _findnext_c

align 16
grAlphaBlendFunction_asm2c:
; _grAlphaBlendFunction@16 (std4, glide2x.dll)
        Call_Asm_Stack4 grAlphaBlendFunction_c, 4

align 16
grAlphaCombine_asm2c:
; _grAlphaCombine@20 (std5, glide2x.dll)
        Call_Asm_Stack5 grAlphaCombine_c, 5

align 16
grBufferClear_asm2c:
; _grBufferClear@12 (std3, glide2x.dll)
        Call_Asm_Stack3 grBufferClear_c, 3

align 16
grBufferSwap_asm2c:
; _grBufferSwap@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grBufferSwap_c, 1

align 16
grChromakeyMode_asm2c:
; _grChromakeyMode@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grChromakeyMode_c, 1

align 16
grChromakeyValue_asm2c:
; _grChromakeyValue@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grChromakeyValue_c, 1

align 16
grColorCombine_asm2c:
; _grColorCombine@20 (std5, glide2x.dll)
        Call_Asm_Stack5 grColorCombine_c, 5

align 16
grConstantColorValue_asm2c:
; _grConstantColorValue@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grConstantColorValue_c, 1

align 16
grCullMode_asm2c:
; _grCullMode@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grCullMode_c, 1

align 16
grDepthBufferFunction_asm2c:
; _grDepthBufferFunction@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grDepthBufferFunction_c, 1

align 16
grDepthBufferMode_asm2c:
; _grDepthBufferMode@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grDepthBufferMode_c, 1

align 16
grDepthMask_asm2c:
; _grDepthMask@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grDepthMask_c, 1

align 16
grDrawLine_asm2c:
; _grDrawLine@8 (std2, glide2x.dll)
        Call_Asm_Stack2 grDrawLine_c, 2

align 16
grDrawPoint_asm2c:
; _grDrawPoint@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grDrawPoint_c, 1

align 16
grDrawTriangle_asm2c:
; _grDrawTriangle@12 (std3, glide2x.dll)
        Call_Asm_Stack3 grDrawTriangle_c, 3

align 16
grFogColorValue_asm2c:
; _grFogColorValue@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grFogColorValue_c, 1

align 16
grFogMode_asm2c:
; _grFogMode@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grFogMode_c, 1

align 16
grGlideGetState_asm2c:
; _grGlideGetState@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grGlideGetState_c, 1

align 16
grGlideInit_asm2c:
; _grGlideInit@0 (std0, glide2x.dll)
        Call_Asm_Stack0 grGlideInit_c, 0

align 16
grGlideSetState_asm2c:
; _grGlideSetState@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grGlideSetState_c, 1

align 16
grGlideShutdown_asm2c:
; _grGlideShutdown@0 (std0, glide2x.dll)
        Call_Asm_Stack0 grGlideShutdown_c, 0

align 16
grLfbLock_asm2c:
; _grLfbLock@24 (std6, glide2x.dll)
        Call_Asm_Stack6 grLfbLock_c, 6

align 16
grLfbUnlock_asm2c:
; _grLfbUnlock@8 (std2, glide2x.dll)
        Call_Asm_Stack2 grLfbUnlock_c, 2

align 16
grRenderBuffer_asm2c:
; _grRenderBuffer@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grRenderBuffer_c, 1

align 16
grSstQueryBoards_asm2c:
; _grSstQueryBoards@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grSstQueryBoards_c, 1

align 16
grSstQueryHardware_asm2c:
; _grSstQueryHardware@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grSstQueryHardware_c, 1

align 16
grSstSelect_asm2c:
; _grSstSelect@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grSstSelect_c, 1

align 16
grSstWinClose_asm2c:
; _grSstWinClose@0 (std0, glide2x.dll)
        Call_Asm_Stack0 grSstWinClose_c, 0

align 16
grSstWinOpen_asm2c:
; _grSstWinOpen@28 (std7, glide2x.dll)
        Call_Asm_Stack7 grSstWinOpen_c, 7

align 16
grTexCalcMemRequired_asm2c:
; _grTexCalcMemRequired@16 (std4, glide2x.dll)
        Call_Asm_Stack4 grTexCalcMemRequired_c, 4

align 16
grTexClampMode_asm2c:
; _grTexClampMode@12 (std3, glide2x.dll)
        Call_Asm_Stack3 grTexClampMode_c, 3

align 16
grTexCombine_asm2c:
; _grTexCombine@28 (std7, glide2x.dll)
        Call_Asm_Stack7 grTexCombine_c, 7

align 16
grTexDownloadMipMap_asm2c:
; _grTexDownloadMipMap@16 (std4, glide2x.dll)
        Call_Asm_Stack4 grTexDownloadMipMap_c, 4

align 16
grTexDownloadTable_asm2c:
; _grTexDownloadTable@12 (std3, glide2x.dll)
        Call_Asm_Stack3 grTexDownloadTable_c, 3

align 16
grTexFilterMode_asm2c:
; _grTexFilterMode@12 (std3, glide2x.dll)
        Call_Asm_Stack3 grTexFilterMode_c, 3

align 16
grTexMaxAddress_asm2c:
; _grTexMaxAddress@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grTexMaxAddress_c, 1

align 16
grTexMinAddress_asm2c:
; _grTexMinAddress@4 (std1, glide2x.dll)
        Call_Asm_Stack1 grTexMinAddress_c, 1

align 16
grTexMipMapMode_asm2c:
; _grTexMipMapMode@12 (std3, glide2x.dll)
        Call_Asm_Stack3 grTexMipMapMode_c, 3

align 16
grTexSource_asm2c:
; _grTexSource@16 (std4, glide2x.dll)
        Call_Asm_Stack4 grTexSource_c, 4

align 16
_isctype_asm2c:
; _isctype (c2, MSVCRT.dll)
        Call_Asm_Stack2 _isctype_c

align 16
_ismbcalnum_asm2c:
; _ismbcalnum (c1, MSVCRT.dll)
        Call_Asm_Stack1 _ismbcalnum_c

align 16
_ismbcpunct_asm2c:
; _ismbcpunct (c1, MSVCRT.dll)
        Call_Asm_Stack1 _ismbcpunct_c

align 16
_ismbcspace_asm2c:
; _ismbcspace (c1, MSVCRT.dll)
        Call_Asm_Stack1 _ismbcspace_c

align 16
_isnan_asm2c:
; _isnan (c2, MSVCRT.dll)
        Call_Asm_Stack2 _isnan_c

align 16
_itoa_asm2c:
; _itoa (c3, MSVCRT.dll)
        Call_Asm_Stack3 _itoa_c

align 16
_lseek_asm2c:
; _lseek (c3, MSVCRT.dll)
        Call_Asm_Stack3 _lseek_c

align 16
_mbsicmp_asm2c:
; _mbsicmp (c2, MSVCRT.dll)
        Call_Asm_Stack2 _mbsicmp_c

align 16
_mbsnbcat_asm2c:
; _mbsnbcat (c3, MSVCRT.dll)
        Call_Asm_Stack3 _mbsnbcat_c

align 16
_mbsnbcpy_asm2c:
; _mbsnbcpy (c3, MSVCRT.dll)
        Call_Asm_Stack3 _mbsnbcpy_c

align 16
_mbsnbicmp_asm2c:
; _mbsnbicmp (c3, MSVCRT.dll)
        Call_Asm_Stack3 _mbsnbicmp_c

align 16
_mkdir_asm2c:
; _mkdir (c1, MSVCRT.dll)
        Call_Asm_Stack1 _mkdir_c

align 16
_msize_asm2c:
; _msize (c1, MSVCRT.dll)
        Call_Asm_Stack1 _msize_c

align 16
_open_asm2c:
; _open (v2, MSVCRT.dll)
        Call_Asm_VariableStack2 _open_c

align 16
_putch_asm2c:
; _putch (c1, MSVCRT.dll)
        Call_Asm_Stack1 _putch_c

align 16
_read_asm2c:
; _read (c3, MSVCRT.dll)
        Call_Asm_Stack3 _read_c

align 16
_splitpath_asm2c:
; _splitpath (c5, MSVCRT.dll)
        Call_Asm_Stack5 _splitpath_c

align 16
_stat_asm2c:
; _stat (c2, MSVCRT.dll)
        Call_Asm_Stack2 _stat_c

align 16
_stricmp_asm2c:
; _stricmp (c2, MSVCRT.dll)
        Call_Asm_Stack2 _stricmp_c

align 16
_strlwr_asm2c:
; _strlwr (c1, MSVCRT.dll)
        Call_Asm_Stack1 _strlwr_c

align 16
_strnicmp_asm2c:
; _strnicmp (c3, MSVCRT.dll)
        Call_Asm_Stack3 _strnicmp_c

align 16
_unlink_asm2c:
; _unlink (c1, MSVCRT.dll)
        Call_Asm_Stack1 _unlink_c

align 16
_vsnprintf_asm2c:
; _vsnprintf (c4, MSVCRT.dll)
        Call_Asm_Stack4 _vsnprintf_c

align 16
abort_asm2c:
; abort (c0, MSVCRT.dll)
        Call_Asm_Stack0 abort_c

align 16
AddFontResourceA_asm2c:
; AddFontResourceA (std1, GDI32.dll)
        Call_Asm_Stack1 AddFontResourceA_c, 1

align 16
AdjustWindowRect_asm2c:
; AdjustWindowRect (std3, USER32.dll)
        Call_Asm_Stack3 AdjustWindowRect_c, 3

align 16
atoi_asm2c:
; atoi (c1, MSVCRT.dll)
        Call_Asm_Stack1 atoi_c

align 16
atol_asm2c:
; atol (c1, MSVCRT.dll)
        Call_Asm_Stack1 atol_c

align 16
auxGetDevCapsA_asm2c:
; auxGetDevCapsA (std3, WIN32.dll)
        Call_Asm_Stack3 auxGetDevCapsA_c, 3

align 16
auxGetNumDevs_asm2c:
; auxGetNumDevs (std0, WIN32.dll)
        Call_Asm_Stack0 auxGetNumDevs_c, 0

align 16
auxSetVolume_asm2c:
; auxSetVolume (std2, WIN32.dll)
        Call_Asm_Stack2 auxSetVolume_c, 2

align 16
BeginPaint_asm2c:
; BeginPaint (std2, USER32.dll)
        Call_Asm_Stack2 BeginPaint_c, 2

align 16
BitBlt_asm2c:
; BitBlt (std9, GDI32.dll)
        Call_Asm_Stack9 BitBlt_c, 9

align 16
bsearch_asm2c:
; bsearch (c5, MSVCRT.dll)
        Call_Asm_Stack5 bsearch_c

align 16
calloc_asm2c:
; calloc (c2, MSVCRT.dll)
        Call_Asm_Stack2 calloc_c

align 16
ClientToScreen_asm2c:
; ClientToScreen (std2, USER32.dll)
        Call_Asm_Stack2 ClientToScreen_c, 2

align 16
ClipCursor_asm2c:
; ClipCursor (std1, USER32.dll)
        Call_Asm_Stack1 ClipCursor_c, 1

align 16
clock_asm2c:
; clock (c0, MSVCRT.dll)
        Call_Asm_Stack0 clock_c

align 16
CloseHandle_asm2c:
; CloseHandle (std1, KERNEL32.dll)
        Call_Asm_Stack1 CloseHandle_c, 1

align 16
CoInitialize_asm2c:
; CoInitialize (std1, ole32.dll)
        Call_Asm_Stack1 CoInitialize_c, 1

align 16
CopyFileA_asm2c:
; CopyFileA (std3, KERNEL32.dll)
        Call_Asm_Stack3 CopyFileA_c, 3

align 16
CoUninitialize_asm2c:
; CoUninitialize (std0, ole32.dll)
        Call_Asm_Stack0 CoUninitialize_c, 0

align 16
CreateCompatibleDC_asm2c:
; CreateCompatibleDC (std1, GDI32.dll)
        Call_Asm_Stack1 CreateCompatibleDC_c, 1

align 16
CreateDIBSection_asm2c:
; CreateDIBSection (std6, GDI32.dll)
        Call_Asm_Stack6 CreateDIBSection_c, 6

align 16
CreateFileA_asm2c:
; CreateFileA (std7, KERNEL32.dll)
        Call_Asm_Stack7 CreateFileA_c, 7

align 16
CreateFileMappingA_asm2c:
; CreateFileMappingA (std6, KERNEL32.dll)
        Call_Asm_Stack6 CreateFileMappingA_c, 6

align 16
CreateFontIndirectA_asm2c:
; CreateFontIndirectA (std1, GDI32.dll)
        Call_Asm_Stack1 CreateFontIndirectA_c, 1

align 16
CreatePalette_asm2c:
; CreatePalette (std1, GDI32.dll)
        Call_Asm_Stack1 CreatePalette_c, 1

align 16
CreateProcessA_asm2c:
; CreateProcessA (std10, KERNEL32.dll)
        Call_Asm_Stack10 CreateProcessA_c, 10

align 16
CreateScalableFontResourceA_asm2c:
; CreateScalableFontResourceA (std4, GDI32.dll)
        Call_Asm_Stack4 CreateScalableFontResourceA_c, 4

align 16
CreateThread_asm2c:
; CreateThread (std6, KERNEL32.dll)
        Call_Asm_Stack6 CreateThread_c, 6

align 16
CreateWindowExA_asm2c:
; CreateWindowExA (std12, USER32.dll)
        Call_Asm_Stack12 CreateWindowExA_c, 12

align 16
DefWindowProcA_asm2c:
; DefWindowProcA (std4, USER32.dll)
        Call_Asm_Stack4 DefWindowProcA_c, 4

align 16
DeleteCriticalSection_asm2c:
; DeleteCriticalSection (std1, KERNEL32.dll)
        Call_Asm_Stack1 DeleteCriticalSection_c, 1

align 16
DeleteDC_asm2c:
; DeleteDC (std1, GDI32.dll)
        Call_Asm_Stack1 DeleteDC_c, 1

align 16
DeleteFileA_asm2c:
; DeleteFileA (std1, KERNEL32.dll)
        Call_Asm_Stack1 DeleteFileA_c, 1

align 16
DeleteObject_asm2c:
; DeleteObject (std1, GDI32.dll)
        Call_Asm_Stack1 DeleteObject_c, 1

align 16
DestroyWindow_asm2c:
; DestroyWindow (std1, USER32.dll)
        Call_Asm_Stack1 DestroyWindow_c, 1

align 16
DialogBoxParamA_asm2c:
; DialogBoxParamA (std5, USER32.dll)
        Call_Asm_Stack5 DialogBoxParamA_c, 5

align 16
difftime_asm2c:
; difftime (c2, MSVCRT.dll)
        Call_Asm_Stack2 difftime_c

align 16
DirectDrawCreate_asm2c:
; DirectDrawCreate (std3, DDRAW.dll)
        Call_Asm_Stack3 DirectDrawCreate_c, 3

align 16
DirectDrawEnumerateA_asm2c:
; DirectDrawEnumerateA (std2, DDRAW.dll)
        Call_Asm_Stack2 DirectDrawEnumerateA_c, 2

align 16
DirectSoundCreate_asm2c:
; DirectSoundCreate (std3, DSOUND.dll)
        Call_Asm_Stack3 DirectSoundCreate_c, 3

align 16
DispatchMessageA_asm2c:
; DispatchMessageA (std1, USER32.dll)
        Call_Asm_Stack1 DispatchMessageA_c, 1

align 16
msvcrt_div_asm2c:
; msvcrt_div (c2, MSVCRT.dll)
        Call_Asm_Stack2 msvcrt_div_c

align 16
dp_enableDebugPrint_asm2c:
; dp_enableDebugPrint (c1, anetdll.dll)
        Call_Asm_Stack1 dp_enableDebugPrint_c

align 16
dpAddPlayerToGroup_asm2c:
; dpAddPlayerToGroup (c3, anetdll.dll)
        Call_Asm_Stack3 dpAddPlayerToGroup_c

align 16
dpClose_asm2c:
; dpClose (c1, anetdll.dll)
        Call_Asm_Stack1 dpClose_c

align 16
dpCreate_asm2c:
; dpCreate (c4, anetdll.dll)
        Call_Asm_Stack4 dpCreate_c

align 16
dpCreateGroup_asm2c:
; dpCreateGroup (c3, anetdll.dll)
        Call_Asm_Stack3 dpCreateGroup_c

align 16
dpCreatePlayer_asm2c:
; dpCreatePlayer (c4, anetdll.dll)
        Call_Asm_Stack4 dpCreatePlayer_c

align 16
dpDestroy_asm2c:
; dpDestroy (c2, anetdll.dll)
        Call_Asm_Stack2 dpDestroy_c

align 16
dpDestroyPlayer_asm2c:
; dpDestroyPlayer (c2, anetdll.dll)
        Call_Asm_Stack2 dpDestroyPlayer_c

align 16
dpEnumGroupPlayers_asm2c:
; dpEnumGroupPlayers (c6, anetdll.dll)
        Call_Asm_Stack6 dpEnumGroupPlayers_c

align 16
dpEnumGroups_asm2c:
; dpEnumGroups (c5, anetdll.dll)
        Call_Asm_Stack5 dpEnumGroups_c

align 16
dpEnumPlayers_asm2c:
; dpEnumPlayers (c5, anetdll.dll)
        Call_Asm_Stack5 dpEnumPlayers_c

align 16
dpEnumSessions_asm2c:
; dpEnumSessions (c6, anetdll.dll)
        Call_Asm_Stack6 dpEnumSessions_c

align 16
dpFreeze_asm2c:
; dpFreeze (c2, anetdll.dll)
        Call_Asm_Stack2 dpFreeze_c

align 16
dpEnumTransports_asm2c:
; dpEnumTransports (c3, anetdll.dll)
        Call_Asm_Stack3 dpEnumTransports_c

align 16
dpGetPlayerData_asm2c:
; dpGetPlayerData (c6, anetdll.dll)
        Call_Asm_Stack6 dpGetPlayerData_c

align 16
dpGetPlayerName_asm2c:
; dpGetPlayerName (c4, anetdll.dll)
        Call_Asm_Stack4 dpGetPlayerName_c

align 16
dpGetSessionDesc_asm2c:
; dpGetSessionDesc (c3, anetdll.dll)
        Call_Asm_Stack3 dpGetSessionDesc_c

align 16
dpOpen_asm2c:
; dpOpen (c4, anetdll.dll)
        Call_Asm_Stack4 dpOpen_c

align 16
dpReceive_asm2c:
; dpReceive (c6, anetdll.dll)
        Call_Asm_Stack6 dpReceive_c

align 16
dpSend_asm2c:
; dpSend (c6, anetdll.dll)
        Call_Asm_Stack6 dpSend_c

align 16
dpSetGameServer_asm2c:
; dpSetGameServer (c2, anetdll.dll)
        Call_Asm_Stack2 dpSetGameServer_c

align 16
dpSetPlayerData_asm2c:
; dpSetPlayerData (c6, anetdll.dll)
        Call_Asm_Stack6 dpSetPlayerData_c

align 16
EndDialog_asm2c:
; EndDialog (std2, USER32.dll)
        Call_Asm_Stack2 EndDialog_c, 2

align 16
EndPaint_asm2c:
; EndPaint (std2, USER32.dll)
        Call_Asm_Stack2 EndPaint_c, 2

align 16
EnterCriticalSection_asm2c:
; EnterCriticalSection (std1, KERNEL32.dll)
        Call_Asm_Stack1 EnterCriticalSection_c, 1

align 16
exit_asm2c:
; exit (c1, MSVCRT.dll)
        Call_Asm_Stack1 exit_c

align 16
ExitProcess_asm2c:
; ExitProcess (std1, KERNEL32.dll)
        Call_Asm_Stack1 ExitProcess_c, 1

align 16
fclose_asm2c:
; fclose (c1, MSVCRT.dll)
        Call_Asm_Stack1 fclose_c

align 16
fflush_asm2c:
; fflush (c1, MSVCRT.dll)
        Call_Asm_Stack1 fflush_c

align 16
fgetc_asm2c:
; fgetc (c1, MSVCRT.dll)
        Call_Asm_Stack1 fgetc_c

align 16
fgets_asm2c:
; fgets (c3, MSVCRT.dll)
        Call_Asm_Stack3 fgets_c

align 16
FindClose_asm2c:
; FindClose (std1, KERNEL32.dll)
        Call_Asm_Stack1 FindClose_c, 1

align 16
FindFirstFileA_asm2c:
; FindFirstFileA (std2, KERNEL32.dll)
        Call_Asm_Stack2 FindFirstFileA_c, 2

align 16
FindNextFileA_asm2c:
; FindNextFileA (std2, KERNEL32.dll)
        Call_Asm_Stack2 FindNextFileA_c, 2

align 16
FindWindowA_asm2c:
; FindWindowA (std2, USER32.dll)
        Call_Asm_Stack2 FindWindowA_c, 2

align 16
floor_asm2c:
; floor (c2, MSVCRT.dll)
        Call_Asm_Stack2 floor_c

align 16
FlushFileBuffers_asm2c:
; FlushFileBuffers (std1, KERNEL32.dll)
        Call_Asm_Stack1 FlushFileBuffers_c, 1

align 16
fopen_asm2c:
; fopen (c2, MSVCRT.dll)
        Call_Asm_Stack2 fopen_c

align 16
fprintf_asm2c:
; fprintf (v2, MSVCRT.dll)
        Call_Asm_VariableStack2 fprintf_c

align 16
fputc_asm2c:
; fputc (c2, MSVCRT.dll)
        Call_Asm_Stack2 fputc_c

align 16
fputs_asm2c:
; fputs (c2, MSVCRT.dll)
        Call_Asm_Stack2 fputs_c

align 16
fread_asm2c:
; fread (c4, MSVCRT.dll)
        Call_Asm_Stack4 fread_c

align 16
free_asm2c:
; free (c1, MSVCRT.dll)
        Call_Asm_Stack1 free_c

align 16
FreeLibrary_asm2c:
; FreeLibrary (std1, KERNEL32.dll)
        Call_Asm_Stack1 FreeLibrary_c, 1

align 16
fscanf_asm2c:
; fscanf (v2, MSVCRT.dll)
        Call_Asm_VariableStack2 fscanf_c

align 16
fseek_asm2c:
; fseek (c3, MSVCRT.dll)
        Call_Asm_Stack3 fseek_c

align 16
ftell_asm2c:
; ftell (c1, MSVCRT.dll)
        Call_Asm_Stack1 ftell_c

align 16
fwrite_asm2c:
; fwrite (c4, MSVCRT.dll)
        Call_Asm_Stack4 fwrite_c

align 16
GdiFlush_asm2c:
; GdiFlush (std0, GDI32.dll)
        Call_Asm_Stack0 GdiFlush_c, 0

align 16
GetAsyncKeyState_asm2c:
; GetAsyncKeyState (std1, USER32.dll)
        Call_Asm_Stack1 GetAsyncKeyState_c, 1

align 16
getc_asm2c:
; getc (c1, MSVCRT.dll)
        Call_Asm_Stack1 getc_c

align 16
GetClientRect_asm2c:
; GetClientRect (std2, USER32.dll)
        Call_Asm_Stack2 GetClientRect_c, 2

align 16
GetCPInfo_asm2c:
; GetCPInfo (std2, KERNEL32.dll)
        Call_Asm_Stack2 GetCPInfo_c, 2

align 16
GetCurrentDirectoryA_asm2c:
; GetCurrentDirectoryA (std2, KERNEL32.dll)
        Call_Asm_Stack2 GetCurrentDirectoryA_c, 2

align 16
GetCurrentProcess_asm2c:
; GetCurrentProcess (std0, KERNEL32.dll)
        Call_Asm_Stack0 GetCurrentProcess_c, 0

align 16
GetCurrentThreadId_asm2c:
; GetCurrentThreadId (std0, KERNEL32.dll)
        Call_Asm_Stack0 GetCurrentThreadId_c, 0

align 16
GetCursorPos_asm2c:
; GetCursorPos (std1, USER32.dll)
        Call_Asm_Stack1 GetCursorPos_c, 1

align 16
GetDC_asm2c:
; GetDC (std1, USER32.dll)
        Call_Asm_Stack1 GetDC_c, 1

align 16
GetDeviceCaps_asm2c:
; GetDeviceCaps (std2, GDI32.dll)
        Call_Asm_Stack2 GetDeviceCaps_c, 2

align 16
GetDlgItem_asm2c:
; GetDlgItem (std2, USER32.dll)
        Call_Asm_Stack2 GetDlgItem_c, 2

align 16
GetDlgItemTextA_asm2c:
; GetDlgItemTextA (std4, USER32.dll)
        Call_Asm_Stack4 GetDlgItemTextA_c, 4

align 16
GetDriveTypeA_asm2c:
; GetDriveTypeA (std1, KERNEL32.dll)
        Call_Asm_Stack1 GetDriveTypeA_c, 1

align 16
GetFileTime_asm2c:
; GetFileTime (std4, KERNEL32.dll)
        Call_Asm_Stack4 GetFileTime_c, 4

align 16
GetFileType_asm2c:
; GetFileType (std1, KERNEL32.dll)
        Call_Asm_Stack1 GetFileType_c, 1

align 16
GetFocus_asm2c:
; GetFocus (std0, USER32.dll)
        Call_Asm_Stack0 GetFocus_c, 0

align 16
GetKeyboardType_asm2c:
; GetKeyboardType (std1, USER32.dll)
        Call_Asm_Stack1 GetKeyboardType_c, 1

align 16
GetKeyState_asm2c:
; GetKeyState (std1, USER32.dll)
        Call_Asm_Stack1 GetKeyState_c, 1

align 16
GetLastError_asm2c:
; GetLastError (std0, KERNEL32.dll)
        Call_Asm_Stack0 GetLastError_c, 0

align 16
GetLocaleInfoA_asm2c:
; GetLocaleInfoA (std4, KERNEL32.dll)
        Call_Asm_Stack4 GetLocaleInfoA_c, 4

align 16
GetLocaleInfoW_asm2c:
; GetLocaleInfoW (std4, KERNEL32.dll)
        Call_Asm_Stack4 GetLocaleInfoW_c, 4

align 16
GetLogicalDrives_asm2c:
; GetLogicalDrives (std0, KERNEL32.dll)
        Call_Asm_Stack0 GetLogicalDrives_c, 0

align 16
GetLogicalDriveStringsA_asm2c:
; GetLogicalDriveStringsA (std2, KERNEL32.dll)
        Call_Asm_Stack2 GetLogicalDriveStringsA_c, 2

align 16
GetModuleFileNameA_asm2c:
; GetModuleFileNameA (std3, KERNEL32.dll)
        Call_Asm_Stack3 GetModuleFileNameA_c, 3

align 16
GetModuleHandleA_asm2c:
; GetModuleHandleA (std1, KERNEL32.dll)
        Call_Asm_Stack1 GetModuleHandleA_c, 1

align 16
GetProcAddress_asm2c:
; GetProcAddress (std2, KERNEL32.dll)
        Call_Asm_Stack2 GetProcAddress_c, 2

align 16
GetProcessHeap_asm2c:
; GetProcessHeap (std0, KERNEL32.dll)
        Call_Asm_Stack0 GetProcessHeap_c, 0

align 16
GetStdHandle_asm2c:
; GetStdHandle (std1, KERNEL32.dll)
        Call_Asm_Stack1 GetStdHandle_c, 1

align 16
GetStockObject_asm2c:
; GetStockObject (std1, GDI32.dll)
        Call_Asm_Stack1 GetStockObject_c, 1

align 16
GetStringTypeA_asm2c:
; GetStringTypeA (std5, KERNEL32.dll)
        Call_Asm_Stack5 GetStringTypeA_c, 5

align 16
GetStringTypeW_asm2c:
; GetStringTypeW (std4, KERNEL32.dll)
        Call_Asm_Stack4 GetStringTypeW_c, 4

align 16
GetSystemDefaultLCID_asm2c:
; GetSystemDefaultLCID (std0, KERNEL32.dll)
        Call_Asm_Stack0 GetSystemDefaultLCID_c, 0

align 16
GetSystemInfo_asm2c:
; GetSystemInfo (std1, KERNEL32.dll)
        Call_Asm_Stack1 GetSystemInfo_c, 1

align 16
GetSystemMetrics_asm2c:
; GetSystemMetrics (std1, USER32.dll)
        Call_Asm_Stack1 GetSystemMetrics_c, 1

align 16
GetSystemPaletteEntries_asm2c:
; GetSystemPaletteEntries (std4, GDI32.dll)
        Call_Asm_Stack4 GetSystemPaletteEntries_c, 4

align 16
GetTextExtentExPointA_asm2c:
; GetTextExtentExPointA (std7, GDI32.dll)
        Call_Asm_Stack7 GetTextExtentExPointA_c, 7

align 16
GetTextExtentPoint32A_asm2c:
; GetTextExtentPoint32A (std4, GDI32.dll)
        Call_Asm_Stack4 GetTextExtentPoint32A_c, 4

align 16
GetTickCount_asm2c:
; GetTickCount (std0, KERNEL32.dll)
        Call_Asm_Stack0 GetTickCount_c, 0

align 16
GetVolumeInformationA_asm2c:
; GetVolumeInformationA (std8, KERNEL32.dll)
        Call_Asm_Stack8 GetVolumeInformationA_c, 8

align 16
GetWindowLongA_asm2c:
; GetWindowLongA (std2, USER32.dll)
        Call_Asm_Stack2 GetWindowLongA_c, 2

align 16
GetWindowRect_asm2c:
; GetWindowRect (std2, USER32.dll)
        Call_Asm_Stack2 GetWindowRect_c, 2

align 16
GetWindowsDirectoryA_asm2c:
; GetWindowsDirectoryA (std2, KERNEL32.dll)
        Call_Asm_Stack2 GetWindowsDirectoryA_c, 2

align 16
HeapAlloc_asm2c:
; HeapAlloc (std3, KERNEL32.dll)
        Call_Asm_Stack3 HeapAlloc_c, 3

align 16
HeapCompact_asm2c:
; HeapCompact (std2, KERNEL32.dll)
        Call_Asm_Stack2 HeapCompact_c, 2

align 16
HeapCreate_asm2c:
; HeapCreate (std3, KERNEL32.dll)
        Call_Asm_Stack3 HeapCreate_c, 3

align 16
HeapDestroy_asm2c:
; HeapDestroy (std1, KERNEL32.dll)
        Call_Asm_Stack1 HeapDestroy_c, 1

align 16
HeapFree_asm2c:
; HeapFree (std3, KERNEL32.dll)
        Call_Asm_Stack3 HeapFree_c, 3

align 16
HeapReAlloc_asm2c:
; HeapReAlloc (std4, KERNEL32.dll)
        Call_Asm_Stack4 HeapReAlloc_c, 4

align 16
HeapSize_asm2c:
; HeapSize (std3, KERNEL32.dll)
        Call_Asm_Stack3 HeapSize_c, 3

align 16
ImmAssociateContext_asm2c:
; ImmAssociateContext (std2, IMM32.dll)
        Call_Asm_Stack2 ImmAssociateContext_c, 2

align 16
InitializeCriticalSection_asm2c:
; InitializeCriticalSection (std1, KERNEL32.dll)
        Call_Asm_Stack1 InitializeCriticalSection_c, 1

align 16
InterlockedDecrement_asm2c:
; InterlockedDecrement (std1, KERNEL32.dll)
        Call_Asm_Stack1 InterlockedDecrement_c, 1

align 16
InterlockedIncrement_asm2c:
; InterlockedIncrement (std1, KERNEL32.dll)
        Call_Asm_Stack1 InterlockedIncrement_c, 1

align 16
isspace_asm2c:
; isspace (c1, MSVCRT.dll)
        Call_Asm_Stack1 isspace_c

align 16
joyGetDevCapsA_asm2c:
; joyGetDevCapsA (std3, WIN32.dll)
        Call_Asm_Stack3 joyGetDevCapsA_c, 3

align 16
joyGetNumDevs_asm2c:
; joyGetNumDevs (std0, WIN32.dll)
        Call_Asm_Stack0 joyGetNumDevs_c, 0

align 16
joyGetPos_asm2c:
; joyGetPos (std2, WINMM.dll)
        Call_Asm_Stack2 joyGetPos_c, 2

align 16
joyGetPosEx_asm2c:
; joyGetPosEx (std2, WIN32.dll)
        Call_Asm_Stack2 joyGetPosEx_c, 2

align 16
LCMapStringA_asm2c:
; LCMapStringA (std6, KERNEL32.dll)
        Call_Asm_Stack6 LCMapStringA_c, 6

align 16
LCMapStringW_asm2c:
; LCMapStringW (std6, KERNEL32.dll)
        Call_Asm_Stack6 LCMapStringW_c, 6

align 16
LeaveCriticalSection_asm2c:
; LeaveCriticalSection (std1, KERNEL32.dll)
        Call_Asm_Stack1 LeaveCriticalSection_c, 1

align 16
LoadCursorA_asm2c:
; LoadCursorA (std2, USER32.dll)
        Call_Asm_Stack2 LoadCursorA_c, 2

align 16
LoadCursorFromFileA_asm2c:
; LoadCursorFromFileA (std1, USER32.dll)
        Call_Asm_Stack1 LoadCursorFromFileA_c, 1

align 16
LoadLibraryA_asm2c:
; LoadLibraryA (std1, KERNEL32.dll)
        Call_Asm_Stack1 LoadLibraryA_c, 1

align 16
LoadModule_asm2c:
; LoadModule (std2, KERNEL32.dll)
        Call_Asm_Stack2 LoadModule_c, 2

align 16
lstrcatA_asm2c:
; lstrcatA (std2, KERNEL32.dll)
        Call_Asm_Stack2 lstrcatA_c, 2

align 16
lstrcpyA_asm2c:
; lstrcpyA (std2, KERNEL32.dll)
        Call_Asm_Stack2 lstrcpyA_c, 2

align 16
malloc_asm2c:
; malloc (c1, MSVCRT.dll)
        Call_Asm_Stack1 malloc_c

align 16
MapViewOfFile_asm2c:
; MapViewOfFile (std5, KERNEL32.dll)
        Call_Asm_Stack5 MapViewOfFile_c, 5

align 16
MapVirtualKeyA_asm2c:
; MapVirtualKeyA (std2, USER32.dll)
        Call_Asm_Stack2 MapVirtualKeyA_c, 2

align 16
mciGetErrorStringA_asm2c:
; mciGetErrorStringA (std3, WIN32.dll)
        Call_Asm_Stack3 mciGetErrorStringA_c, 3

align 16
mciSendCommandA_asm2c:
; mciSendCommandA (std4, WIN32.dll)
        Call_Asm_Stack4 mciSendCommandA_c, 4

align 16
memmove_asm2c:
; memmove (c3, MSVCRT.dll)
        Call_Asm_Stack3 memmove_c

align 16
MessageBoxA_asm2c:
; MessageBoxA (std4, USER32.dll)
        Call_Asm_Stack4 MessageBoxA_c, 4

align 16
MultiByteToWideChar_asm2c:
; MultiByteToWideChar (std6, KERNEL32.dll)
        Call_Asm_Stack6 MultiByteToWideChar_c, 6

align 16
OutputDebugStringA_asm2c:
; OutputDebugStringA (std1, KERNEL32.dll)
        Call_Asm_Stack1 OutputDebugStringA_c, 1

align 16
PeekMessageA_asm2c:
; PeekMessageA (std5, USER32.dll)
        Call_Asm_Stack5 PeekMessageA_c, 5

align 16
PostMessageA_asm2c:
; PostMessageA (std4, USER32.dll)
        Call_Asm_Stack4 PostMessageA_c, 4

align 16
PostQuitMessage_asm2c:
; PostQuitMessage (std1, USER32.dll)
        Call_Asm_Stack1 PostQuitMessage_c, 1

align 16
qsort_asm2c:
; qsort (c4, MSVCRT.dll)
        Call_Asm_Stack4 qsort_c

align 16
rand_asm2c:
; rand (c0, MSVCRT.dll)
        Call_Asm_Stack0 rand_c

align 16
ReadFile_asm2c:
; ReadFile (std5, KERNEL32.dll)
        Call_Asm_Stack5 ReadFile_c, 5

align 16
RealizePalette_asm2c:
; RealizePalette (std1, GDI32.dll)
        Call_Asm_Stack1 RealizePalette_c, 1

align 16
realloc_asm2c:
; realloc (c2, MSVCRT.dll)
        Call_Asm_Stack2 realloc_c

align 16
Rectangle_asm2c:
; Rectangle (std5, GDI32.dll)
        Call_Asm_Stack5 Rectangle_c, 5

align 16
RegCloseKey_asm2c:
; RegCloseKey (std1, ADVAPI32.dll)
        Call_Asm_Stack1 RegCloseKey_c, 1

align 16
RegCreateKeyExA_asm2c:
; RegCreateKeyExA (std9, ADVAPI32.dll)
        Call_Asm_Stack9 RegCreateKeyExA_c, 9

align 16
RegisterClassA_asm2c:
; RegisterClassA (std1, USER32.dll)
        Call_Asm_Stack1 RegisterClassA_c, 1

align 16
RegOpenKeyExA_asm2c:
; RegOpenKeyExA (std5, ADVAPI32.dll)
        Call_Asm_Stack5 RegOpenKeyExA_c, 5

align 16
RegQueryValueExA_asm2c:
; RegQueryValueExA (std6, ADVAPI32.dll)
        Call_Asm_Stack6 RegQueryValueExA_c, 6

align 16
RegSetValueExA_asm2c:
; RegSetValueExA (std6, ADVAPI32.dll)
        Call_Asm_Stack6 RegSetValueExA_c, 6

align 16
ReleaseDC_asm2c:
; ReleaseDC (std2, USER32.dll)
        Call_Asm_Stack2 ReleaseDC_c, 2

align 16
RemoveFontResourceA_asm2c:
; RemoveFontResourceA (std1, GDI32.dll)
        Call_Asm_Stack1 RemoveFontResourceA_c, 1

align 16
ScreenToClient_asm2c:
; ScreenToClient (std2, USER32.dll)
        Call_Asm_Stack2 ScreenToClient_c, 2

align 16
SelectObject_asm2c:
; SelectObject (std2, GDI32.dll)
        Call_Asm_Stack2 SelectObject_c, 2

align 16
SelectPalette_asm2c:
; SelectPalette (std3, GDI32.dll)
        Call_Asm_Stack3 SelectPalette_c, 3

align 16
SendDlgItemMessageA_asm2c:
; SendDlgItemMessageA (std5, USER32.dll)
        Call_Asm_Stack5 SendDlgItemMessageA_c, 5

align 16
SendMessageA_asm2c:
; SendMessageA (std4, USER32.dll)
        Call_Asm_Stack4 SendMessageA_c, 4

align 16
SetBkColor_asm2c:
; SetBkColor (std2, GDI32.dll)
        Call_Asm_Stack2 SetBkColor_c, 2

align 16
SetBkMode_asm2c:
; SetBkMode (std2, GDI32.dll)
        Call_Asm_Stack2 SetBkMode_c, 2

align 16
SetCursor_asm2c:
; SetCursor (std1, USER32.dll)
        Call_Asm_Stack1 SetCursor_c, 1

align 16
SetCursorPos_asm2c:
; SetCursorPos (std2, USER32.dll)
        Call_Asm_Stack2 SetCursorPos_c, 2

align 16
SetDIBColorTable_asm2c:
; SetDIBColorTable (std4, GDI32.dll)
        Call_Asm_Stack4 SetDIBColorTable_c, 4

align 16
SetDIBitsToDevice_asm2c:
; SetDIBitsToDevice (std12, GDI32.dll)
        Call_Asm_Stack12 SetDIBitsToDevice_c, 12

align 16
SetDlgItemTextA_asm2c:
; SetDlgItemTextA (std3, USER32.dll)
        Call_Asm_Stack3 SetDlgItemTextA_c, 3

align 16
SetEndOfFile_asm2c:
; SetEndOfFile (std1, KERNEL32.dll)
        Call_Asm_Stack1 SetEndOfFile_c, 1

align 16
SetFileAttributesA_asm2c:
; SetFileAttributesA (std2, KERNEL32.dll)
        Call_Asm_Stack2 SetFileAttributesA_c, 2

align 16
SetFilePointer_asm2c:
; SetFilePointer (std4, KERNEL32.dll)
        Call_Asm_Stack4 SetFilePointer_c, 4

align 16
SetFocus_asm2c:
; SetFocus (std1, USER32.dll)
        Call_Asm_Stack1 SetFocus_c, 1

align 16
SetLastError_asm2c:
; SetLastError (std1, KERNEL32.dll)
        Call_Asm_Stack1 SetLastError_c, 1

align 16
setlocale_asm2c:
; setlocale (c2, MSVCRT.dll)
        Call_Asm_Stack2 setlocale_c

align 16
SetMapperFlags_asm2c:
; SetMapperFlags (std2, GDI32.dll)
        Call_Asm_Stack2 SetMapperFlags_c, 2

align 16
SetMenu_asm2c:
; SetMenu (std2, USER32.dll)
        Call_Asm_Stack2 SetMenu_c, 2

align 16
SetPaletteEntries_asm2c:
; SetPaletteEntries (std4, GDI32.dll)
        Call_Asm_Stack4 SetPaletteEntries_c, 4

align 16
SetPriorityClass_asm2c:
; SetPriorityClass (std2, KERNEL32.dll)
        Call_Asm_Stack2 SetPriorityClass_c, 2

align 16
SetRect_asm2c:
; SetRect (std5, USER32.dll)
        Call_Asm_Stack5 SetRect_c, 5

align 16
SetStdHandle_asm2c:
; SetStdHandle (std2, KERNEL32.dll)
        Call_Asm_Stack2 SetStdHandle_c, 2

align 16
SetSystemPaletteUse_asm2c:
; SetSystemPaletteUse (std2, GDI32.dll)
        Call_Asm_Stack2 SetSystemPaletteUse_c, 2

align 16
SetTextColor_asm2c:
; SetTextColor (std2, GDI32.dll)
        Call_Asm_Stack2 SetTextColor_c, 2

align 16
setvbuf_asm2c:
; setvbuf (c4, MSVCRT.dll)
        Call_Asm_Stack4 setvbuf_c

align 16
SetWindowLongA_asm2c:
; SetWindowLongA (std3, USER32.dll)
        Call_Asm_Stack3 SetWindowLongA_c, 3

align 16
SetWindowPos_asm2c:
; SetWindowPos (std7, USER32.dll)
        Call_Asm_Stack7 SetWindowPos_c, 7

align 16
ShowCursor_asm2c:
; ShowCursor (std1, USER32.dll)
        Call_Asm_Stack1 ShowCursor_c, 1

align 16
ShowWindow_asm2c:
; ShowWindow (std2, USER32.dll)
        Call_Asm_Stack2 ShowWindow_c, 2

align 16
Sleep_asm2c:
; Sleep (std1, KERNEL32.dll)
        Call_Asm_Stack1 Sleep_c, 1

align 16
SmackBufferBlit_asm2c:
; SmackBufferBlit (std8, smackw32.DLL)
        Call_Asm_Stack8 SmackBufferBlit_c, 8

align 16
SmackBufferClose_asm2c:
; SmackBufferClose (std1, smackw32.DLL)
        Call_Asm_Stack1 SmackBufferClose_c, 1

align 16
SmackBufferNewPalette_asm2c:
; SmackBufferNewPalette (std3, smackw32.DLL)
        Call_Asm_Stack3 SmackBufferNewPalette_c, 3

align 16
SmackBufferOpen_asm2c:
; SmackBufferOpen (std6, smackw32.DLL)
        Call_Asm_Stack6 SmackBufferOpen_c, 6

align 16
SmackBufferSetPalette_asm2c:
; SmackBufferSetPalette (std1, smackw32.DLL)
        Call_Asm_Stack1 SmackBufferSetPalette_c, 1

align 16
SmackClose_asm2c:
; SmackClose (std1, smackw32.DLL)
        Call_Asm_Stack1 SmackClose_c, 1

align 16
SmackColorRemap_asm2c:
; SmackColorRemap (std4, smackw32.DLL)
        Call_Asm_Stack4 SmackColorRemap_c, 4

align 16
SmackDoFrame_asm2c:
; SmackDoFrame (std1, smackw32.DLL)
        Call_Asm_Stack1 SmackDoFrame_c, 1

align 16
SmackNextFrame_asm2c:
; SmackNextFrame (std1, smackw32.DLL)
        Call_Asm_Stack1 SmackNextFrame_c, 1

align 16
SmackOpen_asm2c:
; SmackOpen (std3, smackw32.DLL)
        Call_Asm_Stack3 SmackOpen_c, 3

align 16
SmackSoundOnOff_asm2c:
; SmackSoundOnOff (std2, smackw32.DLL)
        Call_Asm_Stack2 SmackSoundOnOff_c, 2

align 16
SmackSoundUseDirectSound_asm2c:
; SmackSoundUseDirectSound (std1, smackw32.DLL)
        Call_Asm_Stack1 SmackSoundUseDirectSound_c, 1

align 16
SmackToBuffer_asm2c:
; SmackToBuffer (std7, smackw32.DLL)
        Call_Asm_Stack7 SmackToBuffer_c, 7

align 16
SmackToBufferRect_asm2c:
; SmackToBufferRect (std2, smackw32.DLL)
        Call_Asm_Stack2 SmackToBufferRect_c, 2

align 16
SmackWait_asm2c:
; SmackWait (std1, smackw32.DLL)
        Call_Asm_Stack1 SmackWait_c, 1

align 16
sprintf_asm2c:
; sprintf (v2, MSVCRT.dll)
        Call_Asm_VariableStack2 sprintf_c

align 16
srand_asm2c:
; srand (c1, MSVCRT.dll)
        Call_Asm_Stack1 srand_c

align 16
sscanf_asm2c:
; sscanf (v2, MSVCRT.dll)
        Call_Asm_VariableStack2 sscanf_c

align 16
strchr_asm2c:
; strchr (c2, MSVCRT.dll)
        Call_Asm_Stack2 strchr_c

align 16
StretchBlt_asm2c:
; StretchBlt (std11, GDI32.dll)
        Call_Asm_Stack11 StretchBlt_c, 11

align 16
strncmp_asm2c:
; strncmp (c3, MSVCRT.dll)
        Call_Asm_Stack3 strncmp_c

align 16
strncpy_asm2c:
; strncpy (c3, MSVCRT.dll)
        Call_Asm_Stack3 strncpy_c

align 16
strpbrk_asm2c:
; strpbrk (c2, MSVCRT.dll)
        Call_Asm_Stack2 strpbrk_c

align 16
strrchr_asm2c:
; strrchr (c2, MSVCRT.dll)
        Call_Asm_Stack2 strrchr_c

align 16
strstr_asm2c:
; strstr (c2, MSVCRT.dll)
        Call_Asm_Stack2 strstr_c

align 16
strtok_asm2c:
; strtok (c2, MSVCRT.dll)
        Call_Asm_Stack2 strtok_c

align 16
TerminateProcess_asm2c:
; TerminateProcess (std2, KERNEL32.dll)
        Call_Asm_Stack2 TerminateProcess_c, 2

align 16
TextOutA_asm2c:
; TextOutA (std5, GDI32.dll)
        Call_Asm_Stack5 TextOutA_c, 5

align 16
time_asm2c:
; time (c1, MSVCRT.dll)
        Call_Asm_Stack1 time_c

align 16
timeGetTime_asm2c:
; timeGetTime (std0, WIN32.dll)
        Call_Asm_Stack0 timeGetTime_c, 0

align 16
TlsGetValue_asm2c:
; TlsGetValue (std1, KERNEL32.dll)
        Call_Asm_Stack1 TlsGetValue_c, 1

align 16
TlsSetValue_asm2c:
; TlsSetValue (std2, KERNEL32.dll)
        Call_Asm_Stack2 TlsSetValue_c, 2

align 16
ToAscii_asm2c:
; ToAscii (std5, USER32.dll)
        Call_Asm_Stack5 ToAscii_c, 5

align 16
tolower_asm2c:
; tolower (c1, MSVCRT.dll)
        Call_Asm_Stack1 tolower_c

align 16
toupper_asm2c:
; toupper (c1, MSVCRT.dll)
        Call_Asm_Stack1 toupper_c

align 16
TranslateMessage_asm2c:
; TranslateMessage (std1, USER32.dll)
        Call_Asm_Stack1 TranslateMessage_c, 1

align 16
UnmapViewOfFile_asm2c:
; UnmapViewOfFile (std1, KERNEL32.dll)
        Call_Asm_Stack1 UnmapViewOfFile_c, 1

align 16
UpdateWindow_asm2c:
; UpdateWindow (std1, USER32.dll)
        Call_Asm_Stack1 UpdateWindow_c, 1

align 16
ValidateRect_asm2c:
; ValidateRect (std2, USER32.dll)
        Call_Asm_Stack2 ValidateRect_c, 2

align 16
VirtualAlloc_asm2c:
; VirtualAlloc (std4, KERNEL32.dll)
        Call_Asm_Stack4 VirtualAlloc_c, 4

align 16
VirtualFree_asm2c:
; VirtualFree (std3, KERNEL32.dll)
        Call_Asm_Stack3 VirtualFree_c, 3

align 16
VirtualQuery_asm2c:
; VirtualQuery (std3, KERNEL32.dll)
        Call_Asm_Stack3 VirtualQuery_c, 3

align 16
WaitForSingleObject_asm2c:
; WaitForSingleObject (std2, KERNEL32.dll)
        Call_Asm_Stack2 WaitForSingleObject_c, 2

align 16
WideCharToMultiByte_asm2c:
; WideCharToMultiByte (std8, KERNEL32.dll)
        Call_Asm_Stack8 WideCharToMultiByte_c, 8

align 16
WriteFile_asm2c:
; WriteFile (std5, KERNEL32.dll)
        Call_Asm_Stack5 WriteFile_c, 5

align 16
wsprintfA_asm2c:
; wsprintfA (v2, USER32.dll)
        Call_Asm_VariableStack2 wsprintfA_c

align 16
wvsprintfA_asm2c:
; wvsprintfA (std3, USER32.dll)
        Call_Asm_Stack3 wvsprintfA_c, 3

align 16
strspn_asm2c:
; strspn (c2, static)
        Call_Asm_Stack2 strspn_c

align 16
strcspn_asm2c:
; strcspn (c2, static)
        Call_Asm_Stack2 strcspn_c

align 16
strncat_asm2c:
; strncat (c3, static)
        Call_Asm_Stack3 strncat_c

align 16
vsprintf_asm2c:
; vsprintf (c3, static)
        Call_Asm_Stack3 vsprintf_c

align 16
memcpy_asm2c:
; memcpy (c3, static)
        Call_Asm_Stack3 memcpy_c

align 16
printf_asm2c:
; printf (v1, static)
        Call_Asm_VariableStack1 printf_c

align 16
ungetc_asm2c:
; ungetc (c2, static)
        Call_Asm_Stack2 ungetc_c

align 16
_filbuf_asm2c:
; _filbuf (c1, static)
        Call_Asm_Stack1 _filbuf_c

align 16
i76_frame_tick_asm2c:
; i76_frame_tick (std0, runtime)
        Call_Asm_Stack0 i76_frame_tick_c, 0

align 16
i76shell_part_strncmp_asm2c:
; i76shell_part_strncmp (c3, runtime)
        Call_Asm_Stack3 i76shell_part_strncmp_c

