#!/usr/bin/env python3
# Generates the SPIR-V shaders of the Vulkan backend (render_vk.c) -> ../vk_shaders.h (committed: building
# doesn't need a shader compiler). Needs glslangValidator. vk_glide.frag is derived from the OpenGL backend's
# Glide fragment shader (render_gl.c glide_fs), so both stay the same.
import os, re, subprocess, sys, tempfile

here = os.path.dirname(os.path.abspath(__file__))

def make_glide_frag():
    src = open(os.path.join(here, '..', 'render_gl.c')).read()
    a = src.index('static const char *glide_fs =')
    b = src.index('"}\\n";', a) + len('"}\\n";')
    lines = re.findall(r'^\s*"(.*)\\n"', src[a:b], re.M)
    text = '\n'.join(l.replace('\\\\', '\\') for l in lines)
    text = text.replace('#version 330 core', '#version 450')
    ubo = open(os.path.join(here, 'vk_glide_ubo.glsl')).read().strip()
    text = text.replace('noperspective in vec4 v_color;\nnoperspective in vec2 v_depth;\nsmooth in vec2 v_st;\n',
                        'layout(location = 0) noperspective in vec4 v_color;\nlayout(location = 1) noperspective in vec2 v_depth;\nlayout(location = 2) in vec2 v_st;\n')
    text = re.sub(r'uniform sampler2D u_tex;\n(uniform [^\n]*\n)+', ubo + '\nlayout(set = 1, binding = 0) uniform sampler2D u_tex;\n', text)
    text = text.replace('out vec4 o_color;', 'layout(location = 0) out vec4 o_color;')
    for n in ('textured', 'chroma_color', 'chroma', 'fog_color', 'fog_table', 'depth_mode', 'cc', 'ac', 'tc', 'inv'):
        text = re.sub(r'\bu_%s\b' % n, 'u.%s' % n, text)
    text = re.sub(r'\bu_fog\b', 'u.fog', text)
    text = re.sub(r'\bu_const\b', 'u.constcolor', text)
    text = text.replace('u.chroma_color)', 'u.chroma_color.rgb)').replace('u.fog_color,', 'u.fog_color.rgb,')
    text = re.sub(r'u\.fog_table\[(\w+)\]', r'u.fog_table[\1 >> 2][\1 & 3]', text)
    open(os.path.join(here, 'vk_glide.frag'), 'w').write(
        '// Glide pixel pipeline: generated by gen_vk_shaders.py from render_gl.c glide_fs - do not edit\n' + text + '\n')

make_glide_frag()
out = ['/* generated by shaders/gen_vk_shaders.py - do not edit */\n\n#include <stdint.h>\n\n']
for name in ('vk_quad.vert', 'vk_quad.frag', 'vk_post.frag', 'vk_glide.vert', 'vk_glide.frag'):
    with tempfile.TemporaryDirectory() as tmp:
        spv = os.path.join(tmp, 'out.spv')
        r = subprocess.run(['glslangValidator', '-V', '--quiet', os.path.join(here, name), '-o', spv], capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit(r.stdout + r.stderr)
        data = open(spv, 'rb').read()
    words = [int.from_bytes(data[i:i + 4], 'little') for i in range(0, len(data), 4)]
    var = name.replace('.', '_')
    out.append('static const uint32_t %s[] = {\n' % var)
    for i in range(0, len(words), 8):
        out.append('    ' + ', '.join('0x%08x' % w for w in words[i:i + 8]) + ',\n')
    out.append('};\n\n')
open(os.path.join(here, '..', 'vk_shaders.h'), 'w').write(''.join(out))
print('vk_shaders.h written')
