// Glide pixel pipeline: generated by gen_vk_shaders.py from render_gl.c glide_fs - do not edit
#version 450
layout(location = 0) noperspective in vec4 v_color;
layout(location = 1) noperspective in vec2 v_depth;
layout(location = 2) in vec2 v_st;
layout(set = 0, binding = 0) uniform Glide {
    vec2 screen; vec2 texscale;
    ivec4 cc; ivec4 ac; ivec4 tc; ivec4 inv;
    vec4 constcolor;
    vec4 chroma_color;
    vec4 fog_color;
    int textured; int chroma; int fog; int depth_mode;
    vec4 fog_table[16];
} u;
layout(set = 1, binding = 0) uniform sampler2D u_tex;
layout(location = 0) out vec4 o_color;

float factor_s(int f, float local, float local_a, float other_a, float tex_a) {
    if (f == 0) return 0.0;
    if (f == 1) return local;
    if (f == 2) return other_a;
    if (f == 3) return local_a;
    if (f == 4) return tex_a;
    if (f == 5) return 0.0;
    if (f == 9) return 1.0 - local;
    if (f == 10) return 1.0 - other_a;
    if (f == 11) return 1.0 - local_a;
    if (f == 12) return 1.0 - tex_a;
    return 1.0;
}
vec3 factor_v(int f, vec3 local, float local_a, float other_a, float tex_a) {
    if (f == 1) return local;
    if (f == 9) return vec3(1.0) - local;
    return vec3(factor_s(f, 0.0, local_a, other_a, tex_a));
}
vec3 func_v(int fn, vec3 f, vec3 local, float local_a, vec3 other) {
    if (fn == 0) return vec3(0.0);
    if (fn == 1) return local;
    if (fn == 2) return vec3(local_a);
    if (fn == 3) return f * other;
    if (fn == 4) return f * other + local;
    if (fn == 5) return f * other + vec3(local_a);
    if (fn == 6) return f * (other - local);
    if (fn == 7) return f * (other - local) + local;
    if (fn == 8) return f * (other - local) + vec3(local_a);
    if (fn == 9) return f * (-local) + local;
    if (fn == 16) return f * (-local) + vec3(local_a);
    return vec3(0.0);
}
float func_s(int fn, float f, float local, float other) {
    return func_v(fn, vec3(f), vec3(local), local, vec3(other)).x;
}

void main() {
    vec4 iter = clamp(v_color, 0.0, 1.0);
    vec4 tex = vec4(1.0);
    if (u.textured != 0) {
        vec4 t = texture(u_tex, v_st);
        vec3 frgb = factor_v(u.tc.y, t.rgb, t.a, 0.0, 0.0);
        tex.rgb = func_v(u.tc.x, frgb, t.rgb, t.a, vec3(0.0));
        float fa = factor_s(u.tc.w, t.a, t.a, 0.0, 0.0);
        tex.a = func_s(u.tc.z, fa, t.a, 0.0);
        if (u.inv.z != 0) tex.rgb = vec3(1.0) - tex.rgb;
        if (u.inv.w != 0) tex.a = 1.0 - tex.a;
        tex = clamp(tex, 0.0, 1.0);
    }
    float a_local = (u.ac.z == 0) ? iter.a : ((u.ac.z == 1) ? u.constcolor.a : clamp(v_depth.x / 65535.0, 0.0, 1.0));
    float a_other = (u.ac.w == 0) ? iter.a : ((u.ac.w == 1) ? tex.a : u.constcolor.a);
    vec3 c_local = (u.cc.z == 1) ? u.constcolor.rgb : iter.rgb;
    vec4 c_other = (u.cc.w == 0) ? iter : ((u.cc.w == 1) ? tex : u.constcolor);
    vec3 cf = factor_v(u.cc.y, c_local, a_local, c_other.a, tex.a);
    vec3 rgb = func_v(u.cc.x, cf, c_local, a_local, c_other.rgb);
    if (u.inv.x != 0) rgb = vec3(1.0) - rgb;
    float af = factor_s(u.ac.y, a_local, a_local, a_other, tex.a);
    float alpha = func_s(u.ac.x, af, a_local, a_other);
    if (u.inv.y != 0) alpha = 1.0 - alpha;
    rgb = clamp(rgb, 0.0, 1.0);
    alpha = clamp(alpha, 0.0, 1.0);
    if (u.chroma != 0) {
        vec3 key = c_other.rgb;
        if (u.cc.w == 1 && u.textured != 0) {
            ivec2 ts = textureSize(u_tex, 0);
            key = texelFetch(u_tex, ivec2(mod(floor(v_st * vec2(ts)), vec2(ts))), 0).rgb;
        }
        if (all(equal(floor(key * 255.0 + 0.5), u.chroma_color.rgb))) discard;
    }
    int fm = u.fog & 0xFF;
    if (fm != 0) {
        float f = 0.0;
        if (fm == 1) f = iter.a;
        else if (fm == 2) {
            float w = 1.0 / max(v_depth.y, 1e-9);
            float lw = log2(max(w, 1.0));
            float fi = clamp((lw - 0.0) * 4.0, 0.0, 63.0);
            int i0 = int(fi);
            int i1 = min(i0 + 1, 63);
            f = mix(u.fog_table[i0 >> 2][i0 & 3], u.fog_table[i1 >> 2][i1 & 3], fi - float(i0));
        }
        else if (fm == 3) f = clamp(v_depth.x / 65535.0, 0.0, 1.0);
        rgb = mix(rgb, u.fog_color.rgb, clamp(f, 0.0, 1.0));
    }
    o_color = vec4(rgb, alpha);
    if (u.depth_mode == 1 || u.depth_mode == 3) gl_FragDepth = clamp(v_depth.x / 65535.0, 0.0, 1.0);
    else if (u.depth_mode == 2 || u.depth_mode == 4) gl_FragDepth = clamp(log2(1.0 / max(v_depth.y, 1e-9) + 1.0) / 32.0, 0.0, 1.0);
    else gl_FragDepth = 0.5;
}
